/*
 Copyright © 2019 Stewart J. Robinson (AKA StewVed, Ved)
 To show your appreciation of my work, feel free to talk about, and link to my website(s)
 If you wish to copy/use code from [any part of] my website(s), please contact me. Thankyou.
*/
var ya,x,za=0,Aa=0,n=[],y,Ba,Ca,z=[],Da=!1,Ea=!1,Fa=!1,A=[],Ga=[],B=[],C={window:0,x:[0,0],y:[0,0]},D,Ha=!1,E=[],F=0,G=[],H=10,J={active:"none",sc:"",Pb:""},Ia=0,Ja=0,K,L,M,N,Ka,La,Ma="",Na=!1,Oa="",Pa=0,Qa=-1,Ua=[365/7,365/14,365/28,12,4,2,1],Va,Wa,Xa,Ya,Za,$a,ab,va,bb="@#~",O="~#@",P,cb,db=!1,eb=document.exitFullscreen||document.mozCancelFullScreen||document.webkitExitFullscreen||document.msExitFullscreen,fb=document.documentElement.requestFullscreen||document.documentElement.mozRequestFullScreen||
document.documentElement.webkitRequestFullscreen||document.documentElement.msRequestFullscreen;
function ua(){va=document.getElementById("spriteMain");D='style="background:url('+va.src+")";gb[1].Text='<img class="imgSocs" '+D+' -146px -26px;"'+w+">Feedback / Contact Webapp";document.body.style.cursor="default";document.getElementById("Load")&&document.getElementById("Load").parentNode.removeChild(document.getElementById("Load"));hb();(u=ib("webtopTheme"))||(u=0);(x=ib("webtopStyle"))||(x="Ub");ya=ib("showErrors");jb();kb();lb();mb(0);K=document.getElementById("pup");L=document.getElementById("pupc");
M=document.getElementById("pupD");N=document.getElementById("pupDc");Ka=document.getElementById("pupB");nb();window.setInterval(function(){nb()},1E3);ob();window.addEventListener("resize",ob);document.addEventListener("contextmenu",pb);window.addEventListener("wheel",qb);document.addEventListener("touchstart",rb);document.addEventListener("touchmove",sb);document.addEventListener("touchcancel",tb);document.addEventListener("touchend",tb);document.addEventListener("touchleave",tb);document.addEventListener("mousedown",
ub);document.addEventListener("mousemove",vb);document.addEventListener("mouseup",wb);document.addEventListener("dblclick",pb);document.addEventListener("keydown",xb);document.addEventListener("keyup",yb);window.addEventListener("gamepadconnected",zb);window.addEventListener("gamepaddisconnected",Ab);Bb();document.getElementById("UnityPanel").classList.add(t[u].La);Cb();fa?oa(fa+"_2.js","script","","apps & games","",0):ma(2);oa(fa+"_3.js","script","","Text (Changelogs, etc.)","",0);document.getElementById("cpContact").outerHTML=
"Stewart Robinson"}function Cb(){for(var a in Q);document.getElementById("Wallpaper").style.opacity=1;window.setTimeout(function(){Db()},2200)}
function Eb(a,c){var d='<img id="'+a+'appImg" class="winTitleIcon" ';" -"==Q[E[a].Window.qa].C.slice(0,2)?(a=Q[E[a].Window.qa].C.split(" "),d+='style="position:absolute;z-index:0;transition:opacity 1s;opacity:'+c+";left:4px;background-image: url("+va.src+");background-position:"+parseFloat(a[1])/2.75+"px "+parseFloat(a[2])/2.75+'px;"'):d+='style="background:center/contain no-repeat url('+Q[E[a].Window.qa].C+');"';return d+w+">"}
function kb(){var a='<img id="Tl" class="lTriangle" '+D+' -119px -44px;left:58px;top:54px;"'+w+">",c;for(c in R)a+='<div id="C_'+S[R[parseFloat(c)]].s+'" class="LauncherContainer">',a+='<img id="T_'+S[R[parseFloat(c)]].s+'" class="lTriangle" '+D+' -131px -44px;"'+w+">",a+='<div id="D_'+S[R[parseFloat(c)]].s+'" class="LauncherIconBack" style="background-color:'+S[R[parseFloat(c)]].K+';"></div>',a+='<img id="L_'+S[R[parseFloat(c)]].s+'" class="LauncherIcon" ',a=" -"==S[R[parseFloat(c)]].C.slice(0,2)?
a+(D+S[R[parseFloat(c)]].C+';"'+w+">"):a+("style=\"background:center/contain no-repeat url('"+S[R[parseFloat(c)]].C+"');\""+w+">"),a+='<img id="Lc_'+S[R[parseFloat(c)]].s+'" class="LauncherIconCover ttElem" '+D+' -198px -26px;"'+w+">",a+="</div>";document.body.innerHTML+='<canvas id="backGround"></canvas><div id="Wallpaper" class="Wallpaper"><div id="winCover"></div><div id="pupB" class="ttElem"></div><div id="pup" class="ttElem"></div><div id="pupc" class="ttElem"></div><div id="pupD" class="ttElem"></div><div id="pupDc" class="ttElem"></div><div id="UnityPanel"><div id="UPTitle" class="winTitle" style="color: rgb(223,219,210);margin-left:8px;height:24px;transition:opacity 1s;"></div><div id="gMxTitle" style="position:absolute;overflow:hidden;cursor:default;"></div><div id="kTaskBar"><div id="b_0" style="height:32px;width:33px;background-color:transparant;position:relative;float:left;margin:0;padding:0;"> <img id="i_0" class="kTaskImg" style="background-size:180px;background-image:url('+
va.src+");background-position:"+.5*parseFloat(S[0].C.split(" ")[1])+"px "+.5*parseFloat(S[0].C.split(" ")[2])+'px;left:0px;width:36px;height:36px;margin:4px;"'+w+'></div></div><div id="indicatorPanel"><img id="System" class="PanelIcons" '+D+' -120px -21px;"'+w+'><div id="Time" class="PanelIcons" style="width:auto;"></div><img id="Volume" class="PanelIcons" '+D+'  -188px -0px;"'+w+'><img id="Messages" class="PanelIcons" '+D+'  -143px -22px;"'+w+'></div></div><div id="uLauncher">'+a+'</div><div id="cpy"><span class="cp">Copyright&nbsp;&copy;&nbsp;2019 </span><span id="0_cpContact" class="toolTipclass">Stewart J. Robinson</span><span class="cp"><br>Stewved&apos;s Webtop is modeled after </span></span><a class="ubLink" href="http://www.ubuntu.com/" target="_blank">Ubuntu OS</a></div></div>';
Fb(1);document.getElementById("C_0").style.marginTop="5px";E[0]=[];E[0].Window={H:"Desktop",R:"",yd:!1};E[0].va=Gb;E[0].Nc={cpContact:'<p class="B pZW">Contact StewVed:<br></p><img class="imgSocs" '+D+' -146px -26px;"'+w+"><a id='contactFB' class='ubLink'>Feedback / Contact Webapp</a><br><img class=\"imgSocs\" "+Hb+"Facebook.png');\""+w+"><a class='ubLink' href='https://www.facebook.com/StewvedsWebtop' target='_blank'>Stewved's Webtop on FaceBook</a><br><img class=\"imgSocs\" "+Hb+"Facebook.png');\""+
w+"><a class='ubLink' href='https://www.facebook.com/Stewved' target='_blank'>Stewved on FaceBook</a><br><img class=\"imgSocs\" "+Hb+"Twitter.png');\""+w+"><a class='ubLink' href='https://twitter.com/StewVed' target='_blank'>Stewved on Twitter</a><br><hr><img class=\"imgSocs\" style=\"background:center/contain no-repeat url('images/1425710397e.svg');\""+w+"><a class='ubLink' href='https://stewved.co.uk/support-stewved' target='_blank'>Support StewVed</a>"}}
function Ib(a){if(a){a=a.split(",");for(var c in a)window.open(a[c],"_blank")}}
function wa(a){var c=new Date;c>=a?(Ja=Math.floor((c-a)/1E3),c="since "):(Ja=Math.floor((a-c)/1E3),c="until ");var d="",e="("+(Ja/86400/365*100).toFixed(2)+"% of a year.)";31536E3<=Ja&&(d+=Jb(31536E3,"year")+", ");2628E3<=Ja&&(d+=Jb(2628E3,"month")+", ");604800<=Ja&&(d+=Jb(604800,"week")+", ");86400<=Ja&&(d+=Jb(86400,"day")+", ");3600<=Ja&&(d+=Jb(3600,"hour")+", ");60<=Ja&&(d+=Jb(60,"minute")+", ");d+=Jb(1,"second")+"<br>";100>=parseFloat(e.slice(1))&&(d+=e);return"Time "+c+a.toDateString()+"<br>"+
d}function Kb(a){document.getElementById("NotyCont"+a).style.opacity=0;window.setTimeout(function(){delete n[a];document.getElementById("NotyCont"+a).parentNode.removeChild(document.getElementById("NotyCont"+a));xa()},500)}
function xa(){if(0<n.length){var a=0,c=[];if("Ub"===x)for(var d in n){c.push(d);if(0<a){var e=document.getElementById("NotyCont"+c[a-1]),f=document.getElementById("NotyCont"+c[a]);e&&f&&(f.style.top=Number(e.style.top.slice(0,-2))+e.offsetHeight+4+"px")}else document.getElementById("NotyCont"+n[parseFloat(d)]).style.top=Number(document.getElementById("UnityPanel").style.height.slice(0,-2))+4+"px";document.getElementById("NotyCont"+n[parseFloat(d)]).style.left=document.getElementById("Wallpaper").offsetWidth-
document.getElementById("NotyCont"+n[parseFloat(d)]).offsetWidth-4+"px";a++}else for(d in n)c.push(d),0<a?(e=document.getElementById("NotyCont"+c[a-1]),f=document.getElementById("NotyCont"+c[a]),e&&f&&(f.style.top=Number(e.style.top.slice(0,-2))-f.offsetHeight-4+"px")):document.getElementById("NotyCont"+n[parseFloat(d)]).style.top=Number(document.getElementById("UnityPanel").style.top.slice(0,-2))-document.getElementById("NotyCont"+n[parseFloat(d)]).offsetHeight-4+"px",a++}}
function Lb(){if(!document.getElementById("RizzsXmasTimer")){var a=new Date((new Date).getFullYear(),11,25);new Date>a&&a.setFullYear(a.getFullYear()+1);l('For <a class="ubLink" href="https://www.facebook.com/chris.booker.5" target="_blank">Chrs Booker</a>, Until Xmas:<br><div id="RizzsXmasTimer">000 days, 00 hours, 00 minutes, 00 seconds<br>(100% of a year.)</div>')}}function Jb(a,c){var d=Math.floor(Ja/a);Ja-=a*d;return 1==d?"1 "+c:d+" "+c+"s"}
function Mb(a,c){var d=db.createOscillator(),e=db.createGain();d.connect(e);e.connect(db.destination);d.type="sine";d.frequency.value=a;e.gain.value=1;d.start();setTimeout(function(){d.stop()},c)}function Nb(a){K.innerHTML='<p style="margin:0;padding:0;text-align:center;">'+a.replace(/~#/g,"&").replace(/#Q/g,"&quot").replace(/-Q-/g,'\\"')+"</p>";Ob()}function Pb(a){10>a&&(a="0"+a);return a}
function nb(){var a=new Date;a=Pb(a.getHours())+":"+Pb(a.getMinutes());a!=document.getElementById("Time").innerHTML&&(document.getElementById("Time").innerHTML=a);document.getElementById("RizzsXmasTimer")&&(a=new Date((new Date).getFullYear(),11,25),new Date>a&&a.setFullYear(a.getFullYear()+1),document.getElementById("RizzsXmasTimer").innerHTML=wa(a),a=document.getElementById("RizzsXmasTimer").parentNode,a.style.borderColor="rgb(255, 255, 255"==a.style.borderColor.slice(0,17)?"rgb(225,0,0)":"rgb(225, 0"==
a.style.borderColor.slice(0,10)?"rgb(0,255,0":"rgb(255,255,255)")}
function ob(){P=document.getElementById("Wallpaper").offsetWidth-(document.getElementById("uLauncher").offsetWidth+1+document.getElementById("uLauncher").offsetLeft);cb=document.getElementById("uLauncher").offsetWidth+1+document.getElementById("uLauncher").offsetLeft;document.body.style.height=window.innerHeight+"px";if(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||document.msFullscreenElement)if(-1==Qa||0==Qa)Qa=0,E[0].Window.R="full";else{if(0<Qa){var a=
Qa,c=document.getElementById(a),d=document.getElementById(a+"Cont");c.style.left="-8px";c.style.top="-8px";d.style.width=document.getElementById("Wallpaper").offsetWidth+"px";d.style.height=document.getElementById("Wallpaper").offsetHeight+"px";d.style.top=-document.getElementById(a+"TopBar").offsetHeight+"px";E[a].Window.bd=E[a].Window.R;E[a].Window.R="full";c.style.zIndex=999;d.style.height=document.getElementById("Wallpaper").offsetHeight+"px";d.style.top=document.getElementById(a+"TopBar").offsetHeight+
"px";Qb(a);document.getElementById(a+"TopBar").style.opacity=0;document.getElementById("UnityPanel").style.opacity=0;Rb(Qa)}}else-1<Qa&&(Sb(),E[0].Window.R="");document.getElementById("lExpo")&&Tb();document.getElementById("cpy").style.left=cb+"px";document.getElementById("cpy").style.left=document.getElementById("Wallpaper").offsetWidth-document.getElementById("cpy").offsetWidth-4+"px";Ub("resize");"Ku"==x?(document.getElementById("UnityPanel").style.top=document.getElementById("Wallpaper").offsetHeight-
document.getElementById("UnityPanel").offsetHeight+"px",document.getElementById("cpy").style.top=document.getElementById("Wallpaper").offsetHeight-document.getElementById("cpy").offsetHeight-document.getElementById("UnityPanel").offsetHeight-2+"px",document.getElementById("kTaskBar").style.width=document.getElementById("indicatorPanel").offsetLeft+"px"):(document.getElementById("cpy").style.top=document.getElementById("Wallpaper").offsetHeight-document.getElementById("cpy").offsetHeight-2+"px",document.getElementById("gMxTitle").style.width=
document.getElementById("indicatorPanel").offsetLeft+"px");xa();for(var e in E){if("max"==E[parseFloat(e)].Window.R||"full"==E[parseFloat(e)].Window.R)var f=document.getElementById(e),g=document.getElementById(e+"Cont");f&&(f.style.top=-H+"px","max"==E[parseFloat(e)].Window.R?"Ku"==x?(f.style.left=-H+"px",g.style.width=document.getElementById("Wallpaper").offsetWidth+"px",g.style.height=document.getElementById("Wallpaper").offsetHeight-document.getElementById("UnityPanel").offsetHeight+"px"):"Ub"==
x&&(f.style.left=cb-H+"px",g.style.width=P+"px",g.style.height=document.getElementById("Wallpaper").offsetHeight-document.getElementById("UnityPanel").offsetHeight+"px"):(g.style.width=document.getElementById("Wallpaper").offsetWidth+"px",g.style.height=document.getElementById("Wallpaper").offsetHeight+"px",g.style.top=-document.getElementById(e+"TopBar").offsetHeight+"px"),Rb(e))}document.getElementById("NotyCont")&&(document.getElementById("NotyCont").style.left=document.getElementById("Wallpaper").offsetWidth-
document.getElementById("NotyCont").offsetWidth-4+"px")}
function Rb(a){E[a].Window.ra?Vb(a):(document.getElementById(a+"Box").style.width=document.getElementById(a+"Cont").offsetWidth+"px",document.getElementById(a+"Box").style.height=document.getElementById(a+"Cont").offsetHeight+"px");if("Bencher"==E[a].Window.H)document.getElementById(a+"_bb_gameArea")&&(E[a].a.sa=document.getElementById(a+"Cont").offsetWidth,E[a].a.wa=document.getElementById(a+"Cont").offsetHeight,1<E[a].a.Ma?(E[a].a.Ja.width=E[a].a.sa,E[a].a.Ja.height=E[a].a.wa):(E[a].a.Ja.style.width=
E[a].a.sa+"px",E[a].a.Ja.style.height=E[a].a.wa+"px"));else if("Vydio"==E[a].Window.H){var c=document.getElementById(a+"Cont"),d=.08*c.offsetHeight,e=c.offsetHeight;document.getElementById(a+"VidSeek1").style.top=e-d-6+"px";document.getElementById(a+"VidSeek1").style.height=d+"px";document.getElementById(a+"VidSeek1").style.left="4px";document.getElementById(a+"VidSeek1").style.width=c.offsetWidth-4+"px";document.getElementById(a+"VidVol1").style.top=e/2-6+"px";document.getElementById(a+"VidVol1").style.height=
e/2-d-4+"px";document.getElementById(a+"VidVol1").style.left=c.offsetWidth-d-4+"px";document.getElementById(a+"VidVol1").style.width=d+"px";e=document.getElementById(a+"OSD");e.style.left="0px";e.style.fontSize=.33*c.offsetHeight+"%";e.style.left=c.offsetWidth/2-e.offsetWidth/2+"px";e.style.top=document.getElementById(a+"VidSeek1").offsetTop+(d/2-e.offsetHeight/2)+"px"}else"WrdSrch"==E[a].Window.H?Wb(a):"JSCavern"==E[a].Window.H?Xb(a):"Screens"==E[a].Window.H?Yb(a,0):"wall"==E[a].Window.H?Zb(a):12==
a?$b(a):13==a?ac():"GProto"==E[a].Window.H&&bc(a)}
function Qb(a){var c=document.getElementById(a),d=document.getElementById(a+"Box"),e=document.getElementById("Wallpaper"),f=c.offsetWidth-2*H;f>e.offsetWidth-cb&&(d.style.width=f-cb+"px");c=c.offsetHeight-2*H;var g;"max"==E[a].Window.R?c>e.offsetHeight&&(g=e.offsetHeight-document.getElementById("UnityPanel").offsetHeight):c>e.offsetHeight-document.getElementById("UnityPanel").offsetHeight&&(g=e.offsetHeight-document.getElementById("UnityPanel").offsetHeight-document.getElementById(a+"TopBar").offsetHeight);
g&&(d.style.height=g+"px",E[a].Window.ra&&(z.ma="n-resize",Vb(a),z.ma=""));Rb(a)}
function Vb(a){var c=document.getElementById(a+"Box");if("max"==E[a].Window.R||"n-resize"==z.ma||"s-resize"==z.ma){var d=c.offsetHeight/E[a].Window.A;c.style.width=E[a].Window.u*d+"px"}else d=c.offsetWidth/E[a].Window.u,c.style.height=E[a].Window.A*d+"px";"max"!=E[a].Window.R&&"full"!=E[a].Window.R||cc(a);E[a].Window.m&&(c=document.getElementById(a+"Box"),d=c.offsetWidth/E[a].Window.u,c.style.fontSize=100*d+"%",dc(a,c,d),E[a].Window.m=d)}
function dc(a,c,d){if(c.hasChildNodes()){c=c.children;for(var e=0;e<c.length;e++){try{var f=c[e].nodeName.toLowerCase();if("br"!=f&&"option"!=f&&""!=f&&"table"!=f&&"tbody"!=f&&"tr"!=f&&"td"!=f&&(f=c[e].parentNode.nodeName.toLowerCase(),"br"!=f&&"option"!=f&&""!=f&&"table"!=f&&"tbody"!=f&&"tr"!=f&&"td"!=f)){var g=c[e].style.left.slice(0,-2),h=c[e].style.top.slice(0,-2),m=c[e].style.width.slice(0,-2),p=c[e].style.height.slice(0,-2);0==p.length&&(p=c[e].clientHeight);0==m.length&&(m=c[e].clientWidth);
"%"!=c[e].style.left.slice(-1)&&(c[e].style.left=g/E[a].Window.m*d+"px");"%"!=c[e].style.top.slice(-1)&&(c[e].style.top=h/E[a].Window.m*d+"px");"%"!=c[e].style.width.slice(-1)&&(c[e].style.width=m/E[a].Window.m*d+"px");"%"!=c[e].style.height.slice(-1)&&(c[e].style.height=p/E[a].Window.m*d+"px");c[e].style.borderLeftWidth&&(c[e].style.borderLeftWidth=parseFloat(c[e].style.borderLeftWidth)/E[a].Window.m*d+"px");c[e].style.borderRightWidth&&(c[e].style.borderRightWidth=parseFloat(c[e].style.borderRightWidth)/
E[a].Window.m*d+"px");c[e].style.borderTopWidth&&(c[e].style.borderTopWidth=parseFloat(c[e].style.borderTopWidth)/E[a].Window.m*d+"px");c[e].style.borderBottomWidth&&(c[e].style.borderBottomWidth=parseFloat(c[e].style.borderBottomWidth)/E[a].Window.m*d+"px")}}catch(r){}0<c[e].childElementCount&&dc(a,c[e],d)}}}
function ec(a){if(a.hasChildNodes()){a=a.children;for(var c=a.length-1;0<=c;c--){var d=a[c].nodeName.toLowerCase();"br"!=d&&"option"!=d&&""!=d&&"table"!=d&&"tbody"!=d&&"tr"!=d&&"td"!=d&&(d=a[c].parentNode.nodeName.toLowerCase(),"br"!=d&&"option"!=d&&""!=d&&"table"!=d&&"tbody"!=d&&"tr"!=d&&"td"!=d&&("relative"!=a[c].style.position&&(a[c].style.left=a[c].offsetLeft+"px",a[c].style.top=a[c].offsetTop+"px"),a[c].style.boxSizing="border-box",a[c].style.width=a[c].offsetWidth+"px",parseFloat(a[c].style.width)!=
a[c].offsetWidth&&(a[c].style.width=parseFloat(a[c].style.width)+(parseFloat(a[c].style.width)-a[c].offsetWidth)+"px"),a[c].style.height=a[c].offsetHeight+"px",parseFloat(a[c].style.height)!=a[c].offsetHeight&&(a[c].style.height=parseFloat(a[c].style.height)+(parseFloat(a[c].style.height)-a[c].offsetHeight)+"px"),d=a[c].parentNode.offsetWidth,a[c].style.marginLeft&&"%"!=a[c].style.marginLeft.slice(-1)&&(a[c].style.marginLeft=100*parseFloat(a[c].style.marginLeft)/d+"%"),a[c].style.marginRight&&"%"!=
a[c].style.marginRight.slice(-1)&&(a[c].style.marginRight=100*parseFloat(a[c].style.marginRight)/d+"%"),a[c].style.marginTop&&"%"!=a[c].style.marginTop.slice(-1)&&(a[c].style.marginTop=100*parseFloat(a[c].style.marginTop)/d+"%"),a[c].style.marginBottom&&"%"!=a[c].style.marginBottom.slice(-1)&&(a[c].style.marginBottom=100*parseFloat(a[c].style.marginBottom)/d+"%"),a[c].style.paddingLeft&&"%"!=a[c].style.paddingLeft.slice(-1)&&(a[c].style.paddingLeft=100*parseFloat(a[c].style.paddingLeft)/d+"%"),a[c].style.paddingRight&&
"%"!=a[c].style.paddingRight.slice(-1)&&(a[c].style.paddingRight=100*parseFloat(a[c].style.paddingRight)/d+"%"),a[c].style.paddingTop&&"%"!=a[c].style.paddingTop.slice(-1)&&(a[c].style.paddingTop=100*parseFloat(a[c].style.paddingTop)/d+"%"),a[c].style.paddingBottom&&"%"!=a[c].style.paddingBottom.slice(-1)&&(a[c].style.paddingBottom=100*parseFloat(a[c].style.paddingBottom)/d+"%"),0<a[c].childElementCount&&ec(a[c])))}}}
function fc(a){if(a.hasChildNodes()){a=a.children;for(var c=a.length-1;0<=c;c--){var d=a[c].nodeName.toLowerCase();"br"!=d&&"option"!=d&&""!=d&&"table"!=d&&"tbody"!=d&&"tr"!=d&&"td"!=d&&(d=a[c].parentNode.nodeName.toLowerCase(),"br"!=d&&"option"!=d&&""!=d&&"table"!=d&&"tbody"!=d&&"tr"!=d&&"td"!=d&&("relative"!=a[c].style.position&&(a[c].style.position="absolute"),d=parseFloat(a[c].style.left),d!=a[c].offsetLeft&&(a[c].style.left=d+(d-a[c].offsetLeft)+"px"),d=parseFloat(a[c].style.width),d!=a[c].offsetWidth&&
(a[c].style.width=d+(d-a[c].offsetWidth)+"px"),d=parseFloat(a[c].style.top),d!=a[c].offsetTop&&(a[c].style.top=d+(d-a[c].offsetTop)+"px"),d=parseFloat(a[c].style.height),d!=a[c].offsetHeight&&(a[c].style.height=d+(d-a[c].offsetHeight)+"px"),0<a[c].childElementCount&&ec(a[c])))}}}function mb(a){a=parseFloat(a);if(isNaN(a)||!E[a])a=0;if(!(0<a&&"max"==E[a].Window.R)){for(var c in E[a].I);document.getElementById("UPTitle").innerHTML=0<a?"":"StewVed&apos;s Webtop"}}
function gc(a){document.getElementById("RCMcontainer")&&hc();var c=a.id.split("_"),d=parseFloat(c[0]);if(!isNaN(d)){-1==d&&(d=0);J.sc=a.id;if(J.Pb=d)document.getElementById(J.Pb+"gMenu").classList.add("gMenuOpen"),a.classList.add("gMenuItemsHover");var e="",f;for(f in E[d].I[c[2]].v)e=E[d].I[c[2]].v[f].g?e+('<div id="'+d+"_"+f+"_gMenu_"+c[2]+'" class="RCMenu '+t[u].eb+'">'+E[d].I[c[2]].v[f].Text+"</div>"):e+('<div class="RCMgrey">'+E[d].I[c[2]].v[f].Text+"</div>");ic(e);for(f in E[d].I[c[2]].v)E[d].I[c[2]].v[f].Event&&
(e=E[d].I[c[2]].v[f].Event,"mouseup"===e[1]?(document.getElementById(e[0]).addEventListener("mouseup",e[2]),document.getElementById(e[0]).addEventListener("touchend",e[2])):document.getElementById(e[0]).addEventListener(e[1],e[2])),E[d].I[c[2]].v[f].xc&&(e=E[d].I[c[2]].v[f].xc,"mouseup"===e[1]?(document.getElementById(e[0]).addEventListener("mouseup",e[2]),document.getElementById(e[0]).addEventListener("touchend",e[2])):document.getElementById(e[0]).addEventListener(e[1],e[2]));"none"==J.active&&
(J.active="gMenuSub");c=document.getElementById("RCMcontainer");d=0;for(f=a.offsetHeight;"Wallpaper"!=a.id;)d+=a.offsetLeft,f+=a.offsetTop,a=a.parentNode;c.style.left=d+"px";c.style.top=f-2+"px";c.style.borderRadius="0px 0px 6px 6px";c.style.borderTop="0px";7==F&&(E[7].Ab=!0)}}
function jc(a,c){if(a&&"gm"!==a.id.slice(0,2)){var d=parseFloat(a.id).toString();isNaN(d)&&(d=kc(a));if(isFinite(d)){if("top"===c){if(G[G.indexOf(d)]&&G.splice(G.indexOf(d),1),G.unshift(d),"full"==E[d].Window.R)return}else"add"===c?G.unshift(d):"del"===c&&G.splice(G.indexOf(d),1);G[0]&&0!=G[0]?(lc(document.getElementById(G[0])),mb(G[0])):(lc(document.getElementById("Wallpaper")),mb(0),document.getElementById("Tl").style.opacity=0,document.getElementById("Tl").style.top="0")}else lc(a),mb(0),document.getElementById("Tl").style.opacity=
0,document.getElementById("Tl").style.top="0"}}function mc(a){for(var c=1;E[parseFloat(a+"."+c)];)c++;return parseFloat(a+"."+c)}function kc(a){var c=NaN;if(a){for(;"Wallpaper"!=a.id&&isNaN(parseFloat(a.id));)a=a.parentNode;c=a}return parseFloat(c.id).toString()}
function T(a){var c=a.split("_");a=parseFloat(c[1]);if(0===a){a=document.createElement("div");a.id="lExpo";document.getElementById("Wallpaper").appendChild(a);var d=document.getElementById("Wallpaper").offsetHeight-32;a.innerHTML='<div id="lExTop" style="height:32px;"><div style="float:left;width:8px;height:1px;"></div><img id="lExpoClose" class="Button ButtonClo" style="margin-right:56px;background-image: url('+va.src+')" '+w+'><div id="expoTall" class="expoTabSeld">All</div><div id="expoTapp" class="expoTabs">Apps</div><div id="expoTgame" class="expoTabs">Games</div><div id="expoTsett" class="expoTabs">Settings</div><div id="expoThelp" class="expoTabs">Help</div></div><div id="lExlCov" style="top:32px;height:'+
d+"px;width:"+cb+'px;"></div><div id="lExList" class="letScroll" style="top:32px;left:'+cb+"px;height:"+d+"px;width:"+P+'px;"></div>';Q.sort(nc);oc("all");a.style.opacity=1}else{d=parseInt(a,10);var e=parseInt(c[1].split(".")[1],10);if(e){var f=E[d].Window.qa;d=E[d].Window.s}else{99!==a&&100!==a&&a!==d&&parseInt(c[2],10)&&(d=parseInt(c[2],10));for(var g in Q)if(Q[parseFloat(g)].s==d){f=g;break}}var h=[],m;for(g in E)E[parseFloat(g)].Window.s==d&&(h.push(parseFloat(g)),m||(e?E[a]&&(m=1):m=1));if(m&&
"newInstance"!=c[0]&&isNaN(parseInt(y.ca.id,10)))if("b"==c[2]||"f"==c[2]||"i"==c[2]||"t"==c[2])pc(c[3]);else{if("Lc"==c[2])for(g in h)pc(h[parseFloat(g)])}else{if(!e)for(a=1;E[a];)a++;E[a]=[];E[a].Window={qa:f,s:d,H:"blank",wb:!1,j:-1,F:-1,l:-1,$:-1,R:"nor",u:-1,A:-1,P:-1,O:-1,m:0,ra:0};E[a].a=[];h.push(a);e&&c[2]&&(E[a].Window.Kc=c[2]);100==E[a].Window.s&&(E[a].Window.Kc=c[0]);g=document.getElementById("Wallpaper");f=document.createElement("div");f.id=a;f.className="winWindow";g.appendChild(f);if("Ku"==
x){var p=Eb(a,1);p+='<div id="'+a+'bSpacer" style="float:right;width:8px;height:27px;"></div><img id="'+a+'CloseButton" class="Button" style="background-image: url('+va.src+');float:right;" '+w+'><img id="'+a+'MaxButton" class="Button" style="background-image: url('+va.src+');float:right;" '+w+'><img id="'+a+'MinButton" class="Button" style="background-image: url('+va.src+');float:right;" '+w+">"}else"Ub"==x&&(p=Eb(a,0)+'<div id="'+a+'bSpacer" style="float:left;width:8px;height:27px;"></div><img id="'+
a+'CloseButton" class="Button" style="background-image: url('+va.src+')" '+w+'><img id="'+a+'MinButton" class="Button" style="background-image: url('+va.src+')" '+w+'><img id="'+a+'MaxButton" class="Button" style="background-image: url('+va.src+')" '+w+">");f.innerHTML='<div id="'+a+'TopBar" class="windowTopBar">'+p+'<div id="'+a+'Title" class="winTitle"></div><div id="'+a+'gMenu" class="gMenu '+t[u].La+'"></div></div><div id="'+a+'Cont" class="winContainer"><div id="'+a+'Box" class="winBox"></div></div>';
"Ub"===x&&(document.getElementById(a+"appImg").style.width=0);document.getElementById(a+"TopBar").classList.add(t[u].La);"Ku"==x&&(document.getElementById(a+"TopBar").style.height=document.getElementById(a+"Title").offsetHeight+25+"px");""==document.getElementById(a+"Title").innerHTML&&(document.getElementById(a+"Title").innerHTML=Q[E[a].Window.qa].appName);f.style.left="128px";f.style.top="19px";qc(a);-1<R.indexOf(E[a].Window.s)?(za||rc(a,"ku"),document.getElementById("T_"+d).style.opacity=1,document.getElementById("D_"+
d).style.opacity=.5):rc(a,"all");1==h.length?document.getElementById("T_"+d).style.backgroundPosition="-131px -44px":2==h.length?document.getElementById("T_"+d).style.backgroundPosition="-145px -44px":2<h.length&&(document.getElementById("T_"+d).style.backgroundPosition="-157px -44px");jc(document.getElementById(a.toString()),"add")}}}
function qc(a){window[Q[E[a].Window.qa].T]?(window[Q[E[a].Window.qa].T](a),sc(a)):(document.getElementById("Loader"+a)||tc(a),window.setTimeout(function(){qc(a)},500))}
function tc(a){document.getElementById(a+"Box").innerHTML='<div id="Loader'+a+'" style="position:relative;color:#dfdbd2;z-index:5;text-align:center;width:100%;margin:auto;"><span id="Ling'+a+'" class="loadin">Loading...</span><div id="LP"></div>';document.getElementById("Loader"+a).style.top=document.getElementById(a+"Box").offsetHeight/2-document.getElementById("Loader"+a).offsetHeight/2+"px";uc(a)}
function sc(a){document.getElementById(a+"Cont").style.backgroundColor=document.getElementById(a+"Box").style.backgroundColor;document.getElementById(a+"Box").style.left="0";document.getElementById(a+"Box").style.top="0";uc(a);vc(a);var c=document.getElementById(a+"MinButton");100==a&&(c.style.width="0");"Ku"==x?(c=document.getElementById(a+"appImg").offsetLeft+document.getElementById(a+"appImg").offsetWidth,document.getElementById(a+"Title").style.left=(document.getElementById(a+"MinButton").offsetLeft-
c)/2-document.getElementById(a+"Title").offsetWidth/2+c+"px",document.getElementById(a+"gMenu").className="kMenu",document.getElementById(a+"gMenu").style.width="100%",document.getElementById(a+"gMenu").style.top=document.getElementById(a+"Title").offsetHeight+"px"):"Ub"==x&&(document.getElementById(a+"Title").style.left=document.getElementById(a+"MaxButton").offsetLeft+document.getElementById(a+"MaxButton").offsetWidth+"px",document.getElementById(a+"gMenu").style.left=document.getElementById(a+
"Title").style.left,document.getElementById(a+"gMenu").style.width=document.getElementById(a).offsetWidth-document.getElementById(a+"gMenu").offsetLeft+"px",document.getElementById(a+"gMenu").style.height=document.getElementById(a+"TopBar").offsetHeight+"px");E[a].I||(E[a].I=[{Text:"File",v:[{Text:"Exit",g:function(){wc(a)}}]}]);xc(a);Qb(a)}
function pc(a){"Deleted"!=E[a].Window.H&&("min-max"==E[a].Window.R?E[a].Window.R="max":"min-nor"==E[a].Window.R&&(E[a].Window.R="nor"),document.getElementById(a).hidden=!1,jc(document.getElementById(a),"top"),document.getElementById("b_"+a).style.opacity="1")}function xc(a){var c="",d;for(d in E[a].I)c+='<div id="'+a+"_gm_"+d,"Ku"==x?c+='" class="kMenuItems">':"Ub"==x&&(c+='" class="gMenuItems">'),c+=E[a].I[d].Text+"</div>";document.getElementById(a+"gMenu").innerHTML=c}
function Sb(){var a=Qa;if(isFinite(a)&&0<a){var c=document.getElementById(a),d=document.getElementById(a+"Cont"),e=document.getElementById(a+"Box");"max"==E[a].Window.bd?(c.style.top="-8px","Ku"==x?(c.style.left="-8px",d.style.width=document.getElementById("Wallpaper").offsetWidth+"px",d.style.height=document.getElementById("Wallpaper").offsetHeight-document.getElementById("UnityPanel").offsetHeight+"px"):"Ub"==x&&(c.style.left=cb-H+"px",d.style.width=P+"px",d.style.height=document.getElementById("Wallpaper").offsetHeight-
document.getElementById("UnityPanel").offsetHeight+"px"),jc(c,"top")):(c.style.left=E[a].Window.l+"px",c.style.top=E[a].Window.j+"px",d.style.width=d.style.height="",e.style.top=e.style.left="",e.style.width=E[a].Window.$+"px",e.style.height=E[a].Window.F+"px");"Ub"==x&&(document.getElementById(a+"gMenu").style.width=document.getElementById(a).offsetWidth-document.getElementById(a+"gMenu").offsetLeft+"px");E[a].Window.R=E[a].Window.bd;c.style.zIndex=G[a];d.style.top="";document.getElementById(a+"TopBar").style.opacity=
1;document.getElementById("UnityPanel").style.opacity=1}isFinite(a)&&0<a&&(Qb(Qa),Rb(Qa));Qa="full"==E[0].Window.R&&0<a?0:-1}
function U(a){var c=document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||document.msFullscreenElement?1:0;Qa=a;c?"full"==E[0].Window.R&&0<Qa?"full"==E[a].Window.R?Sb():ob():(eb.call(document,function(){}),document.getElementById(a+"FS")&&(document.getElementById(a+"FS").classList.remove("fsdButton"),document.getElementById(a+"FS").classList.add("fsButton"))):(fb.call(document.documentElement,function(){}),document.getElementById(a+"FS")&&(document.getElementById(a+
"FS").classList.remove("fsButton"),document.getElementById(a+"FS").classList.add("fsdButton")))}function uc(a){var c=document.getElementById("Wallpaper"),d=document.getElementById(a);d.style.left=cb-1+(c.offsetWidth-cb)/2-(d.offsetWidth-0)/2+"px";var e=document.getElementById("UnityPanel").offsetHeight,f=d.offsetHeight-2*H;if("Ub"==x)var g=e+(c.offsetHeight-e)/2-f/2;else"Ku"==x&&(g=c.offsetHeight/2-(f+e)/2,e=0);if(g<=e||99==a)g=e;g-=H;d.style.top=g+"px"}
function cc(a){var c=document.getElementById(a+"Cont"),d=document.getElementById(a+"Box"),e=c.offsetHeight;e/=E[a].Window.A;var f=Math.floor(E[a].Window.u*e);f>c.offsetWidth&&(e=c.offsetWidth/E[a].Window.u,f=Math.floor(E[a].Window.u*e));e=Math.floor(E[a].Window.A*e);a=Math.floor(c.offsetWidth-(f+(c.offsetWidth-f)/2));c=Math.floor(c.offsetHeight-(e+(c.offsetHeight-e)/2));1==c&&(c=0);1==a&&(a=0);d.style.left=a+"px";d.style.width=f+"px";d.style.top=c+"px";d.style.height=e+"px"}
function wc(a){var c=parseFloat(a),d=document.getElementById(c.toString());if(isFinite(c)&&d){var e=parseInt(a,10);if(c===e)for(var f in E)parseInt(f,10)===e&&f!=c&&wc(f);"closing"!=E[a].Window.H&&("none"!=J.active&&hc(),d.style.transition="opacity 0.4s",d.style.opacity=0,E[a].Window.H="closing",window.setTimeout(function(){var c=parseInt(E[a].Window.s,10),e=0,f;for(f in E)E[parseFloat(f)].Window.s==c&&e++;1==e?(document.getElementById("T_"+c).style.opacity=0,document.getElementById("T_"+c).style.backgroundPosition=
"-131px -44px",document.getElementById("D_"+c).style.opacity=0,S[c].locked||yc(c)):1<e&&(2==e?document.getElementById("T_"+c).style.backgroundPosition="-131px -44px":3==e?document.getElementById("T_"+c).style.backgroundPosition="-145px -44px":3<e&&(document.getElementById("T_"+c).style.backgroundPosition="-157px -44px"));document.getElementById("b_"+a)&&(document.getElementById("kTaskBar").removeChild(document.getElementById("b_"+a)),Ub("close"));d.parentNode.removeChild(d);E[a].a.$b&&window.clearInterval(E[a].a.$b);
delete E[a];jc(d,"del")},420))}}
function zc(a){var c=document.getElementById(a),d=document.getElementById(a+"Cont"),e=document.getElementById(a+"Box");c&&!isNaN(parseInt(a,10))&&("max"==E[a].Window.R?(c.style.left=E[a].Window.l+"px",c.style.top=E[a].Window.j+"px",d.style.width=d.style.height="",e.style.top=e.style.left="",e.style.width=E[a].Window.$+"px",e.style.height=E[a].Window.F+"px",E[a].Window.R="nor"):(c.style.top="-8px",E[a].Window.R="max",Ac(a),e.style.width=d.style.width,e.style.height=d.style.height),Qb(a),"max"==E[a].Window.R&&
Ac(a),"Ub"==x&&(document.getElementById(a+"gMenu").style.width=document.getElementById(a).offsetWidth-document.getElementById(a+"gMenu").offsetLeft+"px"),jc(c,"top"))}
function Ac(a){var c=document.getElementById(a);a=document.getElementById(a+"Cont");"Ku"==x?(c.style.left=-H+"px",a.style.width=document.getElementById("Wallpaper").offsetWidth+"px",a.style.height=document.getElementById("Wallpaper").offsetHeight-document.getElementById("UnityPanel").offsetHeight+"px"):"Ub"==x&&(c.style.left=cb-H+"px",a.style.width=P+"px",a.style.height=document.getElementById("Wallpaper").offsetHeight-document.getElementById("UnityPanel").offsetHeight+"px")}
function ic(a){var c=document.createElement("div");c.id="RCMcontainer";c.innerHTML=a;document.getElementById("Wallpaper").appendChild(c);c.classList.add(t[u].fb)}
function hc(){J.active="none";M.style.opacity=N.style.opacity=0;J.Pb&&document.getElementById(J.Pb+"gMenu").classList.remove("gMenuOpen");J.sc&&document.getElementById(J.sc).classList.remove("gMenuItemsHover");document.getElementById("RCMcontainer")&&document.getElementById("RCMcontainer").parentNode.removeChild(document.getElementById("RCMcontainer"));"full"!=E[parseFloat(F)].Window.R&&lc(document.getElementById(F.toString()));J={active:"none",sc:"",Pb:"",ad:""}}
function Bc(a){if("System"==a)return Gb;if("Time"==a)return Cc;if("Volume"==a)return Dc;if("Messages"==a)return gb}
function Ec(a){document.getElementById("RCMcontainer")&&hc();J.active="indicator";var c="",d=Bc(a.id),e;for(e in d)c=d[e].g?c+('<div id="'+a.id+"_"+e+'_iMenu" class="RCMenu '+t[u].eb+'">'+d[e].Text+"</div>"):c+('<div class="RCMgrey">'+d[e].Text+"</div>");if(0!=c.length){ic(c);c=document.getElementById("RCMcontainer");for(e=d=0;"Wallpaper"!=a.id;)d+=a.offsetLeft,e+=a.offsetTop,a=a.parentNode;c.offsetWidth+d>document.getElementById("Wallpaper").offsetWidth&&(d=document.getElementById("Wallpaper").offsetWidth-
c.offsetWidth);"Ub"==x?(e+=document.getElementById("UnityPanel").offsetHeight,c.offsetHeight+e>document.getElementById("Wallpaper").offsetHeight&&(e=document.getElementById("Wallpaper").offsetHeight-c.offsetHeight)):"Ku"==x&&c.offsetHeight+e>document.getElementById("Wallpaper").offsetHeight-document.getElementById("UnityPanel").offsetHeight&&(e=document.getElementById("Wallpaper").offsetHeight-document.getElementById("UnityPanel").offsetHeight-c.offsetHeight);c.style.top=e+"px";c.style.left=d+"px"}}
function Fc(a,c){a=parseFloat(a.id).toString();if(!isNaN(a)){var d=E[parseFloat(a)].Window.wb?"&#10004;&nbsp;":"&nbsp;&nbsp;";J.active="title";var e="";0<document.getElementById(a+"MinButton").offsetWidth&&(e+='<div id="'+a+'MinButtonE" class="RCMenu '+t[u].eb+'">>&nbsp;&nbsp;Minimise</div>');0<document.getElementById(a+"MaxButton").offsetWidth&&(e+='<div id="'+a+'MaxButtonE" class="RCMenu '+t[u].eb+'">>&nbsp;&nbsp;Maximise</div>');0<e.length&&(e+="<hr>");e+='<div id="'+a+'AOE" class="RCMenu '+t[u].eb+
'">>'+(d+"Always On Top")+"</div>";99!=parseInt(a,10)&&(e+='<hr><div id="'+a+'CloseButtonE" class="RCMenu '+t[u].eb+'">>&nbsp;&nbsp;Close</div>');ic(e);d=document.getElementById("RCMcontainer");d.style.left=c.clientX+"px";d.style.top=c.clientY+"px";J.ad=a;7==F&&(E[7].Ab=!0)}}
function Gc(a,c){document.getElementById("RCMcontainer")&&hc();var d="",e=a.id;"Wallpaper"==e&&(e=0);for(var f in E[e].va)d=E[e].va[f].g?d+('<div id="'+e+"_"+f+'_rMenu" class="RCMenu '+t[u].eb+'">'+E[e].va[f].Text+"</div>"):d+('<div id="'+e+"_"+f+'_rMenu" class="RCMgrey">'+E[e].va[f].Text+"</div>");0!=d.length&&(ic(d),J.active="right",d=document.getElementById("RCMcontainer"),d.style.borderRadius="6px",d.style.borderTop="",e=c.clientX,f=c.clientY,e+d.offsetWidth>window.innerWidth&&(e=c.clientX-d.offsetWidth),
f+d.offsetHeight>window.innerHeight&&(f=c.clientY-d.offsetHeight),d.style.left=e+"px",d.style.top=f+"px",J.ad=a,7==F&&(E[7].Ab=!0))}
function lc(a){var c=NaN;a&&(c=parseFloat(a.id).toString());for(var d in E)"Deleted"!=E[parseFloat(d)].Window.H&&"Desktop"!=E[parseFloat(d)].Window.H&&d!=c&&(E[parseFloat(d)].Window.wb?document.getElementById(d).style.zIndex=G.length+3:document.getElementById(d).style.zIndex=G.length+1-G.indexOf(d),document.getElementById(d+"CloseButton").className="Button ButtonCloU",document.getElementById(d+"MinButton").className="Button ButtonMinU",document.getElementById(d+"MaxButton").className="Button ButtonMaxU",
document.getElementById("f_"+d).classList.add("kTaskU"),document.getElementById(d+"gMenu").classList.remove("gMenuF"),document.getElementById(d+"Title").classList.remove("winTitleF"));isFinite(c)&&0<c?("full"!=E[parseFloat(c)].Window.R&&(document.getElementById(c.toString()).style.zIndex=G.length+1),document.getElementById("Tl").style.top=document.getElementById("C_"+parseInt(E[parseFloat(c)].Window.s,10)).offsetTop+10+"px",document.getElementById("Tl").style.opacity=1,document.getElementById(c+"CloseButton").className=
"Button ButtonClo",document.getElementById(c+"MinButton").className="Button ButtonMin",document.getElementById(c+"MaxButton").className="Button ButtonMax",document.getElementById("f_"+c).classList.remove("kTaskU"),document.getElementById("f_"+c).classList.remove("kTaskH"),document.getElementById("f_"+c).classList.add("kTaskF"),document.getElementById(c+"gMenu").classList.add("gMenuF"),document.getElementById(c+"Title").classList.add("winTitleF"),F=c):(z.w="",F=0,document.getElementById("Tl").style.opacity=
0,document.getElementById("Tl").style.top="0");if("Ub"==x){for(d=G.length-1;-1<d;d--)if("max"==E[G[d]].Window.R){document.getElementById("gMxTitle").innerHTML=document.getElementById(G[d]+"TopBar").innerHTML;break}-1==d&&(document.getElementById("gMxTitle").innerHTML="")}}
function Hc(a){document.getElementById(a+"Box").style.width=Math.round(.8*P)+"px";E[a].Window.u=document.getElementById(a+"Cont").offsetWidth;document.getElementById(a+"Box").style.height=Math.round(.5625*document.getElementById(a+"Cont").offsetWidth)+"px";E[a].Window.A=document.getElementById(a+"Cont").offsetHeight;E[a].Window.P=Math.floor(document.getElementById(a+"Cont").offsetWidth/3);E[a].Window.O=Math.floor(document.getElementById(a+"Cont").offsetHeight/3)}
function vc(a){E[a].Window.l=document.getElementById(a).offsetLeft;E[a].Window.j=document.getElementById(a).offsetTop;E[a].Window.$=document.getElementById(a+"Cont").offsetWidth;E[a].Window.F=document.getElementById(a+"Cont").offsetHeight};window.dChoose=function(a){a=parseFloat(a);var c=document.body;isFinite(a)?(c=document.getElementById(a+"Box"),c.style.width=.8*P+"px"):a=0;var d=a+"deChooser";c.style.background="radial-gradient(rgb(64, 71, 96), rgb(32, 39, 64))";c.innerHTML+='<div id="'+d+'" style="position:relative;margin:0% 2%;color:#dfdbd2;overflow:hidden;"><p style="padding:0;text-align:center;margin:0;font-size:3em;">Choose&nbsp;your&nbsp;Webtop:</p><p id="b" style="padding:0;text-align:center;margin:0px 0px 8px 0px;"><img id="'+
a+'Ku" class="DEchooseButton" style="float:left;width:47%;" src="images/kub.png"><img id="'+a+'Ub" class="DEchooseButton" style="float:right;width:47%;" src="images/ubu.png"><br style="clear:both;"><br></div>';document.getElementById(a+"Ku").style.height=document.getElementById(a+"Ub").style.height=.5625*document.getElementById(a+"Ku").offsetWidth+"px";a?(document.getElementById(a+x).style.backgroundColor="#eee",c.style.height=c.offsetHeight+"px",c.style.background="#234",d=E[a].Window,d.u=c.offsetWidth,
d.A=c.offsetHeight,d.P=Math.floor(c.offsetWidth/3),d.O=Math.floor(c.offsetHeight/3),d.H="dChooser",d.m=1,d.ra=1,ec(document.getElementById(a+"Box")),fc(document.getElementById(a+"Box"))):document.getElementById(d).style.top=c.offsetHeight/2-document.getElementById(d).offsetHeight/2+"px";document.getElementById(a+"Ku").addEventListener("mouseup",function(){Ic(a,"Ku")},!1);document.getElementById(a+"Ku").addEventListener("touchend",function(){Ic(a,"Ku")},!1);document.getElementById(a+"Ub").addEventListener("mouseup",
function(){Ic(a,"Ub")},!1);document.getElementById(a+"Ub").addEventListener("touchend",function(){Ic(a,"Ub")},!1)};function Ic(a,c){x!==c&&(x=c.slice(-2),Jc("webtopStyle",x),Fb(a))}
function Fb(a){if(a){if(document.getElementById(a+"deChooser")){for(var c=document.getElementById(a+"deChooser").getElementsByTagName("img"),d=0;d<c.length;d++)c[d].style.backgroundColor="";document.getElementById(a+x).style.backgroundColor="#eee"}document.getElementById("uLauncher").style.transition="top 1s, left 1s";document.getElementById("UnityPanel").style.transition="top 1s, height 1s";document.getElementById("cpy").style.transition="top 1s";"Ku"==x?(document.getElementById("uLauncher").style.left=
"-64px",document.getElementById("uLauncher").style.border=0,34!=document.getElementById("uLauncher").offsetTop&&(document.getElementById("uLauncher").style.top=document.getElementById("uLauncher").offsetTop+10+"px"),document.getElementById("UPTitle").style.opacity=0,document.getElementById("kTaskBar").style.opacity=1,document.getElementById("kTaskBar").style.zIndex=12,document.getElementById("indicatorPanel").style.marginTop="4px",document.getElementById("Time").style.lineHeight=document.getElementById("UnityPanel").style.height=
"34px",document.getElementById("gMxTitle").style.width=document.getElementById("gMxTitle").style.height=0,document.getElementById("kTaskBar").style.width=document.getElementById("indicatorPanel").offsetLeft+"px",document.getElementById("UnityPanel").style.top=document.getElementById("Wallpaper").offsetHeight-34+"px",document.getElementById("cpy").style.top=document.getElementById("Wallpaper").offsetHeight-document.getElementById("cpy").offsetHeight-34-2+"px",Kc(-24,"Ku")):"Ub"==x&&(document.getElementById("Time").style.lineHeight=
document.getElementById("UnityPanel").style.height=document.getElementById("gMxTitle").style.height="24px",document.getElementById("UnityPanel").style.top="0",document.getElementById("uLauncher").style.left="0",document.getElementById("uLauncher").style.border="border-right:1px solid rgba(255,255,255,0.5)",24!=document.getElementById("uLauncher").offsetTop&&(document.getElementById("uLauncher").style.top=document.getElementById("uLauncher").offsetTop+-10+"px"),document.getElementById("UPTitle").style.opacity=
1,document.getElementById("kTaskBar").style.opacity=0,document.getElementById("kTaskBar").style.width="0",document.getElementById("kTaskBar").style.zIndex=11,document.getElementById("indicatorPanel").style.marginTop="",document.getElementById("gMxTitle").style.width=document.getElementById("indicatorPanel").offsetLeft+"px",document.getElementById("cpy").style.top=document.getElementById("Wallpaper").offsetHeight-document.getElementById("cpy").offsetHeight-2+"px",Kc(24,"Ub"));xa();window.clearTimeout(Aa);
Aa=window.setTimeout(function(){document.getElementById("uLauncher").style.transition="";document.getElementById("UnityPanel").style.transition="";document.getElementById("cpy").style.transition="";for(var a=document.getElementsByClassName("winWindow"),c=0;c<a.length;c++){a[c].style.transition="";var d=a[c].id;document.getElementById(d+"CloseButton").style.position=document.getElementById(d+"CloseButton").style.transition="";document.getElementById(d+"MinButton").style.position=document.getElementById(d+
"MinButton").style.transition="";document.getElementById(d+"MaxButton").style.position=document.getElementById(d+"MaxButton").style.transition="";document.getElementById(d+"Title").style.transition="";"Ub"===x&&(document.getElementById(d+"appImg").style.width=0)}P=document.getElementById("Wallpaper").offsetWidth-(document.getElementById("uLauncher").offsetWidth+1+document.getElementById("uLauncher").offsetLeft);cb=document.getElementById("uLauncher").offsetWidth+1+document.getElementById("uLauncher").offsetLeft},
1E3)}}
function Kc(a,c){for(var d=document.getElementsByClassName("winWindow"),e=0;e<d.length;e++){d[e].style.transition="";d[e].style.transition="top 1s";d[e].style.top=d[e].offsetTop+a+"px";var f=d[e].id;E[parseFloat(f)].Window.j+=a;document.getElementById(f+"MaxButton").style.transition=document.getElementById(f+"MinButton").style.transition=document.getElementById(f+"CloseButton").style.transition="left 1s";document.getElementById(f+"Title").style.transition="1s";var g=f,h=c,m=document.getElementById(g+"CloseButton"),
p=document.getElementById(g+"MinButton"),r=document.getElementById(g+"MaxButton"),k=document.getElementById(g+"bSpacer");m.style.left=m.offsetLeft+"px";p.style.left=p.offsetLeft+"px";r.style.left=r.offsetLeft+"px";"Ub"===h?(k.style.cssFloat=m.style.cssFloat=p.style.cssFloat=r.style.cssFloat="left",r.parentNode.removeChild(p),r.parentNode.insertBefore(p,r)):(k.style.cssFloat=m.style.cssFloat=p.style.cssFloat=r.style.cssFloat="right",p.parentNode.removeChild(r),p.parentNode.insertBefore(r,p),document.getElementById(g+
"appImg").style.width="");var v=m.offsetLeft;k=p.offsetLeft;var I=r.offsetLeft;m.style.position=p.style.position=r.style.position="absolute";m.style.left=v+"px";p.style.left=k+"px";r.style.left=I+"px";m=document.getElementById(g+"Title");"Ub"===h?document.getElementById(g+"gMenu").style.left=m.style.left=I+r.offsetWidth+"px":(g=document.getElementById(g+"appImg").offsetLeft+document.getElementById(g+"appImg").offsetWidth,m.style.left=(k-g)/2-m.offsetWidth/2+g+"px");g=document.getElementById(f+"gMenu");
g.style.transition="height 1s";"Ub"===c?(document.getElementById(f+"appImg").style.opacity=0,document.getElementById(f+"TopBar").style.height=document.getElementById(f+"Title").offsetHeight+"px",g.style.top="0",g.classList.remove("kMenu"),g.classList.add("gMenu"),g.style.width=d[e].offsetWidth-g.offsetLeft+"px"):(document.getElementById(f+"appImg").style.opacity=1,document.getElementById(f+"TopBar").style.height=document.getElementById(f+"Title").offsetHeight+25+"px",g.style.top=document.getElementById(f+
"Title").offsetHeight+"px",g.style.left="0",g.classList.remove("gMenu"),g.classList.add("kMenu"),g.style.width="")}};function pb(a){a.cancelable?(a.preventDefault(),a.stopPropagation()):(wb({bubbles:!0,button:0,cancelBubble:!1,cancelable:!0,clientX:0,clientY:0,currentTarget:"none",defaultPrevented:!1,returnValue:!0,target:document.getElementById("Wallpaper"),which:1,x:0,y:0}),B=[])}
function Lc(a,c,d){var e=a;0==a&&(e="lExList");if(!(isNaN(a)||!document.getElementById(e)||y.type&&F==a)){var f=(new Date).getTime();d=(f-d)/1E3;var g=c;e=-(c*d);0<d&&0!=c&&.25>e&&-.25<e?(y.type="",window.clearTimeout(y.Ua)):(0<a?document.getElementById(a+"Box").scrollTop+=e:document.getElementById("lExList")&&(document.getElementById("lExList").scrollTop+=e),d&&(g+=0>g?2.5*e:3.2*e,0<c&&0>g||0>c&&0<g)&&(g=0),g?E[a].Window.Vc=window.requestAnimationFrame(function(){Lc(a,g,f)}):y.hb=0)}}
function zb(){Mc()}function Ab(){Mc()}function Mc(){for(var a=navigator.getGamepads(),c=0;c<a.length;c++)a[c]&&(A[c]=[],A[c].buttons=a[c].buttons.slice(0),A[c].axes=a[c].axes.slice(0))}function xb(a){var c=a.keyCode||window.event.keyCode;122==c&&(pb(a),U(F));0!=c&&18!=c&&17!=c&&16!=c&&91!=c&&Ga.push(c)}
function yb(a){var c=a.keyCode||window.event.keyCode;for(122==c&&pb(a);-1!=Ga.indexOf(c);)Ga.splice(Ga.indexOf(c),1);c=Nc(a).id.split("_");if("tg"===c[0]){if("min"===c[3]||"now"===c[3]||"max"===c[3]){a=c[1];c=c[2];var d=parseFloat(document.getElementById("tg_"+a+"_"+c+"_now").value);isNaN(d)||(E[a].a.Na[c].frequency.value=d,Oc(a,c,d))}}else"svl"===c[0]&&Pc(c[1])}
function Nc(a){a||(a=window.event);if(a.target)var c=a.target;else a.srcElement&&(c=a.srcElement);1!=c.nodeType&&(c=c.parentNode);c||(c=document.getElementById("Wallpaper"));return c}function Bb(){y={button:0,type:"",Ua:0,ub:NaN,ca:NaN,startTime:0,hb:0,Ya:0,Za:8,Ba:0,Ca:0};z={w:"",J:"",ma:""};document.getElementById("Wallpaper").style.cursor="default"}function Qc(){Ia=0}
function ub(a){var c=Nc(a);"none"!=J.active&&"gMenuSub"!=J.active&&(J.active="deleteMenu");window.clearTimeout(y.Ua);y.button=null==a.which?a.button:a.which;y.type="click";y.ub=c;y.ca=c;y.startTime=new Date;y.Ba=a.clientX;y.Ca=a.clientY;y.Ya=a.clientX;y.Za=a.clientY;var d=c;d.classList.contains("PanelIcons")&&Ec(c);var e=kc(c);c=0<e?document.getElementById(e):document.getElementById("Wallpaper");isFinite(parseFloat(c.id))&&(z.w=c.id);if(d.classList.contains("editEnable")||d.classList.contains("uButtons")||
"TPFG"==d.className||"object"==d.nodeName.toLowerCase())jc(c,"top");else if(pb(a),d.classList.contains("LauncherIconCover"))Rc(a,d.id);else{if(1==y.button){if(Ia){if(d.classList.contains("gMenu")||d.classList.contains("winTitle")||d.classList.contains("windowTopBar")){if(e=parseFloat(c.id).toString(),0<document.getElementById(e+"MaxButton").offsetWidth){zc(F);Ia=0;return}}else if("screen_img"==d.className||"bb_gameArea"==d.className){U(F);Ia=0;return}Ia=0}else Ia=1,window.setTimeout(Qc,200);if(Ha){z.w=
Ha;z.J="Resizing";"none"!=J.active&&hc();z.ma=document.getElementById("Wallpaper").style.cursor;Sc();jc(document.getElementById(Ha),"top");return}Tc(e,a,d);y.Ua=window.setTimeout(function(){Uc(a,c,d)},500)}3==y.button&&"none"==J.active?d.classList.contains("winTitle")||d.classList.contains("gMenu")||d.classList.contains("windowTopBar")?Fc(c,a):d.classList.contains("LauncherIconCover")?Rc(a,d.id):Gc(c,a):!(""==d.id&&d.classList.contains("windowTopBar")||d.classList.contains("Button"))&&(jc(c,"top"),
d.classList.contains("windowTopBar")&&d.parentNode||(d.classList.contains("gMenu")&&"gMenu"!=d.id||d.classList.contains("winTitle"))&&d.parentNode.parentNode)&&(isNaN(z.w)&&l("origTarg is a window title, but Mdown.ID is NaN!<br>"),z.J="preMoving")}}
function Tc(a,c,d){var e=d.id.split("-");"toolTipclass"==d.id&&(Na=!0,Vc(a,d.id),Wc(d.id,1));if("uLauncher"==d.id)Rc(c,-1);else if("gMenuItems"==d.className||"kMenuItems"==d.className)gc(d);else if("screen_img"==d.className){var f=parseFloat(d.id);1==(null==c.which?c.button:c.which)&&(E[f].a.Kb=c.clientX-E[f].a.left,E[f].a.lc=c.clientY-E[f].a.top,E[f].a.wd=!0,z.w=f,z.J="sDrg")}else if("TTnums"==d.className||"TTbutton"==d.className){if(Ea?f=document.getElementById(Ea):f=Nc(c),a=f.id.split("_"),d=a[0],
1==E[d].a.ended&&(document.getElementById(d+"_lHs").innerHTML="Hours",document.getElementById(d+"_lMs").innerHTML="Minutes",document.getElementById(d+"_lSs").innerHTML="Seconds",E[d].a.la=E[d].a.startTime,Xc(d),E[d].a.ended=!1),"SrtStp"==a[1]&&(0==E[d].a.Zb?(document.getElementById(f.id).style.backgroundColor="#0F0",document.getElementById(f.id).innerHTML="&#8572;&#8572;",E[d].a.Zb=!0,E[d].a.Fc||(E[d].a.startTime=E[d].a.la,E[d].a.Fc=!0)):(document.getElementById(f.id).style.backgroundColor="#4AF",
document.getElementById(f.id).innerHTML="&#9654;",E[d].a.Zb=!1)),"Hs"==a[1]||"Ms"==a[1]||"Ss"==a[1])E[d].a.ea[1]=c.clientY,Ea=E[d].a.ea[0]=f.id,Sc()}else if("wordSearch_grid"==d.className)Yc(d.id,c);else if("wordSearch_ctr"==d.className)Yc(d.parentNode.id,c);else if("_BPgameArea"==d.id.slice(-11)){if(f=parseFloat(d.id),c=Nc(c),"winWindow"==c.className||"bb_gameArea"==c.className)if(""==document.getElementById(f).style.cursor||"default"==document.getElementById(f).style.cursor)0==E[f].a.f.speed&&(E[f].a.ec=
1,E[f].a.f.Sa=E[f].a.f.speed=Zc[E[f].a.Jc]+E[f].a.ec,E[f].a.f.top=E[f].a.Y.top-E[f].a.f.height-1,E[f].a.Ab=!0),E[f].a.Ab=!E[f].a.Ab}else"wallSlider"===d.id.slice(0,10)?(f=kc(d),d=d.id.slice(11),pb(c),$c=d,y.ca=document.getElementById("wallSliderb"+d),y.ca.style.transition="",Nb(""),ad(),M.style.background="linear-gradient(315deg, rgba(0,0,0,1) 36%, rgba(0,0,0,0) 40%)",bd(f,c),document.getElementById(f+"Box").style.backgroundColor="transparent",document.getElementById(f+"Cont").style.backgroundColor=
"rgba(255,255,255,0.2)"):"tg"===e[0]&&"slider"===e[3]?(f=d.id.split("-"),"I"===f[4]||"Iv"===f[4]?(z.J="sgDrag",Sc()):"C"===f[4].slice(0,1)&&(y.ca=document.getElementById("Cv"===f[4]?f[0]+"-"+f[1]+"-"+f[2]+"-"+f[3]+"-Iv":f[0]+"-"+f[1]+"-"+f[2]+"-"+f[3]+"-I"),z.J="sgDrag",cd(c),Sc())):"svl"===e[0]&&"slider"===e[2]?(f=d.id.split("-"),"I"===f[3]||"Iv"===f[3]?z.J="svlDrag":"C"===f[3].slice(0,1)&&(y.ca=document.getElementById("Cv"===f[3]?f[0]+"-"+f[1]+"-"+f[2]+"-Iv":f[0]+"-"+f[1]+"-"+f[2]+"-I"),z.J="svlDrag",
dd(c))):isFinite(parseFloat(y.ub.id))&&"tATimer"==E[parseFloat(y.ub.id)].Window.H&&(f=parseFloat(d.id),E[f].a.xa=-2,ed(f),d=Nc(c),a=d.id.split("~"),f=a[0],isFinite(parseInt(a[1],10))&&(E[f].a.ea[1]=c.clientY,Fa=E[f].a.ea[0]=d.id,Sc()))}
function Uc(a,c,d){"none"==J.active&&d&&(d.classList.contains("winTitle")||d.classList.contains("gMenu")||d.classList.contains("windowTopBar")?Fc(c,a):d.classList.contains("LauncherIconCover")?fd(c.split("_")[1]):y.ca.classList.contains("toolTipclass")||y.ca.parentNode.classList.contains("toolTipclass")?gd(a):d.classList.contains("gMenuItems")||Gc(c,a))}
function vb(a){if(!Da){Da=!0;window.requestAnimationFrame(function(){Da=!1});var c,d;if(d=c=Nc(a)){y.ub!=c&&("click"===y.type&&(y.type="",window.clearTimeout(y.Ua)),hd(c),id());jd(c);var e=y.Za;y.ub=c;y.Ya=a.clientX;y.Za=a.clientY;kd&&ld(a);if(!c)l("targ is null (line 581");else if(!c.classList.contains("editEnable")&&!c.classList.contains("uButtons")&&"TPFG"!=c.className&&"object"!=c.nodeName.toLowerCase()){pb(a);if("click"===y.type){if(y.Ba+10<a.clientX||y.Ba-10>a.clientX||y.Ca+10<a.clientY||y.Ca-
10>a.clientY)y.type="",window.clearTimeout(y.Ua),"preMoving"==z.J&&document.getElementById(F.toString())&&"RCMcontainer"!=c.parentNode.id&&"RCMcontainer"!=c.parentNode.parentNode.id&&"RCMcontainer"!=c.parentNode.parentNode.parentNode.id&&(document.getElementById("RCMcontainer")&&hc(),isNaN(z.w)&&l("trying to move a window without an  ID?!?!? 597"),Ba=a.clientY-document.getElementById(F.toString()).offsetTop,Ca=a.clientX-document.getElementById(F.toString()).offsetLeft,document.getElementById(F+"gMenu").style.width=
0,z.J="Moving",z.ma="move",document.getElementById("Wallpaper").style.cursor="move",Sc())}else if(1==y.button)if("scrolling"==y.type){if(!document.getElementById("lExList")&&!c.classList.contains("letScroll")){y.type="";return}document.getElementById(y.hb).scrollTop+=e-a.clientY}else""==y.type&&(y.Ca+10<a.clientY||y.Ca-10>a.clientY)&&(document.getElementById("lExList")||c.classList.contains("letScroll"))&&(y.type="scrolling",y.startTime=new Date,document.getElementById("lExList")?y.hb="lExList":y.hb=
F+"Box");if(c.classList.contains("editEnable")||"TPFG"==c.className)Na&&!c.classList.contains("ttElem")&&(Na=!1,md());else if(Fa)nd(a);else if(Ea)od(a,z.w);else if($c)bd(F,a);else if("sDrg"==z.J)pd(z.w,a);else if("sgDrag"==z.J)cd(a);else if("svlDrag"==z.J)dd(a);else if(qd(a,c),"Moving"==z.J)isNaN(z.w)&&l("moving a window without an  ID?!?!? 686"),c=document.getElementById(z.w),document.getElementById("RCMcontainer")&&(hc(),l("should never see!!!<br>menuDelete called from inside if Mdown.Action == moving)")),
d=a.clientX-Ca,a=a.clientY-Ba,"Ub"==x&&a<document.getElementById("UnityPanel").offsetHeight?a=document.getElementById("UnityPanel").offsetHeight-H:a<-H?a=-H:a+c.offsetHeight>document.getElementById("Wallpaper").offsetHeight&&a+c.offsetHeight<document.getElementById("Wallpaper").offsetHeight+16&&(a=document.getElementById("Wallpaper").offsetHeight-c.offsetHeight+H),0>d&&d>-(2*H)?d=-H:d+c.offsetWidth>document.getElementById("Wallpaper").offsetWidth&&d+c.offsetWidth<document.getElementById("Wallpaper").offsetWidth+
16&&(d=document.getElementById("Wallpaper").offsetWidth-c.offsetWidth+H),c.style.top=a+"px",c.style.left=d+"px";else if("launcerMD"==z.J)rd(a);else if(""==z.w||"vid"==z.J.slice(0,3)?!c.className||"Wallpaper"==c.className||c.classList.contains("winTitle")||c.classList.contains("windowTopBar")||c.classList.contains("gMenu")||c.classList.contains("RCMenu")||(c=kc(c),c=0<c?document.getElementById(c):document.getElementById("Wallpaper")):d=c=document.getElementById(z.w),"Resizing"==z.J){if("auto"!=z.ma&&
""!=z.w){c=document.getElementById(z.w+"Box");if("n-resize"==z.ma|"ne-resize"==z.ma|"nw-resize"==z.ma)if(e=0,"Ub"==x&&(e=document.getElementById("UnityPanel").offsetHeight),a.clientY>e)if(e=parseInt(c.style.height.slice(0,-2),10)+(parseInt(d.style.top.slice(0,-2),10)-(a.clientY-H)),E[z.w].Window.O<e)c.style.height=e+"px",d.style.top=a.clientY-H+"px";else{e=parseInt(c.style.height.slice(0,-2),10);c.style.height=E[z.w].Window.O+"px";var f=parseInt(c.style.height.slice(0,-2),10);d.style.top=parseInt(d.style.top.slice(0,
-2),10)+(e-f)+"px"}else c.offsetTop>e&&(c.style.height=parseInt(c.style.height.slice(0,-2),10)+(parseInt(d.style.top.slice(0,-2),10)-(e-H))+"px",d.style.top=e-H+"px");if("s-resize"==z.ma||"se-resize"==z.ma||"sw-resize"==z.ma)e=parseInt(d.style.top.slice(0,-2),10)+H,f=parseInt(document.getElementById(z.w+"TopBar").offsetHeight,10),e=a.clientY-f-e,c.style.height=E[z.w].Window.O<e?e+"px":E[z.w].Window.O+"px";if("w-resize"==z.ma||"nw-resize"==z.ma||"sw-resize"==z.ma)e=parseInt(c.style.width.slice(0,-2),
10)+(parseInt(d.style.left.slice(0,-2),10)-(a.clientX-H)),E[z.w].Window.P<e?(c.style.width=e+"px",d.style.left=a.clientX-H+"px"):(e=parseInt(c.style.width.slice(0,-2),10),c.style.width=E[z.w].Window.P+"px",f=parseInt(c.style.width.slice(0,-2),10),d.style.left=parseInt(d.style.left.slice(0,-2),10)+(e-f)+"px");if("e-resize"==z.ma||"ne-resize"==z.ma||"se-resize"==z.ma)e=a.clientX-(parseInt(d.style.left.slice(0,-2),10)+H),c.style.width=E[z.w].Window.P<e?e+"px":E[z.w].Window.P+"px";document.getElementById(z.w+
"gMenu").style.width=0;Rb(z.w);document.getElementById(z.w+"gMenu").style.width=c.offsetWidth-document.getElementById(z.w+"gMenu").offsetLeft+"px";"Ku"===x&&(e=document.getElementById(z.w+"appImg").offsetLeft+document.getElementById(z.w+"appImg").offsetWidth,document.getElementById(z.w+"Title").style.left=(document.getElementById(z.w+"MinButton").offsetLeft-e)/2-document.getElementById(z.w+"Title").offsetWidth/2+e+"px")}}else if(d.id==parseFloat(d.id)){e=c="";f=E[d.id].Window.l+E[d.id].Window.$+H;
var g=E[d.id].Window.j+E[d.id].Window.F+H+document.getElementById(d.id+"TopBar").offsetHeight;a.clientX>=E[d.id].Window.l&&a.clientX<=E[d.id].Window.l+H?c="w":a.clientX>=f&&a.clientX<=f+H&&(c="e");a.clientY>=E[d.id].Window.j&&a.clientY<=E[d.id].Window.j+H?e="n":a.clientY>=g&&a.clientY<=g+H&&(e="s");if(e||c)document.getElementById("Wallpaper").style.cursor=e+c+"-resize",Ha=d.id}else"default"!=document.getElementById("Wallpaper").style.cursor&&(document.getElementById("Wallpaper").style.cursor="default"),
Ha&&(Ha=!1),sd()}}else l("targ is null (line 559")}}function hd(a){document.getElementById("RCMcontainer")&&"right"!=J.active&&"Quick"!=J.active&&("indicator"==J.active&&a.classList.contains("PanelIcons")?Ec(a):("gMenuItems"==a.className||"kMenuItems"==a.className)&&kc(a)==J.Pb&&gc(a))}function jd(a){var c=a.id.split("_");"Lc"==c[0]&&(Na=!0,td(a.id));"eL"!=c[0]&&"eN"!=c[0]&&"eC"!=c[0]||!document.getElementById("eC_"+c[1])||(document.getElementById("eC_"+c[1]).className="expoIconHover")}
function id(){if(y.ub){var a=y.ub.id.split("_");"eL"!=a[0]&&"eN"!=a[0]&&"eC"!=a[0]||!document.getElementById("eC_"+a[1])||(document.getElementById("eC_"+a[1]).className="expoIcon")}}
function qd(a,c){c.classList.contains("toolTipclass")?(ud(a),Na=!0,Vc(parseFloat(c.id),c.id)):Na&&!c.classList.contains("ttElem")&&(Na=!1,md());"screen_img"==c.className?pd(parseFloat(c.id),a):"TTnums"==c.className?od(a,parseFloat(c.id)):"wordSearch_grid"==c.className?vd(c.id):"wordSearch_ctr"==c.className?vd(c.parentNode.id):"_BPgameArea"==c.id.slice(-11)&&(c=parseFloat(c.id),E[c].a.Kb=a.clientX-(document.getElementById(c).offsetLeft+8+document.getElementById(c+"Box").offsetLeft),E[c].a.lc=a.clientY-
(document.getElementById(c).offsetTop+8+document.getElementById(c+"Box").offsetTop),E[c].a.Y.left=E[c].a.Kb-E[c].a.Y.width/2,0==E[c].a.f.speed&&(E[c].a.f.left=E[c].a.Y.left+(E[c].a.Y.width/2-E[c].a.f.width/2)))}
function wb(a){window.clearTimeout(y.Ua);var c=Nc(a);if("input"==c.nodeName.toLowerCase()||"form"==c.nodeName.toLowerCase())Bb();else{var d=z.w;1>d.length&&(d=0);$c?wd(F,a):Ea?xd(z.w):Fa?yd(z.w):Wa||Va?zd(a,"",""):"click"===y.type&&"Moving"!=z.J&&"Resizing"!=z.J&&Ad(a,c);Bd(a,c);if(1==y.button&&"scrolling"==y.type){var e=(new Date).getTime(),f=(y.Za-y.Ca)/((e-y.startTime.getTime())/1E3),g=parseFloat(z.w);isNaN(g)&&(g=0);E[g].Vc=window.requestAnimationFrame(function(){Lc(g,f,e)})}""==z.w||"Moving"!=
z.J&&"Resizing"!=z.J||"full"==E[z.w].Window.R||"max"==E[z.w].Window.R||"min-max"==E[z.w].Window.R||("Moving"==z.J&&(document.getElementById(d+"gMenu").style.width="Ub"==x?document.getElementById(d).offsetWidth-document.getElementById(d+"gMenu").offsetLeft+"px":"100%"),vc(z.w));Pa&&"gMenuSub"!=J.active&&sd();"vidDown"==z.J&&Cd(z.w);0<F&&document.getElementById(F+"TopBar")&&(document.getElementById(F+"Title").style.cursor=document.getElementById(F+"TopBar").style.cursor="default");"deleteMenu"==J.active||
"deleteTitleMenu"==J.active||"deletegMenu"==J.active?(hc(),d=z.w,1>d.length&&(d=0)):"gMenuSub"==J.active&&(J.active="deletegMenu");if(Na&&0<K.style.opacity&&!y.ca.classList.contains("toolTipclass"))Dd();else if(y.ca.classList&&y.ca.classList.contains("toolTipclass")){gd(a);return}a=y.hb;Bb();y.hb=a}}
function Ad(a,c){if(c.classList.contains("LauncherIconCover"))zd(a,S[parseInt(c.id.slice(3),10)].s,c.id);else if("kStartButton"==c.className||"kStartButton"==c.parentNode.className||"kTaskImg"==c.className)0==c.id.slice(2)?zd(a,c.id.slice(2),c.id):zd(a,E[c.id.slice(2)].Window.s,c.id);else if(0<c.id.indexOf("CloseButton"))wc(parseFloat(c.id));else if(0<c.id.indexOf("MinButton")){var d=parseFloat(c.id);(a=document.getElementById(d))&&!isNaN(parseInt(d,10))&&(a.hidden=!0,document.getElementById("b_"+
d).style.opacity="0.5","max"==E[d].Window.R?E[d].Window.R="min-max":"nor"==E[d].Window.R&&(E[d].Window.R="min-nor"),jc(a,"del"))}else if(0<c.id.indexOf("MaxButton"))zc(parseFloat(c.id));else if(0<c.id.indexOf("AOE"))E[parseFloat(c.id)].Window.wb=!E[parseFloat(c.id)].Window.wb;else if("lExpoClose"==c.id)Tb();else if("expoTabs"==c.className)c.parentNode.getElementsByClassName("expoTabSeld")[0].className="expoTabs",c.className="expoTabSeld",oc(c.id.slice(5));else if(0<=c.id.indexOf("notifyClose"))Kb(c.parentNode.id.slice(8));
else if("uLauncher"==c.id)zd(a,-1,"");else if("expoIconHover"==c.className||"expoIcon"==c.className||"LauncherIcon"==c.className||"expoName"==c.className)Tb(),T(c.id);else if(c.classList.contains("uButtons"))Ed(c);else if("contactFB"===c.id)T("_12");else if("sliderI-tg"===c.id.slice(0,10))Fd(c);else if("FS"===c.id.slice(-2))U(parseFloat(c.id));else if("thm"===c.id.slice(0,3)&&(a=parseInt(c.id.split("_")[2],10),u!=a)){document.getElementById("UnityPanel").classList.remove(t[u].La);document.getElementById("UnityPanel").classList.add(t[a].La);
c=document.getElementsByClassName("windowTopBar");for(var e=0;e<c.length;e++)c[e].classList.remove(t[u].La),c[e].classList.add(t[a].La);c=document.getElementsByClassName("gMenu");for(e=0;e<c.length;e++)c[e].classList.remove(t[u].La),c[e].classList.add(t[a].La);c=document.getElementsByClassName("windowTopBar");for(e=0;e<c.length;e++)c[e].classList.remove(t[u].La),c[e].classList.add(t[a].La);document.getElementById("RCMcontainer")&&(document.getElementById("RCMcontainer").classList.remove(t[u].fb),
document.getElementById("RCMcontainer").classList.add(t[a].fb));K.classList.remove(t[u].fb);K.classList.add(t[a].fb);for(d in n)document.getElementById("NotyCont"+n[parseFloat(d)]).classList.remove(t[u].fb),document.getElementById("NotyCont"+n[parseFloat(d)]).classList.add(t[a].fb);u=a;Jc("webtopTheme",u)}}
function Bd(a,c){if(c.classList.contains("LauncherIconCover"))Wa&&zd(a,"UP","");else if(c.classList.contains("RCMenu")){c=c.id.split("_");if("ql"==c[0]){a=c[1];c=c[2];if("create"==c)T("_"+S[a].s);else if("unlock"==c)S[a].locked=!1,1!=document.getElementById("T_"+a).style.opacity&&(yc(a),Gd());else if("lock"==c)S[a].locked=!0,Gd();else if("new"==c)T("newInstance_"+S[a].Window.s);else if("quit"==c)for(var d in E)E[parseFloat(d)].Window.s==a&&wc(d);Na=!1;md()}else"gMenu"==c[2]?E[c[0]].I[c[3]].v[c[1]].g():
"rMenu"==c[2]?E[c[0]].va[c[1]].g():"iMenu"==c[2]&&Bc(c[0])[c[1]].g();J.active="deleteMenu"}else"tATnums"==c.className?yd(parseFloat(c.id)):"TTnums"==c.className?xd(parseFloat(c.id)):"wordSearch_grid"==c.className?Hd(c.id,a):"wordSearch_ctr"==c.className&&Hd(c.parentNode.id,a)}
function Ed(a){var c=a.id.split("_");if(1!=c.length)if("dm"==c[1])Id(c[0],c[2]);else if("wc"==c[1])"Figs"==c[2]?T("_"+mc(c[0])):"UPFigures"==c[2]&&Jd(c[0]);else if("dmW"==c[1])"bOK"==c[2]&&Kd(c[0],"OK"),"bNO"==c[2]&&Kd(c[0],"NO");else if("stor"==c[1])Ld(c[0],c[2]);else if("sImp"==c[1])Md();else if("sExp"==c[1])Nd();else if("errNt"==c[1]){if(Od(),a=document.getElementsByClassName("notifier"),0<a.length){c=a.length;for(var d=0;d<c;d++)Kb(a[d].id.slice(8))}}else"tATM"===c[1]||"tATB"===c[1]?Pd(a.id):
"tATOK"===c[1]?Qd(c[0]):"ws"===c[1]?Rd(c[0]):"full"===c[1]?(Qa=c[0],fb.call(document.documentElement,function(){})):"storC"===c[1]?(Sd(c[2]),Kb(c[0])):"tg"===c[0]?Fd(a):"wall"===c[0]&&Td(c[1],c[2])}function qb(a){a.cancelable&&pb(a);Ud(Nc(a),0<(a.deltaY?-a.deltaY:a.wheelDelta)?1:-1)}
function Ud(a,c){var d=kc(a);if(document.getElementById("lExList")||a.classList.contains("letScroll"))document.getElementById("lExList")?(y.hb="lExList",d=0):(y.ca=kc(a),isFinite(parseFloat(y.ca))&&(y.hb=parseFloat(y.ca)+"Box")),E[d].Window.Vc=0>c?window.requestAnimationFrame(function(){Lc(d,-1E3,(new Date).getTime())}):window.requestAnimationFrame(function(){Lc(d,1E3,(new Date).getTime())});else if(a&&"select"==a.nodeName.toLowerCase()){var e=a.selectedIndex;0<=e+c&&e+c<=a.length-1&&(a.selectedIndex+=
c,"tATimer"==E[parseInt(a.id,10)].Window.H?Vd(a.id,c):"WCalc"==E[d].Window.H?a.id==d+"Combo1"?Wd(a.selectedIndex,d):a.id==d+"Combo2"&&Xd(a.selectedIndex,d):"DM"==E[d].Window.H&&Yd(d))}else"uLauncher"==a.id||a.classList.contains("LauncherIconCover")?Zd(c):"screen_img"==a.className?Yb(parseFloat(a.id),c):isFinite(d)&&"tATimer"==E[d].Window.H?Vd(a.id,c):"TT"==a.className.slice(0,2)?$d(a.id,c):"vid"==a.className.slice(0,3)&&ae(a.id,c)}
function be(a){return{button:1,target:a.target,id:a.identifier,clientX:a.clientX,clientY:a.clientY,preventDefault:function(){},stopPropagation:function(){},cancelable:true}}
function rb(a){for(var c=a.changedTouches,d=!1,e=0;e<c.length;e++){var f=c[e].identifier;B[f]=be(c[e]);0<f&&window.clearTimeout(y.Ua);B[f].target&&!B[f].target.classList.contains("editEnable")&&(0==f&&(vb(B[f]),ub(B[f])),d=!0)}ce()&&(C.window=parseFloat(B[0].target.id),C.x[0]=B[0].clientX,C.y[0]=B[0].clientY,C.x[1]=B[1].clientX,C.y[1]=B[1].clientY);d&&pb(a)}
function sb(a){for(var c=a.changedTouches,d=!1,e=0;e<c.length;e++){var f=c[e].identifier;0<=f&&B.splice(f,1,be(c[e]));if(B[f]&&(B[f].target=document.elementFromPoint(B[f].clientX,B[f].clientY),B[f].target&&!B[f].target.classList.contains("editEnable"))){if(ce()){f=C.x[0]-C.x[1];var g=B[0].clientX-B[1].clientX;d=f-g;C.x[0]>C.x[1]&&(d=-d);f=C.y[0]-C.y[1];g=B[0].clientY-B[1].clientY;f-=g;C.y[0]>C.y[1]&&(f=-f);d=(d+f)/25;f=parseFloat(C.window);C.window&&("Screens"==E[f].Window.H?Yb(f,d):(f=d,d=document.getElementById(z.w),
g=parseFloat(d.offsetHeight)+f,d.style.height=E[z.w].Window.O<g?g+"px":E[z.w].Window.O+"px",f=parseFloat(d.offsetWidth)+f,d.style.width=E[z.w].Window.P<f?f+"px":E[z.w].Window.P+"px",document.getElementById(z.w+"gMenu").style.width=0,Rb(z.w),document.getElementById(z.w+"gMenu").style.width=d.offsetWidth-document.getElementById(z.w+"gMenu").offsetLeft+"px","Ku"===x&&(d=document.getElementById(z.w+"appImg").offsetLeft+document.getElementById(z.w+"appImg").offsetWidth,document.getElementById(z.w+"Title").style.left=
(document.getElementById(z.w+"MinButton").offsetLeft-d)/2-document.getElementById(z.w+"Title").offsetWidth/2+d+"px")));C.x[0]=B[0].clientX;C.x[1]=B[1].clientX;C.y[0]=B[0].clientY;C.y[1]=B[1].clientY}else vb(B[f]);d=!0}}d&&pb(a)}
function tb(a){for(var c=a.changedTouches,d=!1,e=0;e<c.length;e++){var f=c[e].identifier;0<=f&&B[f]&&(B[f].target?(id(),B[f].target.classList.contains("editEnable")&&(d=!0)):(B[f].target=document.getElementById("Wallpaper"),d=!0),wb(B[f]),delete B[f])}C={window:0,x:[0,0],y:[0,0]};d||(0==a.cancelable&&(a.cancelable=!0,a.cancelBubble=!0,a.bubbles=!1),pb(a))}function ce(){var a=0,c=[],d;for(d in B){var e=parseFloat(B[parseFloat(d)].target.id);e&&(c[a]=e,a++)}return 2==a&&c[0]==c[1]?!0:!1}
function Sc(){document.getElementById("winCover").style.height="100%";Pa=1}function sd(){Pa&&(document.getElementById("winCover").style.height="0",Pa=0)}
function Rc(a,c){pb(a);Wa||(1==y.button?(y.type="click",y.startTime=new Date,y.Ba=a.clientX,y.Ca=a.clientY,y.Ua=window.setTimeout(function(){Uc(a,c,document.getElementById(c))},500),-1==c?(Xa="uLauncher",Za=document.getElementById(Xa).offsetTop,Ya=document.getElementById(Xa).offsetLeft):(Za=document.getElementById(c).parentNode.parentNode.offsetTop,Ya=document.getElementById(c).parentNode.parentNode.offsetLeft,Xa=parseInt(c.split("_")[1],10)),Ba=a.clientY-Za,Ca=a.clientX-Ya,z.J="launcerMD"):3==y.button&&
fd(c.split("_")[1]))}
function rd(a){if(!ab){ab=!0;if("launcerMD"==z.J){var c=document.getElementById("uLauncher");if(Wa){c=!1;var d=a.clientX-Ca;a=a.clientY-Ba;document.getElementById("C_"+Xa).style.top=a-6+"px";document.getElementById("C_"+Xa).style.left=d-6+"px";d=R.indexOf(Number(Xa));try{for(var e in R){if(99!=R[Number(e)]){var f=document.getElementById("C_"+R[Number(e)]);if(e!=d&&f.offsetTop-24<a&&f.offsetTop+f.offsetHeight>a+24)if(e<d)for(var g=d-1;g>=e;g--){var h=document.getElementById("C_"+R[Number(g)]);document.getElementById("uLauncher").removeChild(h);
var m=R.splice(d,1);document.getElementById("uLauncher").insertBefore(h,document.getElementById("C_"+Xa).nextElementSibling);d--;R.splice(d,0,m[0]);c=!0}else for(g=d+1;g<=e;g++)h=document.getElementById("C_"+R[Number(g)]),document.getElementById("uLauncher").removeChild(h),m=R.splice(d,1),document.getElementById("uLauncher").insertBefore(h,document.getElementById("lSpacer")),d++,R.splice(d,0,m[0]),c=!0}if(c)break}}catch(p){}}else Va?(e=a.clientY-Ba,24<e?e=24:e+c.offsetHeight<document.getElementById("Wallpaper").offsetHeight&&
(e=document.getElementById("Wallpaper").offsetHeight-c.offsetHeight),c.style.top=e+"px"):Ba+Za-12>a.clientY||Ba+Za+12<a.clientY?(Va=!0,Na=Wa=!1,md()):isFinite(Xa)&&Ca+Ya+20<a.clientX&&(e=Xa,"99"!=e&&"0"!=e&&(Wa=!0,Na=Va=!1,md(),Ba=Za+21,Ca=Ya+21,document.getElementById("T_"+Xa).style.opacity=0,document.getElementById("Tl").style.opacity=0,e=document.getElementById("C_"+Xa),e.style.top=e.offsetTop+"px",e.style.left=e.offsetLeft+"px",e.style.position="absolute",f=document.createElement("div"),f.id=
"lSpacer",f.className="LauncherContainer",document.getElementById("uLauncher").insertBefore(f,e)))}ab=!1}}
function zd(a,c,d){pb(a);window.clearTimeout($a);0<=c&&!Va&&!Wa&&"Quick"!=J.active?2==y.button?T("newInstance_"+c+"_"+d):T("L_"+c+"_"+d):Wa&&(document.getElementById("uLauncher").removeChild(document.getElementById("lSpacer")),a=document.getElementById("C_"+Xa),a.style.position="",a.style.top="",a.style.left="",0<F&&(document.getElementById("Tl").style.top=document.getElementById("C_"+parseInt(E[parseFloat(F)].Window.s,10)).offsetTop+10+"px",document.getElementById("Tl").style.opacity=1),.5==document.getElementById("D_"+
Xa).style.opacity&&(document.getElementById("T_"+Xa).style.opacity=1),Gd());Wa=Va=!1}function Zd(a){var c,d=document.getElementById("uLauncher");0<a?c=document.getElementById("uLauncher").offsetTop+30:c=document.getElementById("uLauncher").offsetTop-30;24<c?c=24:c+d.offsetHeight<document.getElementById("Wallpaper").offsetHeight&&(c=document.getElementById("Wallpaper").offsetHeight-d.offsetHeight);d.style.top=c+"px"};var Hb="style=\"background:center/contain no-repeat url('images/allTheSocials/",w=' src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAACAQMAAABIeJ9nAAAAA1BMVEUAAACnej3aAAAAAXRSTlMAQObYZgAAAApJREFUCNdjAAIAAAQAASDSLW8AAAAASUVORK5CYII="',Q=[{s:1,K:"#00ff21",V:"app",C:" -104px -135px",appName:"TeaTimer",T:"tt_Init"},{s:2,K:"#00b6b6",V:"app",C:" -208px -83px",appName:"Wage Calculator",T:"wc_Init"},{s:3,K:"#00ff00",V:"app",C:" -0px -135px",appName:"DUMbasic",T:"screen_Init"},{s:4,K:"#996b28",V:"app",
C:" -0px -83px",appName:"Private Diary",T:"screen_Init"},{s:5,K:"#00ff00",V:"app",C:" -156px -83px",appName:"Dosh Manager",T:"dm_Init"},{s:6,K:"#00ff00",V:"game",C:" -52px -135px",appName:"JS Cavern",T:"jsc_Init"},{s:7,K:"#8c8b8c",V:"game",C:" -52px -83px",appName:"ArcNerd",T:"bp_Init"},{s:8,K:"#8c8b8c",V:"app",C:" -104px -83px",appName:"Browser Benchmarker",T:"bb_Init"},{s:9,K:"#fffedd",V:"game",C:" -156px -135px",appName:"WordSearch",Bb:"/wordsearch",tb:"wordsearch/index.html",cb:"StewVed",sb:"",
rb:"",T:"if_Init"},{s:11,K:"#5e5e4d",V:"app",C:" -260px -135px",appName:"Video Player",T:"vid_Init"},{s:12,K:"#fffedd",V:"help",C:" -156px -187px",appName:"Feedback / Contact",T:"zFbInit"},{s:13,K:"#00ff00",V:"sett",C:" -0px -187px",appName:"Change Background",T:"wall_Init"},{s:15,K:"#fffedd",V:"sett",C:" -208px -187px",appName:"Storage",T:"Win_storage"},{s:16,K:"#fffedd",V:"app",C:" -260px -187px",appName:"Tillago Timer",T:"tAT_Init"},{s:17,K:"#fffedd",V:"app",C:" -0px -239px",appName:"App Timer",
T:"screen_Init"},{s:18,K:"#fffedd",V:"app",C:" -52px -239px",appName:"Event Manager",T:"screen_Init"},{s:19,K:"#fffedd",V:"sett",C:" -104px -239px",appName:"Desktop Chooser",T:"dChoose"},{s:21,K:"#fffedd",V:"app",C:" -156px -239px",appName:"Tone Generator",T:"tg_Init"},{s:22,K:"#fffedd",V:"app",C:" -260px -239px",appName:"Calories per grams calculator",T:"cpw_Init"},{s:25,K:"#00ff00",V:"app",C:" -156px -83px",appName:"Savings Vs Loans",T:"svl_Init"},{s:26,K:"#00ff00",V:"sett",C:" -0px -292px",appName:"Theme Chooser",
T:"theme_Init"},{s:99,K:"#ff7700",V:"help",C:"images/1425710397e.svg",appName:"Support Stewved",Bb:"/supportstewved",tb:"support-stewved/index.html",cb:"StewVed",sb:"",rb:"",T:"if_Init"},{s:100,K:"#00dd00",V:"help",C:" -208px -135px",appName:"About StewVed&apos;s Webtop",T:"Win_createDialogueInit"},{s:101,appName:"Toddler Colors",K:"#3aaff0",V:"game",C:"https://stewved.github.io/toddlercolors/favicon.png",Bb:"https://github.com/StewVed/toddlercolors",tb:"https://stewved.github.io/toddlercolors/index.html",
cb:"StewVed",Hb:"https://stewved.github.io",sb:"https://stewved.github.io",rb:"https://stewved.github.io/toddlercolors/README.md",T:"if_Init"},{s:102,appName:"MemGuess",K:"#3aaff0",V:"game",C:"https://stewved.github.io/memguess/favicon.png",Bb:"https://github.com/StewVed/memguess",tb:"https://stewved.github.io/memguess/index.html",cb:"StewVed",Hb:"https://stewved.github.io",sb:"https://stewved.github.io",rb:"https://stewved.github.io/memguess/README.md",T:"if_Init"},{s:103,appName:"toddlearner",K:"#3aaff0",
V:"game",C:"https://stewved.github.io/toddlearner/favicon.png",Bb:"https://github.com/StewVed/toddlearner",tb:"https://stewved.github.io/toddlearner/index.html",cb:"StewVed",Hb:"https://stewved.github.io",sb:"https://stewved.github.io",rb:"https://stewved.github.io/toddlearner/README.md",T:"if_Init"},{s:104,appName:"toddlearner",K:"#3aaff0",V:"game",C:"https://stewved.github.io/audiotester/favicon.png",Bb:"https://github.com/StewVed/audiotester",tb:"https://stewved.github.io/audiotester/index.html",
cb:"StewVed",Hb:"https://stewved.github.io",sb:"https://stewved.github.io",rb:"https://stewved.github.io/audiotester/README.md",T:"if_Init"},{s:105,appName:"Calorie Calculator",K:"#fffedd",V:"app",C:"https://stewved.github.io/calorieCalculator/favicon.png",Bb:"https://github.com/StewVed/calorieCalculator",tb:"https://stewved.github.io/calorieCalculator/index.html",cb:"StewVed",Hb:"https://stewved.github.io",sb:"https://stewved.github.io",rb:"https://stewved.github.io/calorieCalculator/README.md",
T:"if_Init"}],de=[{s:0,appName:"All apps",C:" -283px -16px",K:"#fff",locked:!0},{s:99,K:"#ff7700",V:"help",C:"images/1425710397e.svg",appName:"Support Stewved",Bb:"/supportstewved",tb:"support-stewved/index.html",cb:"StewVed",sb:"",rb:"",T:"if_Init",locked:!0},{s:8,appName:"Browser Benchmarker",C:" -104px -83px",K:"#8c8b8c",locked:!0},{s:9,appName:"WordSearch",C:" -156px -135px",K:"#fffedd",locked:!0},{s:5,appName:"Dosh Manager",C:" -156px -83px",K:"#00ff00",locked:!0},{s:6,appName:"JS Cavern",C:" -52px -135px",
K:"#00ff00",locked:!0}],S=[],R=[],Gb=[{Text:"Fullscreen toggle",g:function(){U("0")}},{Text:"Change Background...",g:function(){T("_13")}},{Text:"<hr>"},{Text:"About StewVed&apos;s Webtop",g:function(){T("stewvedsWebtop-StewVed&apos;s Webtop_100")}},{Text:"StewVed&apos;s Webtop Changelog",g:function(){T("SiteCL-StewVed&apos;s Webtop_100")}},{Text:"Webtop Statistics",g:function(){T("_14")}},{Text:"",g:function(){Od()}}],Cc=[{Text:"For Rizz...",g:function(){Lb()}},{Text:"TillAgoTimer",g:function(){T("_16")}},
{Text:"TeaTimer",g:function(){T("_1")}}],Dc=[{Text:"Volume Control"}],gb=[{Text:'<p class="B pZW">Contact StewVed:</p>'},{Text:"Feedback / Contact Webapp",g:function(){T("_12")}},{Text:'<img class="imgSocs" '+Hb+"Facebook.png');\""+w+">Stewved's Webtop on FaceBook",g:function(){Ib("https://www.facebook.com/StewvedsWebtop")}},{Text:'<img class="imgSocs" '+Hb+"Facebook.png');\""+w+">Stewved on FaceBook",g:function(){Ib("https://www.facebook.com/Stewved")}},{Text:'<img class="imgSocs" '+Hb+"Twitter.png');\""+
w+">Stewved on Twitter",g:function(){Ib("https://twitter.com/StewVed")}},{Text:"<hr>"},{Text:'<img class="imgSocs" style="background:center/contain no-repeat url(\'images/1425710397e.svg\');"'+w+">Support StewVed",g:function(){Ib("https://stewved.co.uk/support-stewved")}}];function Tb(){document.getElementById("lExpo").style.opacity=0;window.setTimeout(function(){document.getElementById("lExpo")&&document.getElementById("lExpo").parentNode.removeChild(document.getElementById("lExpo"))},300)}
function rc(a,c){if(E[a].Window.qa){var d=E[a].Window.s;if("all"==c){S[E[a].Window.s]={s:Q[E[a].Window.qa].s,appName:Q[E[a].Window.qa].appName,C:Q[E[a].Window.qa].C,K:Q[E[a].Window.qa].K,locked:!1};R.push(d);var e=document.createElement("div");e.id="C_"+d;e.className="LauncherContainer";var f='<img id="T_'+d+'" class="lTriangle" '+D+' -131px -44px;opacity:1;"'+w+">";f+='<div id="D_'+d+'" class="LauncherIconBack" style="background-color:'+S[d].K+';opacity:0.5;"></div>';f+='<img id="L_'+d+'" class="LauncherIcon" ';
f=" -"==S[d].C.slice(0,2)?f+(D+S[d].C+';"'+w+">"):f+("style=\"background:center/contain no-repeat url('"+S[d].C+"');\""+w+">");f+='<img id="Lc_'+d+'" class="LauncherIconCover ttElem" '+D+' -198px -26px;"'+w+">";e.innerHTML=f;document.getElementById("uLauncher").appendChild(e)}if("all"==c||"ku"==c)c=document.createElement("div"),c.id="b_"+a,c.className="kStartButton",f='<div id="f_'+a+'" class="kTask"></div>'+('<img id="i_'+a+'" class="kTaskImg"')," -"==S[E[a].Window.s].C.slice(0,2)?(d=S[E[a].Window.s].C.split(" "),
f+='style="background-image: url('+va.src+");background-position:"+.313725490196*parseFloat(d[1])+"px "+.313725490196*(parseFloat(d[2])-1)+'px;"'):f+="style=\"background:center/contain no-repeat url('"+S[E[a].Window.s].C+"');\"",f+=w+'><div id="t_'+a+'" class="kTaskTitle">'+S[E[a].Window.s].appName+"</div>",c.innerHTML=f+"</div>",document.getElementById("kTaskBar").appendChild(c),document.getElementById("b_"+a).addEventListener("mouseover",function(){document.getElementById("f_"+a).classList.add("kTaskH")},
!1),document.getElementById("b_"+a).addEventListener("mouseout",function(){document.getElementById("f_"+a).classList.remove("kTaskH")},!1)}Ub("change")}function jb(){var a=ib("Launcher Icons");if(a)try{var c=a.split(O);for(a=0;a<c.length-1;a++){var d=c[a].split(bb);if(100!=d[0])S[d[0]]={s:d[0],appName:d[1],C:d[2],K:d[3],locked:"true"===d[4]},R.push(parseFloat(d[0]));else var e=!0;e&&Gd()}S[0]||ee()}catch(f){ee()}else ee()}
function Gd(){var a="",c;for(c in R)1==S[R[parseFloat(c)]].locked&&(a+=S[R[parseFloat(c)]].s+bb+S[R[parseFloat(c)]].appName+bb+S[R[parseFloat(c)]].C+bb+S[R[parseFloat(c)]].K+bb+S[R[parseFloat(c)]].locked+O);a&&Jc("Launcher Icons",a)}function ee(){R=[];S=[];var a;for(a in de){var c=parseFloat(de[parseFloat(a)].s);S[c]=de[parseFloat(a)];R.push(c)}}
function oc(a){var c=P/120,d=parseInt(120+(c-parseInt(c,10))/parseInt(c,10)*120,10);c='style="width:'+d+'px;"';d=Math.floor((d-51)/2);var e="",f=!1,g;for(g in Q){if("Ub"==x)for(var h in S)if(Q[parseFloat(g)].s==S[parseFloat(h)].s){f=!0;break}"all"!=a&&a!=Q[parseFloat(g)].V&&(f=!0);if(f)f=!1;else{var m=Q[parseFloat(g)].appName;m=m.replace(/'/g,"'");e+='<div id="eC_'+Q[parseFloat(g)].s+'" class="expoIcon" '+c+' ">';e=" -"==Q[parseFloat(g)].C.slice(0,2)?e+('<img id="eL_'+Q[parseFloat(g)].s+'" class="LauncherIcon" '+
D+Q[parseFloat(g)].C+";transform:scale(1.5);left:"+d+'px;top:18px;"'+w+" >"):e+('<img id="eL_'+Q[parseFloat(g)].s+'" class="LauncherIcon"  style="background:center/contain no-repeat url(\''+Q[parseFloat(g)].C+"');left:"+d+'px;top:18px;width:51px;height:51px;transform: scale(1.5);"'+w+" >");e+='<div id="eN_'+Q[parseFloat(g)].s+'" class="expoName" style="top:84px;" >'+m+"</div></div>"}}document.getElementById("lExList").innerHTML=e}
function nc(a,c){return a.appName<c.appName?-1:a.appName>c.appName?1:0}
function Ub(a){var c=document.getElementById("Wallpaper").offsetHeight-document.getElementById("UnityPanel").offsetHeight,d=58*R.length+6,e=document.getElementById("uLauncher");e.style.height=d>c?d+"px":c+"px";c=e.offsetTop;"change"==a&&(c=document.getElementById("Wallpaper").offsetHeight-e.offsetHeight);c>document.getElementById("UnityPanel").offsetHeight?c=document.getElementById("UnityPanel").offsetHeight:c+e.offsetHeight<document.getElementById("Wallpaper").offsetHeight&&(c=document.getElementById("Wallpaper").offsetHeight-
e.offsetHeight);e.style.top=c+"px";a=document.getElementById("kTaskBar").childNodes;if(e=a.length-1)for(c=document.getElementById("kTaskBar").offsetWidth-document.getElementById("b_0").offsetWidth,c=a[1].offsetWidth*e>c||256*e>c?Math.floor(c/e)-2:256,d=1;d<=e;d++)a[d].style.width=c+"px"}
function fd(a){document.getElementById("RCMcontainer")&&hc();var c='class="RCMenu '+t[u].eb+'" ';var d='<div id="ql_'+a+'_create" style="font-weight:bold;" '+c+">"+S[a].appName+"</div>";if(0!=a&&99!=a&&100!=parseInt(a,10)){d=S[a].locked?d+('<div id="ql_'+a+'_unlock" '+c+">Unlock from Launcher</div>"):d+('<div id="ql_'+a+'_lock" '+c+">Lock to Launcher</div>");var e=0,f=parseInt(a,10),g;for(g in E)parseInt(E[parseFloat(g)].Window.s,10)==f&&(e+=1);e&&(d=d+('<div id="ql_'+a+'_new" '+c+">New Window (middle Click)</div>")+
('<div id="ql_'+a+'_quit" '+c),d=1==e?d+">Quit</div>":d+">Close all windows</div>")}else d='<p style="margin:6px;padding:0;">'+d+'<p style="margin:6px;padding:0;">';0!=d.length&&(ic(d),J.active="Quick",td(a),M.style.top=document.getElementById("C_"+a).offsetTop+document.getElementById("uLauncher").offsetTop+26-M.offsetHeight/2+"px",N.style.top=M.offsetTop-1+"px",a=document.getElementById("RCMcontainer"),a.style.left="70px",a.style.top=M.offsetTop-8+"px",M.style.left="63px",N.style.left="62px",K.style.opacity=
L.style.opacity=0,M.style.opacity=N.style.opacity=1,M.style.zIndex=9999,M.style.background="linear-gradient(45deg, rgba(38,38,38,1) 45%, rgba(0,0,0,0) 45%)")}function yc(a){delete S[a];var c=parseFloat(a);if(za||"Ub"==x)c=parseInt(a,10);R.splice(R.indexOf(c),1);document.getElementById("uLauncher").removeChild(document.getElementById("C_"+a));Ub("close")}
function td(a){if(!Va&&!Wa&&"Quick"!=J.active){a=Number(a.split("_")[1]);var c=document.getElementById("C_"+a).offsetTop+document.getElementById("uLauncher").offsetTop+26;M.style.background="linear-gradient(45deg, rgba(38,38,38,1) 45%, rgba(0,0,0,0) 45%)";N.style.border="1px solid rgba(255,255,255,0.5)";N.style.borderTop="0px";N.style.borderRight="0px";K.style.left="70px";L.style.left="70px";M.style.left="63px";N.style.left="62px";K.innerHTML=S[a].appName;M.style.top=c-M.offsetHeight/2+"px";K.style.top=
c-K.offsetHeight/2+"px";L.style.top=K.offsetTop-1+"px";L.style.width=K.offsetWidth-1+"px";L.style.height=K.offsetHeight+"px";N.style.top=M.offsetTop-1+"px";K.style.opacity=L.style.opacity=M.style.opacity=N.style.opacity=.9}};var fe="<^>",ge="<*>",he=0,V;window.Win_storage=function(a){E[a].Window.H="storage";document.getElementById(a+"Box").style.padding="4px";document.getElementById(a+"Box").style.backgroundColor="#fff";ie(a);E[a].Window.u=document.getElementById(a+"Cont").offsetWidth;E[a].Window.A=document.getElementById(a+"Cont").offsetHeight;E[a].Window.P=200;E[a].Window.O=Math.round(E[a].Window.A/4)};
function ie(a){var c='This webtop uses <a class="ubLink" style="color:#000;" href="http://www.w3schools.com/html/html5_webstorage.asp" target="_blank">HTML5 Local Storage</a>, (better than cookies).<br>Listed below is all of the stuff currently stored:<br><br>'+('<button id="'+a+'_sImp_" class="uButtons uButtonGrey" style="float:left;font-size:1.5em;width:40%;margin-left:2%;" type="button">Import Data</button><button id="'+a+'_sExp_" class="uButtons uButtonGrey" style="float:right;font-size:1.5em;width:40%;margin-right:2%;" type="button">Export Data</button><br><br>');
var d=0;"undefined"!==typeof Storage&&(d=V.length);if(0<d)for(var e=0;e<d;e++){var f=V.key(e);c+='<div id="'+a+f+'" style="margin-bottom:6px;margin:10px 0px 10px 2%;padding-left:4px;">'+f+'&nbsp;&nbsp;<button id="'+a+"_stor_"+f+'" class="uButtons uButtonGrey" style="position:absolute;" type="button">Delete</button></div>'}else c+="<p>Nothing is currently stored.<br>When you change something on the webtop,<br>you can choose for your browser to remember it.</p>";document.getElementById(a+"Box").innerHTML=
c;if(0<d){for(e=c=0;e<d;e++)f=V.key(e),document.getElementById(a+"_stor_"+f).offsetLeft>c&&(c=document.getElementById(a+"_stor_"+f).offsetLeft);for(e=0;e<d;e++)f=V.key(e),document.getElementById(a+"_stor_"+f).style.left=c+"px"}}function hb(){try{if(V=window.localStorage)if(V.length){var a=ib("AllowSave");he=1==a?1:0==a?-1:0}else he=0}catch(c){}-1===he&&l("localStorage appears to be unavailable in this browser. Unable to save anything.")}
function Sd(a){if("Y"==a){a=he[0];var c=he[1];he=1;Jc("AllowSave",he);Jc(a,c)}else he=-1}function Ld(a,c){try{V.removeItem(c),document.getElementById(a+c).parentNode.removeChild(document.getElementById(a+c))}catch(d){}}function ib(a){var c="";if(-1!=he)try{c=V.getItem(a)}catch(d){}return c}
function Jc(a,c){if(1==he)for(V.setItem(a,c),a=0;a<G.length;a++)"storage"==E[G[a]].Window.H&&ie(G[a]);else 0!=he||document.getElementById("_stor_Y")||(he=[a,c],l('Would you like your browser to remember your settings?<br>(Using <a class="ubLink" href="http://www.w3schools.com/html/html5_webstorage.asp" target="_blank">HTML5 Local Storage</a>, (better than cookies).)<br><br><button id="_storC_Y" class="uButtons uButtonGreen" type="button " style="font-size:1.5em;width:30%;margin:4px;float:left;">Yes</button><button id="_storC_N" class="uButtons uButtonRed" type="button" style="font-size:1.5em;width:30%;margin:4px;float:right;">No</button>'))}
function Nd(){var a="",c=0;"undefined"!==typeof Storage&&(c=V.length);if(0<c){for(var d=0;d<c;d++)a+=V.key(d)+fe,a+=V.getItem(V.key(d))+ge;c=document.createElement("a");c.setAttribute("href","data:text/plain;charset=utf-8,"+encodeURIComponent(a));c.download="stewVedsWebtopData";c.style.display="none";document.body.appendChild(c);c.click();document.body.removeChild(c)}}
function Md(){var a=document.createElement("input");a.setAttribute("type","file");a.style.display="none";document.body.appendChild(a);a.addEventListener("change",function(){je(this.files)},!1);a.click();document.body.removeChild(a)}
function je(a){if(window.File&&window.FileReader){var c=new FileReader;c.onload=function(){var a=c.result;V.clear();a=a.split(ge);try{for(var e=0;e<a.length-1;e++){var f=a[e].split(fe);V.setItem(f[0],f[1])}x=ib("webtopStyle");location.reload()}catch(g){alert("I am sorry, but the import failed.")}};c.readAsText(a[0])}else alert("Your broswer appears to not support HTML5 File Reading.")};var t=[{name:"StewVed Dark",La:"zThStewVedMain",fb:"zThStewVedMenu",eb:"zThStewVedMenH"},{name:"Ubuntu Ambiance",La:"zThAmbianceMain",fb:"zThAmbianceMenu",eb:"zThAmbianceMenH"}],u=0;
window.theme_Init=function(a){var c=E[a].Window;c.u=640;c.A=240;c.P=320;c.O=240;c.H="thm";c.m=1;c.ra=1;c=document.getElementById(a+"Box");c.style.backgroundColor="#fff";c.style.padding="4px";for(var d='<div style="position:relative;width:96%;height:32px;"></div>',e=0;e<t.length;e++)d+='<div id="thm_'+a+"_"+e+'" class="'+t[e].La+'" style="position:relative;width:96%;left:2%;border:0;box-shadow:0px 0px 14px #000;border-radius:8px 8px 0px 0px;cursor:default;height:32px;font-size:28px;color:#fff;text-align:center;">'+
t[e].name+'</div><div style="position:relative;width:96%;height:32px;"></div>';c.innerHTML=d+('<div id="thm_'+a+'_cover" NaN');document.getElementById(a+"Box").style.width=Math.round(.8*P)+"px";E[a].Window.u=document.getElementById(a+"Cont").offsetWidth;E[a].Window.A=document.getElementById(a+"Cont").offsetHeight;E[a].Window.P=Math.floor(E[a].Window.u/3);E[a].Window.O=E[a].Window.A};function md(){"Quick"!=J.active&&window.setTimeout(function(){Na||(Dd(),Ma="",K.innerHTML="")},10)}function Dd(){window.clearTimeout(La);K.style.opacity=L.style.opacity=M.style.opacity=N.style.opacity=Ka.style.opacity=0;K.style.top="-"+K.offsetHeight+"px";L.style.top="-"+L.offsetHeight+"px";L.style.width="0px";M.style.top="-"+M.offsetHeight+"px";N.style.top="-"+N.offsetHeight+"px";Ka.style.top="-"+Ka.offsetHeight+"px"}
function ad(){K.style.opacity=L.style.opacity=M.style.opacity=N.style.opacity=.9}function ud(a){isNaN(parseFloat(Nc(a).id))||.9==K.style.opacity&&Wc(Nc(a).id,!0)}function Vc(a,c){Ma!=c&&isFinite(a)&&(a=E[a].Nc[c.split("_")[1]],Ma=c,Oa='<span id="pupCapt">'+a+"</span>",La=window.setTimeout(function(){Wc(c,!1)},400))}
function Ob(){M.style.left=y.Ya-M.offsetWidth/2+"px";M.style.top=y.Za-M.offsetHeight-H+"px";Ka.style.top=M.offsetTop+H+"px";Ka.style.height=M.offsetHeight+"px";K.style.top=M.offsetTop-(K.offsetHeight-M.offsetHeight/1.5)+"px";var a=document.getElementById("Wallpaper").offsetWidth;a=y.Ya+2+K.offsetWidth/2>a?a-2-K.offsetWidth:y.Ya-K.offsetWidth/2;0>a&&(a=1);K.style.left=a+"px";L.style.left=Ka.style.left=K.offsetLeft-1+"px";L.style.top=K.offsetTop-1+"px";L.style.width=Ka.style.width=K.offsetWidth+"px";
L.style.height=K.offsetHeight+"px";N.style.left=M.offsetLeft+"px";N.style.top=M.offsetTop+"px";N.style.width=M.offsetWidth+"px";N.style.height=M.offsetHeight+1+"px";N.style.border="1px solid rgba(255,255,255,0.5)";N.style.borderTop="0px";N.style.borderLeft="0px"}function gd(a){var c=parseFloat(y.ub.id),d=y.ca.id;ud(a);Na=!0;Vc(c,d);Wc(d,!1);window.clearTimeout(La)}
function Wc(a,c){Ma==a?(K.innerHTML='<p style="margin:0;padding:0;text-align:center;">'+Oa.replace(/~#/g,"&").replace(/#Q/g,"&quot").replace(/-Q-/g,'\\"')+"</p>",ke(K),M.style.background="linear-gradient(315deg, rgba(0,0,0,1) 36%, rgba(0,0,0,0) 40%)",Ob(),c||ad()):c||Dd()}function ke(a){a=a.children;for(var c=0;c<a.length;c++)"br"!=a[c].nodeName.toLowerCase()&&a[c].classList.add("ttElem"),0<a[c].childElementCount&&ke(a[c])};var le,me,W=[],$c,ne,kd,oe=[],pe=1;window.Slids=oe;
window.wall_Init=function(a){var c=E[a].Window;c.u=640;c.A=240;c.P=320;c.O=240;c.H="wall";c.m=1;c.ra=1;E[a].I=[{Text:"Reset",v:[{Text:"Reset to defaults",g:function(){qe(a)}}]}];c=document.getElementById(a+"Box");c.style.backgroundColor="#fff";c.style.padding="4px";c.innerHTML='<button id="wall_'+a+'_s" type="button" class="uButtonLeft uButtons uButtonGrey" style="width:28%;height:32px;margin-left:4px;" value="0">Solid</button><button id="wall_'+a+'_l" type="button" class="uButtons uButtonGrey uButtonMid" style="width:28%;height:32px;margin-left:-1px;margin-right:-1px;" value="0">Linear</button><button id="wall_'+
a+'_r" type="button" class="uButtons uButtonGreen uButtonRight" style="width:28%;height:32px;margin-right:4px;" value="1">Circle</button><button id="wall_'+a+'_f" type="button" class="uButtons uButtonGrey" style="width:14%;height:32px;" value="0">Follow</button><br><br><div class="uButtons" style="float:left;clear:both;opacity:0;padding:8px;width:20%;"></div><button id="wall_'+a+'_1" type="button" class="uButtons uButtonGreen uButtonLeft" style="width:28%;height:32px;left:25%;" value="1">Color 1<span id="wall_'+
a+'_c1" style="background: hsl(0, 0%, 100%);height:24px;margin:-5px 0px 0px 8px;width:24px;position:absolute;border-radius:16px;"></span></button><button id="wall_'+a+'_2" type="button" class="uButtons uButtonGrey uButtonRight" style="width:28%;height:32px;margin-right:4px;" value="0">Color 2<span id="wall_'+a+'_c2" style="background: hsl(0, 0%, 100%);height:24px;margin:-5px 0px 0px 8px;width:24px;position:absolute;border-radius:16px;"></span></button><p id="wallH" class="cBtext" style="clear:both;">Hue</p>'+
re(1)+'<p id="wallS" class="cBtext">Saturation</p>'+re(2)+'<p id="wallL" class="cBtext">Luminocity</p>'+re(3)+'<p id="wallP" class="cBtext">overall color % <input id="wall_'+a+'_Ch" type="checkbox" class="editEnable uButtons" style="font-size:1.5em;margin:0px 6px 0px 0px;padding:0;border:0;vertical-align:middle;width:26px;height:26px;"></p>'+re(4)+"<br><br>";document.getElementById(a+"Box").style.width=Math.round(.8*P)+"px";E[a].Window.u=document.getElementById(a+"Cont").offsetWidth;E[a].Window.A=
document.getElementById(a+"Cont").offsetHeight;E[a].Window.P=Math.floor(E[a].Window.u/3);E[a].Window.O=E[a].Window.A;document.getElementById("wall_"+a+"_Ch").checked="%"==W[0].split(-1);document.getElementById("wallSlidera4").style.opacity=document.getElementById("wall_"+a+"_Ch").checked?.25:1;kd&&document.getElementById("wall_"+a+"_f").classList.add("uButtonGreen");Zb(a);a&&(document.getElementById("wall_"+a+"_c1").style.background=W[0],document.getElementById("wall_"+a+"_c2").style.background=W[1]);
se(a)};
function Zb(a){var c=W[pe-1].split(") "),d=c[0].slice(4).split(",");oe[0]=d[0]/3.6/100;oe[1]=parseFloat(d[1])/100;oe[2]=parseFloat(d[2])/100;c[1]&&"%"==c[1].slice(-1)?(oe[3]=parseFloat(c[1])/100,document.getElementById("wall_"+a+"_Ch").checked=!0,document.getElementById("wallSlidera4").style.opacity=1):(oe[3]=0,document.getElementById("wall_"+a+"_Ch").checked=!1,document.getElementById("wallSlidera4").style.opacity=.25);document.getElementById("wall_"+a+"_c1").style.background=W[0];document.getElementById("wall_"+a+
"_c2").style.background=W[1];ac()}function re(a){return'<div id="wallSlidera'+a+'" class="winSliderCont" style="width:100%;height:16px;"><div id="wallSliderb'+a+'" class="winSliderInner" style="position:relative;top:-10px;left:43%;height:32px;width:32px;transition:0.2s;"></div></div>'}
function lb(){var a=ib("Wallpaper");if(a)try{var c=a.split(O);le=c[0];me=c[1];var d=c[2];ne=c[3];kd=parseInt(c[4],10);"so"!=le.slice(0,2)&&"li"!=le.slice(0,2)&&"ra"!=le.slice(0,2)&&qe(0);W=d.split("|");te()}catch(e){qe(0)}else qe(0)}function ue(){for(var a="",c=0;c<W.length;c++)a+=W[c]+"|";a=a.slice(0,-1);Jc("Wallpaper",le+O+me+O+a+O+ne+O+kd+O)}
function qe(a){le="radial-gradient(";me="circle at 90% 24%, ";W=["hsl(26,100%,50%)","hsl(281,100%,33%) 70%"];$c=0;ne="non";kd=0;try{V.removeItem("Wallpaper")}catch(c){}te();document.getElementById(a)&&Zb(a)}function ld(a){me="circle at "+Math.round(a.clientX/document.getElementById("Wallpaper").offsetWidth*100)+"% "+Math.round(a.clientY/document.getElementById("Wallpaper").offsetHeight*100)+"%,";te()}
function se(a){var c=ne;if(c!==ne){for(var d in E[a].I[2].v)"&"==E[a].I[2].v[d].Text[0]&&(E[a].I[2].v[d].Text=E[a].I[2].v[d].Text.split(";")[1]);"non"==c?(E[a].I[2].v[0].Text="&#10004;\tNormal",kd=0,ne="non",te()):"fM"==c?(E[a].I[2].v[1].Text="&#10004;\tFollow Mouse",kd=1,ne="fM"):"tD"==c&&(E[a].I[2].v[1].Text="&#10004;\tFollow Mouse",kd=1,ne="tD");wd(a,{clientX:0,clientY:0})}}
function bd(a,c){var d=y.ca.parentNode.offsetWidth;c=c.clientX-document.getElementById(a).offsetLeft-y.ca.parentNode.offsetLeft-H;c-=y.ca.offsetWidth/2;c=c/(d-y.ca.offsetWidth)*100;0>c?c=0:100<c&&(c=100);d=(d-y.ca.offsetWidth)/d;Nb(c.toFixed(2)+"%");y.ca.style.left=c*d+"%";oe[$c-1]=c/100;d="";document.getElementById("wall_"+a+"_Ch").checked&&(d=" "+Math.round(100*oe[3])+"%");W[pe-1]="hsl("+Math.round(360*oe[0])+","+Math.round(100*oe[1])+"%,"+Math.round(100*oe[2])+"%)"+d;te();document.getElementById("wall_"+
a+"_c1").style.background=W[0];document.getElementById("wall_"+a+"_c2").style.background=W[1]}function wd(a,c){ue();Dd();y.ca.style.transition="0.2s";document.getElementById(a+"Cont")&&(document.getElementById(a+"Cont").style.backgroundColor="#fff");"non"!=ne&&kd?ld(c):te();$c=0}
function Td(a,c){if(isFinite(c))document.getElementById("wall_"+a+"_"+pe).classList.remove("uButtonGreen"),document.getElementById("wall_"+a+"_"+pe).classList.add("uButtonGrey"),document.getElementById("wall_"+a+"_"+c).classList.remove("uButtonGrey"),document.getElementById("wall_"+a+"_"+c).classList.add("uButtonGreen"),pe=c,Zb(a);else if("Ch"===c)document.getElementById("wallSlidera4").style.opacity=document.getElementById("wall_"+a+"_"+c).checked?.25:1;else if("f"!=c){var d=le.slice(0,1);document.getElementById("wall_"+
a+"_"+d).classList.remove("uButtonGreen");document.getElementById("wall_"+a+"_"+d).classList.add("uButtonGrey");document.getElementById("wall_"+a+"_"+c).classList.remove("uButtonGrey");document.getElementById("wall_"+a+"_"+c).classList.add("uButtonGreen");"r"===c?document.getElementById("wall_"+a+"_f").classList.remove("uButtonDisabled"):document.getElementById("wall_"+a+"_f").classList.add("uButtonDisabled");"s"==c?(le="so",document.getElementById("wallSlidera4").style.opacity=document.getElementById("wallP").style.opacity=
.25,document.getElementById("wall_"+a+"_Ch").checked=!1,kd=0):("l"==c?(le="linear-gradient(",me="0deg, ",kd=0):"r"==c&&(le="radial-gradient(",me="circle at 90% 24%, "),document.getElementById("wallSlidera4").style.opacity=document.getElementById("wallP").style.opacity=1,document.getElementById("wall_"+a+"_f").classList.contains("uButtonGreen")&&(kd=1));te();ne="non";se(a);wd(a,{clientX:0,clientY:0})}else kd?(document.getElementById("wall_"+a+"_f").classList.remove("uButtonGreen"),document.getElementById("wall_"+
a+"_f").classList.add("uButtonGrey"),kd=0):(document.getElementById("wall_"+a+"_f").classList.remove("uButtonGrey"),document.getElementById("wall_"+a+"_f").classList.add("uButtonGreen"),kd=1);ue()}
function ac(){var a=document.getElementById("wallSliderb1"),c=a.parentNode.offsetWidth;a=(c-a.offsetWidth)/c;document.getElementById("wallSliderb1").style.left=100*oe[0]*a+"%";document.getElementById("wallSliderb2").style.left=100*oe[1]*a+"%";document.getElementById("wallSliderb3").style.left=100*oe[2]*a+"%";document.getElementById("wallSliderb4").style.left=100*oe[3]*a+"%"}
function te(){if("so"==le.slice(0,2))document.getElementById("Wallpaper").style.background=W[0];else{for(var a=le+me,c=0;c<W.length;c++)a+=W[c]+", ";a=a.slice(0,-2);document.getElementById("Wallpaper").style.background=a+")"}document.getElementById("cpy").style.color="";document.getElementsByClassName("ubLink")[0].style.color=""};window.Win_errorHandler=function(a){ya&&l("Error detected:<br><br>"+a.message+"<br><br>in file "+a.filename+"<br>in Line: "+a.lineno+", Columb: "+a.colno+'<br><button type="button" id="_errNt" class="uButtons uButtonGrey" style="margin-top:6px">Don&apos;t show errors</button>')};function Od(){ya=!ya;Jc("showErrors",ya);Db()}function Db(){var a="Notify on Errors";a=ya?'<span style="color:#0F0;">&#10004;</span>'+a:'<span style="color:#f00;">&#10008;</span>'+a;E[0].va[6].Text=a};
