/*
 Copyright © 2019 Stewart J. Robinson (AKA StewVed, Ved)
 To show your appreciation of my work, feel free to talk about, and link to my website(s)
 If you wish to copy/use code from [any part of] my website(s), please contact me. Thankyou.
 Adapted from my projects on GitHub, which in turn were adapted from the original loader for the webtop!
*/
function aa(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}}function ba(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):{next:aa(a)}}var ca="function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,d){a!=Array.prototype&&a!=Object.prototype&&(a[c]=d.value)},da="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;
function ea(a){if(a){for(var c=da,d=["Array","prototype","fill"],e=0;e<d.length-1;e++){var f=d[e];f in c||(c[f]={});c=c[f]}d=d[d.length-1];e=c[d];a=a(e);a!=e&&null!=a&&ca(c,d,{configurable:!0,writable:!0,value:a})}}ea(function(a){return a?a:function(a,d,e){var c=this.length||0;0>d&&(d=Math.max(0,c+d));if(null==e||e>c)e=c;e=Number(e);0>e&&(e=Math.max(0,c+e));for(d=Number(d||0);d<e;d++)this[d]=a;return this}});var fa=window.fVer,ha=[],ia=0,b=[],ja=0;fa?(ka(),la()):(ia=2,ma(1));
function ka(){"serviceWorker"in navigator&&navigator.serviceWorker.register("sw.js").then(function(a){a.active&&(ja="a");a.addEventListener("updatefound",function(){a.installing.addEventListener("statechange",function(a){"installed"===a.target.state?"a"===ja&&l("updating webtop..."):"activated"===a.target.state&&(ja="a"===ja?"u":"i",l("i"))})});"a"===ja&&a.update()}).catch(function(a){ja="e";console.log("ServiceWorker registration failed: ",a)})}
function la(){var a=[];ha=[];var c=fa?"190920.css":"all.css";a.push(c);c=fa?fa+"_1.js":"apps/aWebtop.js";a.push(c);a.push("images/imgSprites_160429.png");c=ba(a);for(var d=c.next();!d.done;d=c.next())ha.push(d.value.replace(/\./,"").replace(/\//,""));na(a[0],"style","","",0,ha[0]);oa(a[1],"script","","Core Webtop","",0);oa(a[2],"img","","Images","",0)}
function oa(a,c,d,e,f,g){var h=a.replace(/\./,"").replace(/\//,"");document.getElementById("Load")&&(document.getElementById("Load").innerHTML+='<div id="'+h+'C" class="loadC"><div id="'+h+'Pi" class="loadPi"></div><div id="'+h+'Pc" class="loadPc">'+e+" (...)</div></div>",pa());b[h]=[];b[h].text=e;b[h].time=performance.now();b[h].dd=performance.now();b[h].size=0;b[h].speed=2;b[h].total=0;b[h].fd=1;e=new XMLHttpRequest;e.open("GET",a,!0);"img"===c&&(e.responseType="blob");e.addEventListener("loadend",
function(){if(b[h].fd){var a=document.createElement(c);d?a.id=d:a.id=h;"img"===c?(window.URL.revokeObjectURL(a.src),a.src=window.URL.createObjectURL(new Blob([this.response],{type:"image/png"}))):a.innerHTML=this.responseText;document.head.appendChild(a);if(f)window[f](g)}},!1);e.addEventListener("error",function(){b[h].fd=0;na(a,c,d,f,g,h)},!1);e.addEventListener("progress",function(a){qa(a,h)},!1);e.send();b[h].frame=window.requestAnimationFrame(function(){ra(h)})}
function na(a,c,d,e,f,g){var h=document.getElementsByTagName("script")[0],m=document.createElement(c);"link"===c||"style"===c?(m=document.createElement("link"),m.type="text/css",m.rel="stylesheet",m.href=a,sa(m)):m.src=a;m.id=d?d+"l":g+"l";m.addEventListener("load",function(){if("l"===this.id.slice(-1)&&(this.id=this.id.slice(0,-1),e))window[e](f);ta()});h.parentNode.insertBefore(m,h)}
function sa(a){a.sheet?("l"===a.id.slice(-1)&&(a.id=a.id.slice(0,-1)),ta()):window.requestAnimationFrame(function(){sa(a)})}
function qa(a,c){if(document.getElementById(c+"Pi"))if(a.lengthComputable){b[c].Ic&&(b[c].Ic=0,window.clearInterval(b[c].Yc),b[c].Yc=null);document.getElementById(c+"Pi").classList.remove("loadVV");var d=performance.now();b[c].speed=(a.loaded-b[c].size)/(d-b[c].time);b[c].time=d;b[c].size=a.loaded;b[c].total||(b[c].total=a.total);a=a.loaded/a.total*100;document.getElementById(c+"Pi").style.width=a+"%";document.getElementById(c+"Pc").innerHTML=b[c].text+" ("+a.toFixed(1)+"%)"}else b[c].Ic||(b[c].Ic=
1,b[c].Yc=window.setInterval(function(){ta()},500)),document.getElementById(c+"Pi").classList.add("loadVV")}
function ra(a){if(document.getElementById(a+"Pi")){var c=parseFloat(document.getElementById(a+"Pi").style.width||0);if(100>c){if(b[a].total){var d=performance.now();c+=parseFloat(parseFloat(b[a].speed*(d-b[a].dd))/b[a].total*100);document.getElementById(a+"Pi").style.width=c+"%";document.getElementById(a+"Pc").innerHTML=b[a].text+" ("+c.toFixed(1)+"%)"}else document.getElementById(a+"Pc").innerHTML=b[a].text+" (...)",document.getElementById(a+"Pi").classList.add("loadVV");b[a].dd=d;b[a].frame=window.requestAnimationFrame(function(){ra(a)})}else document.getElementById(a+
"C").style.transition="1s",document.getElementById(a+"C").style.opacity=0,window.setTimeout(function(){document.getElementById(a+"C")&&(document.getElementById(a+"C").parentNode.removeChild(document.getElementById(a+"C")),pa());ta()},1E3)}}
function ta(){if(document.getElementById("Load")){for(var a=ba(ha),c=a.next();!c.done;c=a.next())if(!document.getElementById(c.value))return;2==ia?(ia=0,la()):ia||(ia=1,document.getElementById("Load").parentNode.removeChild(document.getElementById("Load")),document.getElementById(ha[2]).id="spriteMain",ua())}}function pa(){document.getElementById("Load").style.top=(window.innerHeight-document.getElementById("Load").offsetHeight)/2+"px"}
function ma(a){1===a?(ha="aWinStorage aWinIndex aWinLaunchers aWinWallpaper aWinDEChooser aWinEvents aWinzErrorHandler aWinThemeChooser aWinToolTip".split(" "),ha.push()):2===a&&(ha="bb bp calsPerGrams dialogue dm feedBack jsCavern saveVsLoan screen iFramedApp soundGenerator tAT tt video wc wordSearch".split(" "));a=ba(ha);for(var c=a.next();!c.done;c=a.next())c=c.value,na("apps/"+c+".js","script","","",0,c)}
function l(a){if(!document.getElementById("Wallpaper"))window.setTimeout(function(){l(a)},1E3);else if(a){var c=document.createElement("div");c.id="NotyCont"+n.length;c.className="notifier "+t[u].fb;var d='<img id="notifyClose'+n.length+'" class="Button ButtonClo" style="background-image:url('+va.src+');position:absolute;left:0px;top:0px;margin:0;" '+w+">";a=a.replace(/ id="_/gi,' id="'+n.length+"_");c.innerHTML=d+a;document.getElementById("Wallpaper").appendChild(c);d=document.getElementById("NotyCont"+
n.length);if("RizzsXmasTimer"===a.slice(144,158)){d.style.border="4px solid rgb(255,0,0)";d.style.width=d.offsetWidth+32+"px";var e=new Date((new Date).getFullYear(),11,25);new Date>e&&e.setFullYear(e.getFullYear()+1);document.getElementById("RizzsXmasTimer").innerHTML=wa(e)}e=document.getElementById("Wallpaper").offsetWidth-d.offsetWidth-4;0>e&&(e=0,d.style.width=document.getElementById("Wallpaper").offsetWidth+"px");d.style.left=e+"px";n.push(n.length);xa();c.style.opacity=.9}};
