/*
 Copyright © 2023 Stewart J. Robinson (AKA StewVed, Ved)
 To show your appreciation of my work, feel free to talk about, and link to my website(s)...
 If you wish to copy/use code from [any part of] my website(s), please contact me. Thankyou.
*/
var he=[8,16,32,64,128,256,512,1024,2048,4096,8192,16384];
window.bb_Init=function(a){C[a].Window.I="Bencher";C[a].g={Z:"",aa:"",ya:"",Oa:"",Va:0,kc:0,ja:"",ac:"",B:"",$:"",jb:0,sa:256,la:3,qb:!1,dc:new Image};var b=[],d;for(d in he){var e=Number(d);b[parseFloat(d)]={Text:he[e],j:function(){},Event:[a+"_"+d+"_gMenu_1","mouseup",function(){C[a].g.sa=he[parseInt(this.id.split("_")[1],10)];C[a].g.qb=!0}]}}C[a].ea=[{Text:"Fullscreen",j:function(){V(a)}}];C[a].D=[{Text:"Renderer",v:[{Text:"HTML: div",j:function(){ie(a,0)}},{Text:"HTML: img",j:function(){ie(a,
1)}},{Text:"canvas: draw",j:function(){ie(a,2)}},{Text:"canvas: img",j:function(){ie(a,3)}}]},{Text:"Amount",v:b},{Text:"Fullscreen",v:[{Text:"Fullscreen",j:function(){V(a)}}]}];C[a].g.dc.src=t.src;document.getElementById(a+"Box").style.width=Math.round(.8*Q)+"px";C[a].Window.o=document.getElementById(a+"Cont").offsetWidth;document.getElementById(a+"Box").style.height=Math.round(.5625*C[a].Window.o)+"px";C[a].Window.s=document.getElementById(a+"Cont").offsetHeight;C[a].Window.G=Math.floor(C[a].Window.o/
3);C[a].Window.F=Math.floor(C[a].Window.s/3);document.getElementById(a+"Box").style.background="radial-gradient(#999, #222)";Mb(a);je(a)};
function je(a){C[a].g.qb=!1;window.clearInterval(C[a].g.Va);C[a].g.B=[];C[a].g.Z=document.getElementById(a+"Cont").offsetWidth;C[a].g.aa=document.getElementById(a+"Cont").offsetHeight;for(var b=C[a].g.Z/2-8,d=C[a].g.aa/2-8,e,f=0;f<C[a].g.sa;f++)e=(36E3*Math.random()+1)/100,C[a].g.B[f]={Ha:e,V:b,T:d,Element:""};document.getElementById(a+"_bb_gameArea")&&(document.getElementById(a+"_bb_gameArea").parentNode.removeChild(document.getElementById(a+"_bb_gameArea")),document.getElementById(a+"_bb_score").parentNode.removeChild(document.getElementById(a+
"_bb_score")));b=2>C[a].g.la?"div":"canvas";d="<"+b+' id="'+a+'_bb_gameArea">';if(0==C[a].g.la)for(e=0;e<C[a].g.sa;e++)d+='<div id="'+a+"_"+e+'" class="bb_circleGraded"></div>';else if(1==C[a].g.la)for(e=0;e<C[a].g.sa;e++)d+='<img id="'+a+"_"+e+'" class="bb_imgCircle" '+B+' -263px -8px;" '+u+">";d=d+("</"+b+'><div id="')+(a+'_bb_score" class="bb_score">0 FPS</div>');C[a].g.Oa=(new Date).getTime();document.getElementById(a+"Box").innerHTML=d;document.getElementById(a+"Cont").innerHTML+='<div id="'+
a+'FS" class="fsButton">&#9974;</div>';C[a].g.ja=document.getElementById(a+"_bb_gameArea");1<C[a].g.la?(C[a].g.$=C[a].g.ja.getContext("2d"),C[a].g.ja.width=C[a].g.Z,C[a].g.ja.height=C[a].g.aa):(C[a].g.ja.style.width=C[a].g.Z+"px",C[a].g.ja.style.height=C[a].g.aa+"px");C[a].g.ac=document.getElementById(a+"_bb_score");for(e=0;e<C[a].g.sa;e++)C[a].g.B[e].Element=document.getElementById(a+"_"+e);b="Browser Benchmarker - ";0==C[a].g.la?b+="HTML: div":1==C[a].g.la?b+="HTML: img":2==C[a].g.la?b+="canvas:draw":
3==C[a].g.la&&(b+="canvas:image");document.getElementById(a+"Title").innerHTML=b+" with "+C[a].g.sa+" elements";C[a].g.Oa=C[a].g.yb=(new Date).getTime();C[a].g.yb+=1E3;ke(a)}function ie(a,b){C[a].g.la=b;C[a].g.qb=!0}function le(a){C[a].g.ac.innerHTML=0==C[a].g.jb?"Calculating...":C[a].g.jb+" FPS";C[a].g.yb=C[a].g.ya+1E3;C[a].g.jb=0}
function ke(a){if(C[a])if(C[a].g.qb)je(a);else{C[a].g.ya=(new Date).getTime();C[a].g.ya>C[a].g.yb&&le(a);var b=1E3/(C[a].g.ya-C[a].g.Oa);if(0!=b){C[a].g.Oa=C[a].g.ya;b=Number(500/b);for(var d=0;d<C[a].g.sa;d++)C[a].g.B[d].V+=b*Math.sin(C[a].g.B[d].Ha),C[a].g.B[d].T-=b*Math.cos(C[a].g.B[d].Ha),me(d,a);2>C[a].g.la?ne(a):2==C[a].g.la?oe(a):3==C[a].g.la&&pe(a);C[a].g.jb++;C[a].g.Va=C[a].g.kc?window.requestAnimationFrame(function(){ke(a)}):window.setTimeout(function(){ke(a)},0)}}}
function me(a,b){var d=Number((C[b].g.B[a].Ha/Math.PI*180).toFixed(2));0>C[b].g.B[a].V&&(C[b].g.B[a].V=-1*C[b].g.B[a].V,C[b].g.B[a].Ha=(360-d)*Math.PI/180);C[b].g.B[a].V>C[b].g.Z-16&&(C[b].g.B[a].V=C[b].g.Z-16+(C[b].g.Z-16-C[b].g.B[a].V),C[b].g.B[a].Ha=(360-d)*Math.PI/180);0>C[b].g.B[a].T&&(C[b].g.B[a].T=-1*C[b].g.B[a].T,C[b].g.B[a].Ha=0<d&&90>d?(180-d)*Math.PI/180:(270-d+270)*Math.PI/180);C[b].g.B[a].T>C[b].g.aa-16&&(C[b].g.B[a].T=C[b].g.aa-16+(C[b].g.aa-16-C[b].g.B[a].T),C[b].g.B[a].Ha=90<d&&180>
d?(180-d)*Math.PI/180:(180-d+360)*Math.PI/180)}function oe(a){C[a].g.$.clearRect(0,0,C[a].g.ja.width,C[a].g.ja.height);for(var b,d=0;d<C[a].g.sa;d++)b=C[a].g.$.createRadialGradient(C[a].g.B[d].V-8,C[a].g.B[d].T-8,2,C[a].g.B[d].V-8,C[a].g.B[d].T-8,14),b.addColorStop(0,"white"),b.addColorStop(1,"black"),C[a].g.$.fillStyle=b,C[a].g.$.beginPath(),C[a].g.$.arc(C[a].g.B[d].V,C[a].g.B[d].T,8,0,2*Math.PI,!0),C[a].g.$.closePath(),C[a].g.$.fillStyle=b,C[a].g.$.fill()}
function pe(a){C[a].g.$.clearRect(0,0,C[a].g.ja.width,C[a].g.ja.height);for(var b=0;b<C[a].g.sa;b++)C[a].g.$.drawImage(C[a].g.dc,263,8,16,16,C[a].g.B[b].V,C[a].g.B[b].T,16,16)}function ne(a){for(var b=0;b<C[a].g.sa;b++)C[a].g.B[b].Element.style.left=C[a].g.B[b].V+"px",C[a].g.B[b].Element.style.top=C[a].g.B[b].T+"px"};var Rc=[100,250,500,1E3,2500],qe=[{x:0,y:22},{x:65,y:22},{x:0,y:41},{x:65,y:41}];
window.bp_Init=function(a){var b=C[a].Window;b.o=640;b.s=360;b.G=213;b.F=120;b.I="GProto";b.S=1;b.ca=1;C[a].g={Ua:0,tb:0,Z:0,aa:0,h:[],L:[],i:[],pa:0,mc:[],Va:0,ya:0,Oa:new Date,xb:new Image,$:"",U:0,Ta:0,Pb:1};C[a].ea=[{Text:"Reset",j:function(){re(a)}},{Text:"Fullscreen",j:function(){V(a)}}];C[a].D=[{Text:"Speed",v:[{Text:"Slow",j:function(){se(a,0)}},{Text:"Medium",j:function(){se(a,1)}},{Text:"Fast",j:function(){se(a,2)}},{Text:"Warp Speed, Mr Sulu! -Captain Kirk",j:function(){se(a,3)}},{Text:"Don&apos;t blink. Don&apos;t even blink. Blink and you&apos;re dead.<br>They are fast, faster than you could believe.<br>Don&apos;t turn your back, don&apos;t look away, and don&apos;t blink.<br>Good luck. -the Doctor",
j:function(){se(a,4)}}]},{Text:"Fullscreen",v:[{Text:"Fullscreen",j:function(){V(a)}}]},{Text:"Help",v:[{Text:"About"},{Text:"Whats New"}]}];C[a].g.xb.src="images/bpSprites.png";document.getElementById(a+"Box").style.background="#444";document.getElementById(a+"Box").innerHTML='<canvas id="'+a+'_BPgameArea" class="bb_gameArea"></canvas>';document.getElementById(a+"Cont").innerHTML+='<div id="'+a+'FS" class="fsButton">&#9974;</div>';C[a].g.Ta=document.getElementById(a+"_BPgameArea");C[a].g.$=C[a].g.Ta.getContext("2d");
C[a].g.Ua=280;C[a].g.h.width=C[a].g.h.height=16;te(a);ue(a);ve(a)};function te(a){for(var b=C[a].g.pa=0;90>=b;b+=10)for(var d=1;10>=d;d++){C[a].g.i[b+d]=[];if(0==b||10==b)C[a].g.i[b+d].block=0;else if(20==b||30==b)C[a].g.i[b+d].block=1;else if(40==b||50==b)C[a].g.i[b+d].block=3;else if(60==b||70==b)C[a].g.i[b+d].block=2;else if(80==b||90==b)C[a].g.i[b+d].block=0;C[a].g.i[b+d].ic=64*(d-1);C[a].g.i[b+d].jc=b/10*18;C[a].g.i[b+d].width=64;C[a].g.i[b+d].height=18;C[a].g.i[b+d].show=!0;C[a].g.pa++}}
function ue(a){C[a].Window.o=640;C[a].Window.s=360;Wb(a)}
function Wb(a){var b=document.getElementById(a+"Box"),d=b.offsetHeight;C[a].g.U=d/C[a].Window.s;var e=Math.round(C[a].Window.o*C[a].g.U);e>b.offsetWidth&&(C[a].g.U=b.offsetWidth/C[a].Window.o,e=Math.round(C[a].Window.o*C[a].g.U));d=Math.round(C[a].Window.s*C[a].g.U);var f=C[a].g.Z;b=C[a].g.aa;C[a].g.Ta.width=C[a].g.Z=e;C[a].g.Ta.height=C[a].g.aa=d;d=C[a].g.Z/f;e=C[a].g.aa/b;C[a].g.L.width=80*C[a].g.U;C[a].g.L.left=C[a].g.Z/2-C[a].g.L.width/2;C[a].g.L.height=20*C[a].g.U;C[a].g.L.top=C[a].g.aa-C[a].g.L.height-
2;C[a].g.h.width=C[a].g.h.height=16*C[a].g.U;!C[a].g.h.da&&!C[a].g.h.qa||0==C[a].g.h.da&&0==C[a].g.h.qa?(C[a].g.h.left=C[a].g.h.ha=C[a].g.L.left+(C[a].g.L.width/2-C[a].g.h.width/2),C[a].g.h.top=C[a].g.h.ia=C[a].g.L.top-C[a].g.h.height,C[a].g.h.speed=0,C[a].g.h.da=0,C[a].g.h.qa=0):(C[a].g.h.ha=C[a].g.h.left,C[a].g.h.ia=C[a].g.h.top,C[a].g.h.left=C[a].g.h.left*d,C[a].g.h.top=C[a].g.h.top*e);for(var g in C[a].g.i)C[a].g.i[g].left=C[a].g.i[g].ic*C[a].g.U,C[a].g.i[g].top=C[a].g.i[g].jc*C[a].g.U,C[a].g.i[g].width=
64*C[a].g.U,C[a].g.i[g].height=18*C[a].g.U}function se(a,b){C[a].g.Pb=parseInt(b,10)}function ve(a){C[a]&&(C[a].g.ya=Date.now(),C[a].g.Wb=(C[a].g.ya-C[a].g.Oa)/1E3,C[a].g.Oa=C[a].g.ya,0==C[a].g.Ja&&(C[a].g.h.ha=C[a].g.h.left,C[a].g.h.ia=C[a].g.h.top,C[a].g.h.left+=C[a].g.h.da*C[a].g.U*C[a].g.Wb,C[a].g.h.top-=C[a].g.h.qa*C[a].g.U*C[a].g.Wb,we(a),xe(a)),ye(a),C[a].g.Va=window.requestAnimationFrame(function(){ve(a)}))}
function we(a){var b=C[a].g.h.top-C[a].g.h.ia,d=C[a].g.h.left-C[a].g.h.ha;if(0>b){b=-b;var e=!0}if(0>d){d=-d;var f=!0}if(b>=d){var g=Math.floor(b);d*=1/b;b=1}else g=Math.floor(d),b*=1/d,d=1;0==g&&(g=1);e&&(b=-b);f&&(d=-d);e=8>g?g:8;for(f=1;f<=g;){ye(a);var l=Math.ceil(C[a].g.h.ia/(18*C[a].g.U));var m=Math.ceil((C[a].g.h.ia+C[a].g.h.height)/(18*C[a].g.U));var p=Math.ceil(C[a].g.h.ha/(64*C[a].g.U));var w=Math.ceil((C[a].g.h.ha+C[a].g.h.width)/(64*C[a].g.U));var M=10*(l-1)+p;l=10*(l-1)+w;p=10*(m-1)+
p;w=10*(m-1)+w;var Aa=[];C[a].g.i[M]&&C[a].g.i[M].show&&Aa.push(M);C[a].g.i[l]&&C[a].g.i[l].show&&M!=l&&Aa.push(l);C[a].g.i[p]&&C[a].g.i[p].show&&p!=M&&p!=l&&Aa.push(p);C[a].g.i[w]&&C[a].g.i[w].show&&w!=p&&w!=M&&w!=l&&Aa.push(w);for(var xb in Aa){var n=Aa[parseFloat(xb)];if(C[a].g.i[n].show){p=C[a].g.h.ha;w=C[a].g.h.ha+C[a].g.h.width;l=C[a].g.h.ia;m=C[a].g.h.ia+C[a].g.h.height;M=C[a].g.i[n].left;var Ja=C[a].g.i[n].left+C[a].g.i[n].width;var Ka=C[a].g.i[n].top;var La=C[a].g.i[n].top+C[a].g.i[n].height;
if((p>M&&p<Ja||w>M&&w<Ja)&&(l>Ka&&l<La||m>Ka&&m<La)){for(;(p>M&&p<Ja||w>M&&w<Ja)&&(l>Ka&&l<La||m>Ka&&m<La);)l-=b,m-=b,p-=d,w-=d,C[a].g.h.ia=l,C[a].g.h.ha=p;C[a].g.i[n].show=!1;C[a].g.pa--;0<d&&w+1>M&&w-1<M?(C[a].g.i[n-10]&&C[a].g.i[n-10].show&&C[a].g.i[n-10].left==C[a].g.i[n].left&&l+1>C[a].g.i[n-10].left&&l-1<C[a].g.i[n-10].left+C[a].g.i[n-10].width&&(C[a].g.i[n-10].show=!1,C[a].g.pa--),C[a].g.i[n+10]&&C[a].g.i[n+10].show&&C[a].g.i[n+10].left==C[a].g.i[n].left&&m+1>C[a].g.i[n+10].left&&m-1<C[a].g.i[n+
10].left+C[a].g.i[n+10].width&&(C[a].g.i[n+10].show=!1,C[a].g.pa--),C[a].g.h.da=-C[a].g.h.da,C[a].g.h.ha=M-C[a].g.h.width,C[a].g.h.left-=C[a].g.h.left-C[a].g.h.ha):0>d&&p+1>Ja&&p-1<Ja&&(C[a].g.i[n-10]&&C[a].g.i[n-10].show&&C[a].g.i[n-10].left==C[a].g.i[n].left&&l+1>C[a].g.i[n-10].left&&l-1<C[a].g.i[n-10].left+C[a].g.i[n-10].width&&(C[a].g.i[n-10].show=!1,C[a].g.pa--),C[a].g.i[n+10]&&C[a].g.i[n+10].show&&C[a].g.i[n+10].left==C[a].g.i[n].left&&m+1>C[a].g.i[n+10].left&&m-1<C[a].g.i[n+10].left+C[a].g.i[n+
10].width&&(C[a].g.i[n+10].show=!1,C[a].g.pa--),C[a].g.h.da=-C[a].g.h.da,C[a].g.h.ha=Ja,C[a].g.h.left+=C[a].g.h.ha-C[a].g.h.left);0>b&&l+1>La&&l-1<La?(C[a].g.i[n-1]&&C[a].g.i[n-1].show&&C[a].g.i[n-1].top==C[a].g.i[n].top&&p+1>C[a].g.i[n-1].left&&p-1<C[a].g.i[n-1].left+C[a].g.i[n-1].width&&(C[a].g.i[n-1].show=!1,C[a].g.pa--),C[a].g.i[n+1]&&C[a].g.i[n+1].show&&C[a].g.i[n+1].top==C[a].g.i[n].top&&w+1>C[a].g.i[n+1].left&&w-1<C[a].g.i[n+1].left+C[a].g.i[n+1].width&&(C[a].g.i[n+1].show=!1,C[a].g.pa--),
C[a].g.h.qa=-C[a].g.h.qa,C[a].g.h.ia=La,C[a].g.h.top+=C[a].g.h.ia-C[a].g.h.top):0<b&&m+1>Ka&&m-1<Ka&&(C[a].g.i[n-1]&&C[a].g.i[n-1].show&&C[a].g.i[n-1].top==C[a].g.i[n].top&&p+1>C[a].g.i[n-1].left&&p-1<C[a].g.i[n-1].left+C[a].g.i[n-1].width&&(C[a].g.i[n-1].show=!1,C[a].g.pa--),C[a].g.i[n+1]&&C[a].g.i[n+1].show&&C[a].g.i[n+1].top==C[a].g.i[n].top&&w+1>C[a].g.i[n+1].left&&w-1<C[a].g.i[n+1].left+C[a].g.i[n+1].width&&(C[a].g.i[n+1].show=!1,C[a].g.pa--),C[a].g.h.qa=-C[a].g.h.qa,C[a].g.h.ia=Ka-C[a].g.h.height,
C[a].g.h.top-=C[a].g.h.top-C[a].g.h.ia);var Td=!0;break}}}if(Td)break;else f+=e,f>g&&f-e!=g&&(f=g),C[a].g.h.ia+=b*e,C[a].g.h.ha+=d*e}Td&&(Hb(1900,100),xe(a),we(a));0==C[a].g.pa&&re(a)}
function xe(a){if(0>=C[a].g.h.left){C[a].g.h.left=-1*C[a].g.h.left;C[a].g.h.da=-C[a].g.h.da;var b=1}C[a].g.h.left+C[a].g.h.width>=C[a].g.Z&&(C[a].g.h.left=C[a].g.Z-C[a].g.h.width+(C[a].g.Z-C[a].g.h.width-C[a].g.h.left),C[a].g.h.da=-C[a].g.h.da,b=1);0>=C[a].g.h.top&&(C[a].g.h.top=-1*C[a].g.h.top,C[a].g.h.qa=-C[a].g.h.qa,b=1);b&&Hb(750,100);if(C[a].g.h.top+C[a].g.h.height>C[a].g.L.top&&0!=C[a].g.h.speed){b=C[a].g.L.left/C[a].g.U+C[a].g.L.width/C[a].g.U/2;var d=C[a].g.h.left/C[a].g.U+C[a].g.h.width/
C[a].g.U/2;C[a].g.h.left>C[a].g.L.left-C[a].g.h.width&&C[a].g.h.left<C[a].g.L.left+C[a].g.L.width?(C[a].g.mb+=.5,C[a].g.h.speed=Rc[C[a].g.Pb]+C[a].g.mb,d>=b?(C[a].g.h.da=(d-b)/50*C[a].g.h.speed,b=C[a].g.h.da/2):(C[a].g.h.da=-((b-d)/50*C[a].g.h.speed),b=-C[a].g.h.da/2),C[a].g.h.qa=C[a].g.h.speed-b,C[a].g.h.top-=C[a].g.h.top-(C[a].g.L.top-C[a].g.h.height),Hb(500,100)):C[a].g.h.top>=C[a].g.aa-C[a].g.h.width&&re(a)}}
function ye(a){if(C[a]){C[a].g.$.clearRect(0,0,C[a].g.Ta.width,C[a].g.Ta.height);C[a].g.$.drawImage(C[a].g.xb,0,0,16,16,C[a].g.h.left,C[a].g.h.top,C[a].g.h.width,C[a].g.h.height);C[a].g.$.drawImage(C[a].g.xb,18,0,80,20,C[a].g.L.left,C[a].g.L.top,C[a].g.L.width,C[a].g.L.height);for(var b in C[a].g.i)if(C[a].g.i[b].show){var d=C[a].g.i[b].block;C[a].g.$.drawImage(C[a].g.xb,qe[d].x,qe[d].y,64,18,C[a].g.i[b].left,C[a].g.i[b].top,C[a].g.i[b].width,C[a].g.i[b].height)}}}
function re(a){C[a].g.h.left=C[a].g.L.left+C[a].g.L.width/2-C[a].g.h.width/2;C[a].g.h.top=C[a].g.L.top-C[a].g.h.height;C[a].g.h.speed=0;C[a].g.h.da=0;C[a].g.h.qa=0;C[a].g.Ja=!0;Hb(250,300);te(a);Wb(a)};window.cpw_Init=function(a){var b=C[a].Window;b.I="CalsPerGrams";b.S=1;b.ca=1;C[a].D=[{Text:"Help",v:[{Text:"About",j:function(){U("CalsPerGrams-Calories per grams calculator_100")}}]}];b=document.getElementById(a+"Cont");var d=document.getElementById(a+"Box");ze(a);C[a].Window.o=b.offsetWidth;C[a].Window.s=b.offsetHeight;C[a].Window.G=Math.floor(.66*C[a].Window.o);C[a].Window.F=Math.floor(.66*C[a].Window.s);a=b.offsetWidth/b.offsetHeight;d.style.width=Math.round(.8*Q)+"px";d.style.height=Math.round(b.offsetWidth/
a)+"px"};
function ze(a){var b=document.getElementById(a+"Box");b.style.backgroundColor="#fff";b.style.margin="4px";b.innerHTML='<span style="float:left;padding:8px 0px 0px 4px;width:calc(100% - 4px);text-align:center;">Energy per <input type="text" id="cpw_'+a+'_cpG" class="editEnable" style="margin:0px 0px 6px 0px;padding:0px;text-align:center;background:linear-gradient(#fff, #eee);border:1px solid #000;box-sizing:border-box;" size="2" value="100">g:<br><span id="cpw_'+a+'_cpD">kcals: </span><input type="text" id="cpw_'+a+
'_cpC" class="editEnable" style="margin:0px 0px 6px 0px;padding:0px;text-align:center;background:linear-gradient(#fff, #eee);border:1px solid #000;box-sizing:border-box;" size="2" value="0"></span><div style="width:calc(45% - 2px);margin:0px;padding:4px;text-align:center;overflow:hidden;box-sizing:border-box;float:left;clear:both;">Target<br>Calories<input type="text" id="cpw_'+a+'_cpc" class="editEnable" style="clear:both;float:left;margin:0px;padding:0px;width:100%;text-align:center;background:linear-gradient(#fff, #eee);border:1px solid #000;box-sizing:border-box;" size="2" value="0"></div><div style="width:calc(45% - 2px);margin:0px;padding:4px;text-align:center;overflow:hidden;box-sizing:border-box;float:right;">Weight<br>(grams)<input type="text" id="cpw_'+
a+'_cpg" class="editEnable" style="clear:both;float:left;margin:0px;padding:0px;width:100%;text-align:center;background:linear-gradient(#fff, #eee);border:1px solid #000;box-sizing:border-box;" size="2" value="0"></div>';document.getElementById("cpw_"+a+"_cpC").addEventListener("keyup",function(){Ae(a)},!1);document.getElementById("cpw_"+a+"_cpG").addEventListener("keyup",function(){Ae(a)},!1);document.getElementById("cpw_"+a+"_cpc").addEventListener("keyup",function(){var d=parseFloat(document.getElementById("cpw_"+
a+"_cpC").value),e=parseFloat(document.getElementById("cpw_"+a+"_cpG").value),f=parseFloat(document.getElementById("cpw_"+a+"_cpc").value);isFinite(d)&&isFinite(e)&&isFinite(f)?document.getElementById("cpw_"+a+"_cpg").value=(e/d*f).toFixed(1):document.getElementById("cpw_"+a+"_cpg").value=0},!1);document.getElementById("cpw_"+a+"_cpg").addEventListener("keyup",function(){Ae(a)},!1);b.style.width=b.offsetWidth+"px";b.style.height=.5625*b.offsetWidth+"px";Yb(b);Zb(b);document.getElementById("cpw_"+
a+"_cpG");document.getElementById("cpw_"+a+"_cpG");document.getElementById("cpw_"+a+"_cpC").style.left=parseFloat(document.getElementById("cpw_"+a+"_cpG").style.left)+"px";document.getElementById("cpw_"+a+"_cpD").style.left=parseFloat(document.getElementById("cpw_"+a+"_cpG").style.left)-document.getElementById("cpw_"+a+"_cpD").offsetWidth+"px";document.getElementById("cpw_"+a+"_cpC").style.position=document.getElementById("cpw_"+a+"_cpD").style.position="absolute"}
function Ae(a){var b=parseFloat(document.getElementById("cpw_"+a+"_cpC").value),d=parseFloat(document.getElementById("cpw_"+a+"_cpG").value),e=parseFloat(document.getElementById("cpw_"+a+"_cpg").value);isFinite(b)&&isFinite(d)&&isFinite(e)?document.getElementById("cpw_"+a+"_cpc").value=Math.round(b/d*e):document.getElementById("cpw_"+a+"_cpc").value=0};window.Win_createDialogueInit=function(a){window.SiteCL?(Be(a),lc(a)):(document.getElementById("Loader"+a)||mc(a),window.setTimeout(function(){window.Win_createDialogueInit(a)},500))};
function Be(a){var b=C[a].Window;b.I="Dialog";b.name="Hmm";b=document.getElementById(a+"Box");b.style.backgroundColor="#fff";b.style.width=.9*Q+"px";b.style.height=.88*(document.getElementById("Wallpaper").offsetHeight-document.getElementById(a+"TopBar").offsetHeight-document.getElementById("UnityPanel").offsetHeight)+"px";C[a].Window.o=document.getElementById(a+"Cont").offsetWidth;C[a].Window.s=document.getElementById(a+"Cont").offsetHeight;C[a].Window.G=C[a].Window.o/4;C[a].Window.F=C[a].Window.s/
4;document.getElementById(a+"Cont");b=document.getElementById(a+"Box");var d=C[a].Window.Qb.split("-");if("Xmas"==d[0])Gb();else{if(0<d[0].indexOf("CL"))var e=d[1]+" ChangeLog";else if("fullscreen"===d[0].slice(0,10)){e="Launch Fullscreen?";var f=d[1].slice(17);window.dialogueFullScreen='<p style="margin:4px;">Would you like to launch this fullscreen?</p><button id="'+a+"_fullYes_"+f+'" class="uButtons uButtonGrey" type="button " style="font-size:2em;width:30%;margin:4px;float:left;">Yes</button><button id="'+
a+"_fullNo_"+f+'" class="uButtons uButtonGrey" type="button" style="font-size:2em;width:30%;margin:4px;float:right;">No</button>';d[0]="dialogueFullScreen";b.style.textAlign="center";C[a].Window.Fa=!0}else"msgBox"===d[0]?(e=d[2],d[0]=d[1],b.style.textAlign="center",C[a].Window.Fa=!0):""==d[0]||"stewvedsWebtop"==d[0]||"L"==d[0]||"eL"==d[0]||"eN"==d[0]||"eC"==d[0]?(e="About StewVed&apos;s Webtop",d[0]="stewvedsWebtop"):e="About "+d[1];document.getElementById(a+"Title").innerHTML=e;"http"===d[0].slice(0,
4)?b.innerHTML='<iframe style="border:0;width:100%;height:100%;" src="'+d[0]+'"></iframe>':b.innerHTML=window[d[0]];Ce(b);b.classList.add("letScroll");b.style.padding="4px";b.style.width="";b.style.height="";Mb(a);nc(a);oc(a);C[a].Window.o=document.getElementById(a+"Cont").offsetWidth;C[a].Window.s=document.getElementById(a+"Cont").offsetHeight;C[a].Window.G=Math.floor(C[a].Window.o/4);C[a].Window.F=Math.floor(C[a].Window.s/4);document.getElementById("cpContact")&&(document.getElementById("cpContact").id=
a+"_cpContact",C[a].Sb={cpContact:C[0].Sb.cpContact})}}function Ce(a){a=a.children;for(var b=0;b<a.length;b++)"br"!=a[b].nodeName.toLowerCase()&&a[b].classList.add("letScroll"),"a"==a[b].nodeName.toLowerCase()&&(a[b].style.color="#000"),0<a[b].childElementCount&&Ce(a[b])};var De="Your&nbsp;Job Partner&apos;s&nbsp;Job Benefits Other&nbsp;Income Shopping Bills Car Other&nbsp;Out".split(" ");window.dm_Init=function(a){a==parseInt(a,10)?Ee(a):Fe(a)};
function Ee(a){var b=C[a].Window;b.s=332;b.G=286;b.F=256;b.I="DM";b.name="Dosh Manager";b.S=1;b.ca=1;C[a].ea=[{Text:"About",j:function(){U("DoshManager-Dosh Manager_100")}},{Text:"Whats New",j:function(){U("DoshManagerCL-Dosh Manager_100")}}];C[a].D=[{Text:"File",v:[{Text:"Example figures",j:function(){Ge(a,"example")}},{Text:"Clear figures",j:function(){Ge(a,"new")}},{Text:"Download Dosh Manager<br>For Desktop (.NET)",j:function(){Db("apps/DoshManager.exe")}}]},{Text:"Help",v:[{Text:"About",j:function(){U("DoshManager-Dosh Manager_100")}},
{Text:"Whats New",j:function(){U("DoshManagerCL-Dosh Manager_100")}}]}];He(a);Ie(a);document.getElementById(a+"Box").style.width=.8*Q+"px";Rb(a);Je(a)}
function Je(a){for(var b=Qa[document.getElementById(parseInt(a,10)+"cbTotalTime").selectedIndex],d=0,e=0;4>e;e++)d+=parseFloat(C[a].Ba[e])/b,document.getElementById(a+"dm_"+e+"t").value=(C[a].Ba[e]/b).toFixed(2);document.getElementById(a+"tInTxt").value=d.toFixed(2);var f=0;for(e=4;8>e;e++)f+=parseFloat(C[a].Ba[e])/b,document.getElementById(a+"dm_"+e+"t").value=(C[a].Ba[e]/b).toFixed(2);document.getElementById(a+"tOutTxt").value=f.toFixed(2);f<=d?document.getElementById(a+"gainLoss").innerHTML="gaining "+
(d-f).toFixed(2):document.getElementById(a+"gainLoss").innerHTML="losing "+(f-d).toFixed(2);b=""+(C[a].Ba.join(O)+P);for(d=0;d<C[a].g.length;d++)b+=C[a].g[d].join(O)+P;Cc("DoshManager",b)}
function Ke(a){for(var b=0,d,e=0;e<C[a].nb;e++)d=parseFloat(document.getElementById(a+"dm_"+e+"num").value*Qa[document.getElementById(a+"dm_"+e+"per").selectedIndex]),isFinite(d)&&(b+=d);C[a].total=b.toFixed(2);b/=Qa[document.getElementById(parseInt(a,10)+"cbTotalTime").selectedIndex];document.getElementById(a+"WL").innerHTML=document.getElementById(parseInt(a,10)+"cbTotalTime").value+" total: "+b.toFixed(2)}
function Ge(a,b){"example"==b?(C[a].Ba="10590.57 13043.54 993.60 45.00 6335.71 9436.09 1037.14 1175.89".split(" "),C[a].g=["Main Job;150.00;0;50 a week;2607.14;6;Online Surveys;13.50;3".split(";"),"Full-Time (39h@7.20);250.15;0;(Edit for another...);0.00;0;(Edit for another...);0.00;0".split(";"),"Tax Credits;0.00;0;Child Benefit;82.80;3;JSA/ESA/ISA;0.00;0;Housing Benefit;0.00;0;Council Tax Rebate;0.00;0;(Edit for another...);0.00;0".split(";"),"Interest;0.00;0;State Pension;0.00;0;Pension #1;0.00;0;Pension #2;0.00;0;Dividends;45.00;6;(Edit for another...);0.00;0;(Edit for another...);0.00;0;(Edit for another...);0.00;0".split(";"),
"Main Shop;95.00;0;top-up shopping;15.00;0;Clothes, etc;50.00;3;(Edit for another...);0.00;0".split(";"),"Mortgage / Rent;520.00;3;Council Tax;1020.71;6;Electric;50.00;3;Gas;30.00;3;Water;350.00;6;Landline & Broadband;25.00;3;Sky Subscription;19.99;3;Mobile contract;15.00;3;TV License;145.50;6".split(";"),"MOT & Work;60.00;6;Road Tax;75.00;6;Insurance;120.00;6;Fuel;15.00;0".split(";"),"General UpKeep;10.00;0;Nights out;15.00;1;Class 2 NI;2.75;0;Partner's Mobile;10.00;3;(Edit for another...);0.00;0;(Edit for another...);0.00;0;(Edit for another...);0.00;0;(Edit for another...);0.00;0".split(";")]):
"new"==b&&(C[a].Ba="0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00".split(" "),C[a].g=["Main Job;0.00;0;edit for another;0.00;0;edit for another;0.00;0".split(";"),"main Job;0.00;0;Edit for another;0.00;0;Edit for another;0.00;0".split(";"),"Tax Credits;0.00;0;Child Benefit;0.00;0;JSA/ESA/ISA;0.00;0;Housing Benefit;0.00;0;Council Tax Rebate;0.00;0;Edit for another;0.00;0".split(";"),"Interest;0.00;0;State Pension;0.00;0;Pension #1;0.00;0;Pension #2;0.00;0;Dividends;45.00;6;(Edit for another...);0.00;0;Edit for another;0.00;0;Edit for another;0.00;0".split(";"),
"Main Shop;0.00;0;top-up shopping;0.00;0;Clothes, etc;0.00;3;Edit for another;0.00;0".split(";"),"Mortgage / Rent;0.00;0;Council Tax;0.00;0;Electric;0.00;0;Gas;0.00;0;Water;0.00;0;Landline & Broadband;0.00;0;Sky Subscription;0.00;0;Mobile contract;.0.00;0;TV License;0.00;0".split(";"),"MOT & Work;0.00;6;Road Tax;0.00;6;Insurance;0.00;6;Fuel;0.00;0".split(";"),"General UpKeep;0.00;0;Nights out;0.00;1;Class 2 NI;0.00;0;Partner's Mobile;0.00;0;Edit for another;0.00;0;Edit for another;0.00;0;Edit for another;0.00;0;Edit for another;0.00;0".split(";")]);
document.getElementById(a+"cbTotalTime")&&Ld(a)}function He(a){var b=cb("DoshManager");if(b){C[a].g=[];try{var d=b.split(P);C[a].Ba=d[0].split(O);for(b=1;b<d.length-1;b++)C[a].g.push(d[b].split(O))}catch(e){Ge(a,"new")}}else Ge(a,"new")}
function Ie(a){C[a].g.Eb=!1;var b=document.getElementById(a+"Box");b.style.width=.8*Q+"px";b.style.backgroundColor="#fff";b.style.fontSize="1em";b.style.padding="4px";for(var d='<p id="'+a+'TL" style="position:absolute;font-size:1.2em;margin:0;padding:0;left:0;width:640px;text-align:center;">Calculation period: <select id="'+a+'cbTotalTime" class="editEnable"><option class="wageC" >Weekly</option><option class="wageC" >Fortnightly</option><option class="wageC" >4-Weekly</option><option class="wageC" >Monthly</option><option class="wageC" >Quarterly</option><option class="wageC" >6-Monthly</option><option class="wageC" >Yearly</option></select></p><div id="'+
a+'dmleftcont" style="position:absolute;top:30px;left:3px;border:1px solid #777;-webkit-border-radius:4px;-moz-border-radius:4px;border-radius:4px;"><p id="'+a+'wIn" style="width:100%;text-align:center;font-size:1.25em;padding:3px;margin:0;"><span id="'+a+'outPer">Weekly</span> Income</p>',e=0;3>=e;e++)d+='<button id="'+a+"_dm_"+e+'_b"class="uButtons uButtonGrey" type="button" style="position:absolute;left:4px;" >'+De[e]+'</button><input type="text" id="'+a+"dm_"+e+'t" class="editDisable" style="position:absolute;" size="5" readonly/>';
d=d+('<p id="'+a+'tIn"style="position:absolute;margin:0;padding:0;text-align:center;">Total Income</p><input type="text" id="'+a+'tInTxt" class="editDisable" style="position:absolute;" size="5"/ readonly></div><div id="')+(a+'dmrightcont" style="position:absolute;top:30px;left:4px;border:1px solid #777;-webkit-border-radius:4px;-moz-border-radius:4px;border-radius:4px;"><p id="'+a+'wOut" style="width:100%;text-align:center;font-size:1.25em;padding:3px;margin:0;"><span id="'+a+'inPer">Weekly</span> Outgoing</p>');
for(e=4;7>=e;e++)d+='<button id="'+a+"_dm_"+e+'_b"class="uButtons uButtonGrey" type="button" style="position:absolute;left:4px;" >'+De[e]+'</button><input type="text" id="'+a+"dm_"+e+'t" class="editDisable" style="position:absolute;" size="5" readonly/>';b.innerHTML=d+('<p id="'+a+'tOut"style="position:absolute;margin:0;padding:0;text-align:center;">Total Outgoing</p><input type="text" id="'+a+'tOutTxt" class="editDisable" style="position:absolute;" size="5"/ readonly></div><p id="')+(a+'WL" style="position:absolute;font-size:1.2em;margin:0;padding:0;width:640px;left:0;text-align:center;">You are <span id="'+
a+'gainLoss">heheing 00.00</span> <span id="'+a+'outTot">Weekly</span></p>');d=1.5;e=1;var f;0<C[a].Window.o&&(e=document.getElementById(a+"Box").offsetWidth/C[a].Window.o,d*=e);document.getElementById(a+"wIn").style.fontSize=document.getElementById(a+"wOut").style.fontSize=document.getElementById(a+"WL").style.fontSize=document.getElementById(a+"TL").style.fontSize=1.2*d+"em";if(-1==C[a].Window.o)document.getElementById(a+"_dm_3_b").style.border=0,document.getElementById(a+"_dm_3_b").style.width=
document.getElementById(a+"_dm_3_b").style.height="",document.getElementById(a+"_dm_3_b").style.fontSize=d+"em",document.getElementById(a+"dm_0t").style.fontSize=d+"em",C[a].Window.fc=document.getElementById(a+"_dm_3_b").offsetWidth,C[a].Window.hc=f=document.getElementById(a+"dm_0t").offsetWidth,document.getElementById(a+"_dm_3_b").style.border="",document.getElementById(a+"_dm_3_b");else{f=C[a].Window.fc*e;var g=C[a].Window.hc*e}var l=document.getElementById(a+"_dm_3_b").offsetHeight+6*e;document.getElementById(a+
"TL").style.top="4px";for(var m=0;3>=m;m++)document.getElementById(a+"_dm_"+m+"_b").style.left=document.getElementById(a+"_dm_"+(m+4)+"_b").style.left=4*e+"px",document.getElementById(a+"_dm_"+m+"_b").style.width=document.getElementById(a+"_dm_"+(m+4)+"_b").style.width=f+"px",document.getElementById(a+"dm_"+m+"t").style.width=document.getElementById(a+"dm_"+(m+4)+"t").style.width=g+"px",document.getElementById(a+"_dm_"+m+"_b").style.fontSize=document.getElementById(a+"_dm_"+(m+4)+"_b").style.fontSize=
document.getElementById(a+"dm_"+m+"t").style.fontSize=document.getElementById(a+"dm_"+(m+4)+"t").style.fontSize=d+"em",document.getElementById(a+"_dm_"+m+"_b").style.top=document.getElementById(a+"_dm_"+(m+4)+"_b").style.top=document.getElementById(a+"dm_"+m+"t").style.top=document.getElementById(a+"dm_"+(m+4)+"t").style.top=(m+1)*l+"px",document.getElementById(a+"dm_"+m+"t").style.left=document.getElementById(a+"dm_"+(m+4)+"t").style.left=f+8*e+"px",document.getElementById(a+"dm_"+m+"t").style.height=
document.getElementById(a+"dm_"+(m+4)+"t").style.height=l-9+"px";document.getElementById(a+"tIn").style.top=document.getElementById(a+"tInTxt").style.top=document.getElementById(a+"tOut").style.top=document.getElementById(a+"tOutTxt").style.top=5*l+"px";document.getElementById(a+"tIn").style.fontSize=document.getElementById(a+"tInTxt").style.fontSize=document.getElementById(a+"tOut").style.fontSize=document.getElementById(a+"tOutTxt").style.fontSize=d+"em";document.getElementById(a+"tIn").style.width=
document.getElementById(a+"tOut").style.width=f+8*e+"px";document.getElementById(a+"tInTxt").style.left=document.getElementById(a+"tOutTxt").style.left=f+8*e+"px";document.getElementById(a+"tInTxt").style.width=document.getElementById(a+"tOutTxt").style.width=g+"px";document.getElementById(a+"dmleftcont").style.top=document.getElementById(a+"dmrightcont").style.top=document.getElementById(a+"TL").offsetTop+document.getElementById(a+"TL").offsetHeight+4*e+"px";document.getElementById(a+"TL");document.getElementById(a+
"dmleftcont").style.height=document.getElementById(a+"dmrightcont").style.height=6*l+"px";document.getElementById(a+"dmleftcont").style.width=document.getElementById(a+"dmrightcont").style.width=f+document.getElementById(a+"dm_0t").offsetWidth+14*e+"px";document.getElementById(a+"dmleftcont").style.left=4*e+"px";document.getElementById(a+"dmrightcont").style.left=document.getElementById(a+"dmleftcont").offsetWidth+8*e+"px";document.getElementById(a+"WL").style.top=document.getElementById(a+"dmleftcont").offsetTop+
document.getElementById(a+"dmleftcont").offsetHeight+8*e+"px";l=document.getElementById(a+"WL").offsetTop+document.getElementById(a+"WL").offsetHeight+8*e;document.getElementById(a+"Box").style.height=l+"px";g=document.getElementById(a+"dmrightcont").offsetLeft+document.getElementById(a+"dmrightcont").offsetWidth+5;C[a].Window.o=g;document.getElementById(a+"Box").style.width=g+"px";d=document.getElementById(a+"Box").offsetHeight;C[a].Window.s=d;document.getElementById(a+"Box").style.height=d+"px";
document.getElementById(a+"TL").style.width=document.getElementById(a+"WL").style.width="100%";C[a].Window.G=.33*g;C[a].Window.F=.33*d;Yb(b);Zb(b)}function wd(a,b){a=fc(a);C[a]?cc(document.getElementById(a.toString()),"Top"):U("_"+a+"_"+b)}
function Fe(a){var b=parseInt(a,10);C[a].ua=parseInt(C[a].Window.Qb,10);var d=C[a].Window;d.s=360;d.Fa=1;d.I="DMW";d.S=1;d.ca=1;document.getElementById(a+"Title").innerHTML=De[C[a].ua]+" - Dosh Manager";C[a].nb=C[b].g[C[a].ua].length/3;document.getElementById(a+"MinButton").style.width=0;d=document.getElementById(a+"Box");d.style.fontSize="1em";d.style.backgroundColor="#fff";d.style.padding="6px";d.style.width=Q+"px";for(var e="",f=0;f<C[a].nb;f++)e+='<input type="text" id="'+a+"dm_"+f+'desc" class="editEnable" size="16">&nbsp;<input type="text" id="'+
a+"dm_"+f+'num" class="editEnable"  size="3">&nbsp;<select id="'+a+"dm_"+f+'per" class="editEnable"><option class="wageC" >Weekly</option><option class="wageC" >Fortnightly</option><option class="wageC" >4-Weekly</option><option class="wageC" >Monthly</option><option class="wageC" >Quarterly</option><option class="wageC" >6-Monthly</option><option class="wageC" >Yearly</option></select><br>';d.innerHTML=e+('<br><button id="'+a+'_dmW_bNO"class="uButtons uButtonGrey" type="button" style="float:left;" >Cancel</button><p id="'+
a+'WL" style="float:left;font-size:1.2em;margin:0;padding:0;left:0;text-align:center;">Weekly total: 0000.00</p><button id="'+a+'_dmW_bOK"class="uButtons uButtonGrey" type="button" style="float:right;padding-right:8px;" >Accept</button>');for(f=0;f<C[a].nb;f++)try{document.getElementById(a+"dm_"+f+"desc").value=C[b].g[C[a].ua][3*f],document.getElementById(a+"dm_"+f+"num").value=C[b].g[C[a].ua][3*f+1],document.getElementById(a+"dm_"+f+"per").selectedIndex=C[b].g[C[a].ua][3*f+2],document.getElementById(a+
"dm_"+f+"per").addEventListener("mouseup",function(){Ke(a)},!1),document.getElementById(a+"dm_"+f+"per").addEventListener("touchend",function(){Ke(a)},!1),document.getElementById(a+"dm_"+f+"per").addEventListener("wheel",function(){Ke(a)},!1),document.getElementById(a+"dm_"+f+"num").addEventListener("keyup",function(){Ke(a)},!1)}catch(g){}b=document.getElementById(a+"dm_0per").offsetLeft+document.getElementById(a+"dm_0per").offsetWidth+0;d.style.width=b+"px";Yb(d);Zb(d);document.getElementById(a+
"_dmW_bOK").style.left=document.getElementById(a+"dm_0per").offsetLeft+document.getElementById(a+"dm_0per").offsetWidth-document.getElementById(a+"_dmW_bOK").offsetWidth+"px";document.getElementById(a+"WL").style.width=document.getElementById(a+"_dmW_bOK").offsetLeft-10-document.getElementById(a+"_dmW_bOK").offsetWidth+"px";d.style.height=document.getElementById(a+"_dmW_bOK").offsetTop-0+document.getElementById(a+"_dmW_bOK").offsetHeight+4+"px";C[a].Window.s=d.offsetHeight;d.style.height=C[a].Window.s+
"px";C[a].Window.o=4+document.getElementById(a+"dm_0per").offsetLeft+document.getElementById(a+"dm_0per").offsetWidth;d.style.width=C[a].Window.o+"px";document.getElementById(a+"WL").style.width=document.getElementById(a+"_dmW_bOK").offsetLeft-document.getElementById(a+"WL").offsetLeft+"px";C[a].Window.G=.33*C[a].Window.o;C[a].Window.F=.33*C[a].Window.s;document.getElementById(a+"Box").style.width=.8*Q+"px";Nb(a);Ke(a)}
function Ld(a){document.getElementById(a+"inPer").innerHTML=document.getElementById(a+"outPer").innerHTML=document.getElementById(a+"outTot").innerHTML=document.getElementById(a+"cbTotalTime").value;Je(a);for(var b in C)a==parseInt(b,10)&&b!=a&&Ke(b)}
function yd(a,b){if("OK"==b){C[parseInt(a,10)].Ba[C[a].ua]=C[a].total;for(b=0;b<C[a].nb;b++)C[parseInt(a,10)].g[C[a].ua][3*b]=document.getElementById(a+"dm_"+b+"desc").value,C[parseInt(a,10)].g[C[a].ua][3*b+1]=Number(document.getElementById(a+"dm_"+b+"num").value).toFixed(2),C[parseInt(a,10)].g[C[a].ua][3*b+2]=document.getElementById(a+"dm_"+b+"per").selectedIndex.toString();Je(parseInt(a,10))}pc(a)};window.zFbInit=function(a){C[a].Window.name="Feedback / Contact (1000   Characters)";document.getElementById(a+"Box").style.padding="4px";document.getElementById(a+"Box").style.backgroundColor="#fff";document.getElementById(a+"Box").innerHTML='<div id="fbNIns" class="instructdiv"><strong>Name</strong> (Optional)<input type="text" id="fbName" class="editEnable feedBackIn" style="padding:4px;border:2px solid #a7a7a7;border-radius:6px;"></div><div id="fbEIns" class="instructdiv"><strong>Email</strong> (Optional)<input type="text" id="fbEmail" class="editEnable feedBackIn" style="padding:4px;border:2px solid #a7a7a7;border-radius:6px;"></div><div id="startHere"></div><div id="FCCont" style="position:absolute;left:4px;outline:0;border:0;"><div id="commentIns" style="position:absolute;z-index:1;text-align:center;color:rgba(0, 0, 0, 0.4);width:100%;">Enter your message here</div><textarea id="feedbackComment" class="editEnable feedBackTextInput" style="padding:1%;border:2px solid #a7a7a7;border-radius:6px;"></textarea></div><button id="FbSubButton" type="button" class="uButtonDisabled" style="position:absolute;">Send Feedback</button>';
Le(a);document.getElementById("FbSubButton").addEventListener("mouseup",function(){Me(a)},!1);document.getElementById("FbSubButton").addEventListener("touchend",function(){Me(a)},!1);document.getElementById("feedbackComment").addEventListener("input",function(){Ne(a,"feedbackComment")},!1);document.getElementById("fbName").addEventListener("input",function(){Ne(a,"fbName")},!1);document.getElementById("fbEmail").addEventListener("input",function(){Ne(a,"fbEmail")},!1)};
function Ub(a){try{var b=document.getElementById(a+"Box"),d=document.getElementById("fbNIns"),e=document.getElementById("fbEIns"),f=document.getElementById("fbName");document.getElementById("fbEmail");var g=document.getElementById("commentIns"),l=document.getElementById("FCCont");e.style.top=d.style.top="8px";e.style.width=d.style.width=Math.floor(b.offsetWidth/2-26)+"px";e.style.left=d.offsetWidth+20+"px";document.getElementById("FbSubButton").style.top=b.offsetHeight-document.getElementById("FbSubButton").offsetHeight-
4+"px";document.getElementById("FbSubButton").style.left=Math.floor(b.offsetWidth/2-document.getElementById("FbSubButton").offsetWidth/2)+"px";l.style.width=Math.floor(2*d.offsetWidth+24)+"px";l.style.top=Math.floor(e.offsetTop+f.offsetHeight+4)+"px";var m=b.offsetHeight-(document.getElementById("FbSubButton").offsetHeight+4)-l.offsetTop-6;l.style.height=m+"px";g.style.top=l.offsetHeight/2-g.offsetHeight/2+"px"}catch(p){}}function Le(a){Ac(a);Ub(a)}
function Ne(a,b){var d=document.getElementById(b);"feedbackComment"==b?""!=d.value?document.getElementById("commentIns").style.color="#fff":document.getElementById("commentIns").style.color="rgba(0, 0, 0, 0.4)":"fbName"==b?""!=d.value?document.getElementById("fbNIns").style.color="#fff":document.getElementById("fbNIns").style.color="rgba(0, 0, 0, 0.4)":"fbEmail"==b&&(""!=d.value?document.getElementById("fbEIns").style.color="#fff":document.getElementById("fbEIns").style.color="rgba(0, 0, 0, 0.4)");
b=1E3-document.getElementById("fbName").value.length;b-=document.getElementById("fbEmail").value.length;b-=document.getElementById("feedbackComment").value.length;a=document.getElementById(a+"Title");a.innerHTML="Feedback / Contact ("+b+" Characters)";1E3==b||0==document.getElementById("feedbackComment").value.length?(a.style.color="",document.getElementById("FbSubButton").className="uButtonDisabled"):0>b?(a.style.color="#f78",document.getElementById("FbSubButton").className="uButtonDisabled"):-1<
b&&(a.style.color="",document.getElementById("FbSubButton").className="uButtons uButtonGrey");if(1==b||-1==b)a.innerHTML="Send Feedback ("+b+" Character)"}
function Me(a){if(0==document.getElementById("feedbackComment").value.length)h("Please type a comment, or description of any bugs you encountered before sending."),document.getElementById("feedbackComment").focus();else{var b="";0<document.getElementById("fbName").value.length&&(document.getElementById("fbName"),b+="Name:\n"+document.getElementById("fbName").value+"\n\n------========-------\n\n");0<document.getElementById("fbEmail").value.length&&(document.getElementById("fbEmail"),b+="Email:\n"+
document.getElementById("fbEmail").value+"\n\n------========-------\n\n");b+="Comment:\n\n"+document.getElementById("feedbackComment").value+"\n\n------========-------\n\n";3200<b.length?(h("Apologies, but Feedback is limited to 3200 characters.<br>Please shorten your message."),document.getElementById("feedbackComment").focus()):(b="Date/Time: "+new Date+"\n"+b+"\n",b=b.replace(/\r\n|\r|\n/g,"___-v-y-___"),Oe(b,a))}}
function Oe(a,b){var d=new XMLHttpRequest;d.addEventListener("load",function(){var e=d.responseText.replace(/~vNL~/g,"<br>");h(e);"Message sent<br>Thankyou."==e&&pc(b)},!1);d.open("POST","mailIt.php?blah="+a,!0);d.send();document.getElementById("FbSubButton").style.hidden="true"};window.if_Init=function(a){var b=C[a].Window;b.o=640;b.s=360;b.G=-1;b.F=-1;b.I="if";Ac(a);var d="";1<R[b.Y].La.length&&(d={Text:"Tip/Support "+R[b.Y].Ca,j:function(){Db(R[b.Y].Qa)}});C[a].D=[{Text:"About",v:[{Text:"About "+document.getElementById(a+"Title").innerHTML,j:function(){U(R[b.Y].Ka+"-"+document.getElementById(a+"Title").innerHTML+"_100")}},{Text:"Author: "+R[b.Y].Ca,j:function(){Db(R[b.Y].Qa)}},d]}];d=document.getElementById(a+"Box");d.style.backgroundColor="#444";d.innerHTML='<iframe style="border:0;width:100%;height:100%;" src="'+
R[b.Y].Ma+'" allowfullscreen></iframe>'};window.svl_Init=function(a){var b=C[a].Window;b.I="svl";b.S=1;b.ca=1;C[a].ea=[{Text:"Reset Calculator",j:function(){}}];C[a].D=[{Text:"Reset",v:[{Text:"Reset Calculator",j:function(){}}]}];b=document.getElementById(a+"Cont");var d=document.getElementById(a+"Box");Pe(a);C[a].Window.o=b.offsetWidth;C[a].Window.s=b.offsetHeight;C[a].Window.G=Math.floor(C[a].Window.o/2);C[a].Window.F=Math.floor(C[a].Window.s/2);var e=b.offsetWidth/b.offsetHeight;d.style.width=Math.round(.8*Q)+"px";d.style.height=Math.round(b.offsetWidth/
e)+"px";Ic(a)};
function Pe(a){var b=document.getElementById(a+"Box");C[a].g.Eb=!0;b.style.padding="4px";b.style.backgroundColor="#fff";b.innerHTML='<div style="text-align:center;font-size:2em;"><span class="labScale" style="top:0px;">Target amount</span><input type="text" id="svl_'+a+'_target" class="editEnable" style="text-align:center;background:linear-gradient(#fff, #ddd);border:1px solid #000;" size="6" value="5000"><Span>%</span></div><div style="clear:both;text-align:center;"><span class="labScale" style="top:0px;">Average inflation rate</span><input type="text" id="svl_'+a+
'_inflat" class="editEnable" style="text-align:center;background:linear-gradient(#fff, #ddd);border:1px solid #000;" size="1" value="2"><Span>%</span></div><div id="svl-'+a+'-slider-C" style="word-break:break-all;clear:both;float:left;margin-top:12px;width:100%;background:linear-gradient(#ddd, #777);border:1px solid #000;height:20px;border-radius:20px;text-align:left;"><span id="svl_'+a+'_years" style="margin:0.3% 2%;float:left;">5 years</span><div id="svl-'+a+'-slider-I"" style="position:relative;top:-7px;left:37%;border-radius:32px;background:radial-gradient(circle at 33% 33% , #fff, #333);border:1px solid #000;height:32px;width:32px;"></div></div><div style="clear:both;text-align:center;"><span>Payments:</span><input type="text" id="svl_'+
a+'_sPays" class="editEnable" style="text-align:center;background:linear-gradient(#fff, #ddd);border:1px solid #000;" size="3" value="20.00"><span> every</span><select id="svl_'+a+'_per" class="editEnable" style=""><option class="wageC" >Week</option><option class="wageC" >Fortnight </option><option class="wageC" >4 Weeks</option><option class="wageC" selected>Month</option><option class="wageC" >Quarter</option><option class="wageC" >6 Months&#160;</option><option class="wageC" >Year</option></select></div><div style="clear:both;text-align:center;float:left;padding:1% 0;width:calc(50% - 1px);border:1px solid #000;"><span class="labScale">Savings Interest:</span><input type="text" id="svl_'+
a+'_sInt" class="editEnable" style="text-align:center;background:linear-gradient(#fff, #ddd);border:1px solid #000;" size="1" value="5"><Span>%</span><br><span class="labScale">Total Payed:</span><input type="text" id="svl_'+a+'_sTot" class="editEnable" style="text-align:center;background:linear-gradient(#fff, #ddd);border:1px solid #000;" size="8" value="6500"></div>';document.getElementById(a+"Title").innerHTML="Savings Vs Loans Calculator";document.getElementById("svl_"+a+"_target").style.width=
document.getElementById("svl_"+a+"_target").offsetWidth+6+"px";document.getElementById("svl_"+a+"_per").addEventListener("change",function(){Ic(a)},!1);b.style.height=b.offsetHeight+"px";b.style.width=b.offsetWidth+"px";Yb(b);Zb(b)}
function Ic(a){document.getElementById("svl_"+a+"_target");var b=parseFloat(document.getElementById("svl_"+a+"_inflat").value)/100;document.getElementById("svl_"+a+"_years");var d=parseFloat(document.getElementById("svl_"+a+"_sPays").value),e=Qa[document.getElementById("svl_"+a+"_per").selectedIndex],f=parseFloat(document.getElementById("svl_"+a+"_sInt").value)/100;d*=e;f=(1+f)/(1+b);b=d;for(e=0;68>=e;e++)b+=d,b*=f;document.getElementById("svl_"+a+"_sTot").value=b.toFixed(2)}
function Wc(a){var b=x.O,d=b.parentNode.offsetWidth,e=b.parentNode.offsetLeft;a=a.clientX-document.getElementById(b.id.split("-")[1]).offsetLeft-e-F;a-=b.offsetWidth/2;a=a/(d-b.offsetWidth)*100;0>a?a=0:100<a&&(a=100);a*=(d-b.offsetWidth)/d;b.style.left=a+"%"};window.screen_Init=Qe;
function Qe(a){var b=C[a].Window.l;C[a].Window.I="Screens";3==b?(b=C[a].Window,b.o=630,b.s=380,b.G=314,b.F=190,b.name="DUMBasic",C[a].g={image:new Image},C[a].g.image.src="images/DUMbasic.png",C[a].ea=[{Text:"Fullscreen",j:function(){V(a)}},{Text:"About",j:function(){U("DUMbasic-DUMbasic_100")}},{Text:"Whats New",j:function(){U("DUMbasicCL-DUMbasic_100")}}],C[a].D=[{Text:"File",v:[{Text:"Download DUMbasic",j:function(){Db("bins/DUMbasic.exe")}}]},{Text:"Fullscreen",v:[{Text:"Fullscreen",j:function(){V(a)}}]},
{Text:"Help",v:[{Text:"About",j:function(){U("DUMbasic-DUMbasic_100")}},{Text:"Whats New",j:function(){U("DUMbasicCL-DUMbasic_100")}}]}]):4==b?(b=C[a].Window,b.o=640,b.s=512,b.G=286,b.F=256,b.name="Private Diary",C[a].g={image:new Image},C[a].g.image.src="images/PrivateDiary.png",C[a].ea=[{Text:"Fullscreen",j:function(){V(a)}},{Text:"About",j:function(){U("PrivateDiary-Private Diary_100")}},{Text:"Whats New",j:function(){U("PrivateDiaryCL-Private Diary_100")}}],C[a].D=[{Text:"File",v:[{Text:"Download Private Diary",
j:function(){Db("bins/PrivateDiary.exe")}}]},{Text:"Fullscreen",v:[{Text:"Fullscreen",j:function(){V(a)}}]},{Text:"Help",v:[{Text:"About",j:function(){U("PrivateDiary-Private Diary_100")}},{Text:"Whats New",j:function(){U("PrivateDiaryCL-Private Diary_100")}}]}]):6==b?(b=C[a].Window,b.o=680,b.s=165,b.G=170,b.F=41,b.name="JS Cavern Complete Map",C[a].g={image:new Image},C[a].g.image.src="games/JSCavern/Pics/OverallMap.png"):17==b?(b=C[a].Window,b.o=300,b.s=375,b.G=150,b.F=251876,b.name="App Timer",
C[a].g={image:new Image},C[a].g.image.src="images/AppTimer.png",C[a].ea=[{Text:"Fullscreen",j:function(){V(a)}},{Text:"About",j:function(){U("AppTimer-App Timer_100")}},{Text:"Whats New",j:function(){U("AppTimerCL-App Timer_100")}}],C[a].D=[{Text:"File",v:[{Text:"Download AppTimer",j:function(){Db("bins/AppTimer.exe")}}]},{Text:"Fullscreen",v:[{Text:"Fullscreen",j:function(){V(a)}}]},{Text:"Help",v:[{Text:"About",j:function(){U("AppTimer-App Timer_100")}},{Text:"Whats New",j:function(){U("AppTimerCL-App Timer_100")}}]}]):
18==b&&(b=C[a].Window,b.o=951,b.s=637,b.G=475,b.F=318,b.name="Event Manager",C[a].g={image:new Image},C[a].g.image.src="images/EventManager.png",C[a].ea=[{Text:"Fullscreen",j:function(){V(a)}},{Text:"About",j:function(){U("EventManager-Event Manager_100")}},{Text:"Whats New",j:function(){U("EventManagerrCL-Event Manager_100")}}],C[a].D=[{Text:"File",v:[{Text:"Download EventManager",j:function(){Db("bins/EventManager.exe")}}]},{Text:"Fullscreen",v:[{Text:"Fullscreen",j:function(){V(a)}}]},{Text:"Help",
v:[{Text:"About",j:function(){U("EventManager-Event Manager_100")}},{Text:"Whats New",j:function(){U("EventManagerrCL-Event Manager_100")}}]}]);C[a].Window.ca=!0;b=document.getElementById(a+"Box");b.innerHTML='<img id="'+a+'img" class="screen_img" src="'+C[a].g.image.src+'" style="width:100%;height:100%;" alt="For more info, and to download, check out the menu\nmouse wheel zooms, and you can click/drag the zoomed screenshot">';b.style.backgroundColor="#000";b.style.height=C[a].Window.s+"px";b.style.width=
C[a].Window.o+"px";b.style.overflow="visible";document.getElementById(a+"Title").innerHTML=C[a].Window.name+" - Picture Viewer";C[a].g.Ua=0;C[a].g.tb=0;C[a].g.left=0;C[a].g.top=0;C[a].g.zoom=1;Sb(a,-1);var d=document.getElementById(a+"Cont"),e=C[a].Window.o/C[a].Window.s;b.style.width=Math.round(.8*Q)+"px";b.style.height=Math.round(Math.round(.8*Q)/e)+"px";C[a].Window.G=Math.floor(d.offsetWidth/3);C[a].Window.F=Math.floor(d.offsetHeight/3)}
function gd(a,b){"sDrg"==y.N&&"Resizing"!=y.N&&(C[a].g.left=b.clientX-C[a].g.Ua,C[a].g.top=b.clientY-C[a].g.tb,Re(a))}
function Re(a){var b=document.getElementById(a+"img"),d=document.getElementById(a+"Cont"),e=document.getElementById(a+"Box");b.offsetWidth>d.offsetWidth?(0<C[a].g.left+e.offsetLeft&&(C[a].g.left=-e.offsetLeft),C[a].g.left+b.offsetWidth+e.offsetLeft<d.offsetWidth&&(C[a].g.left=d.offsetWidth-b.offsetWidth-e.offsetLeft)):(0>C[a].g.left+e.offsetLeft&&(C[a].g.left=-e.offsetLeft),C[a].g.left+b.offsetWidth+e.offsetLeft>d.offsetWidth&&(C[a].g.left=d.offsetWidth-b.offsetWidth-e.offsetLeft));b.offsetHeight>
d.offsetHeight?(0<C[a].g.top+e.offsetTop&&(C[a].g.top=-e.offsetTop),C[a].g.top+b.offsetHeight+e.offsetTop<d.offsetHeight&&(C[a].g.top=d.offsetHeight-b.offsetHeight-e.offsetTop)):(0>C[a].g.top+e.offsetTop&&(C[a].g.top=-e.offsetTop),C[a].g.top+b.offsetHeight+e.offsetTop>d.offsetHeight&&(C[a].g.top=d.offsetHeight-b.offsetHeight-e.offsetTop));b.style.left=C[a].g.left+"px";b.style.top=C[a].g.top+"px"}
function Sb(a,b){b&&(C[a].g.zoom*=1+b/10);var d=document.getElementById(a+"img"),e=document.getElementById(a+"Box"),f=parseFloat(d.style.width),g=parseFloat(d.style.height);1>C[a].g.zoom&&(C[a].g.zoom=1,C[a].g.left=C[a].g.top=0);d.style.width=e.offsetWidth*parseFloat(C[a].g.zoom)+"px";d.style.height=e.offsetHeight*parseFloat(C[a].g.zoom)+"px";e=parseFloat(d.style.width);var l=parseFloat(d.style.height);0==b?(C[a].g.left+=(e-f)/e*C[a].g.left,C[a].g.top+=(l-g)/l*C[a].g.top):(C[a].g.left+=(f-e)*((x.Ra-
(document.getElementById(a).offsetLeft+F))/document.getElementById(a+"Box").offsetWidth),C[a].g.top+=(g-l)*((x.Sa-(document.getElementById(a).offsetTop+F))/document.getElementById(a+"Box").offsetHeight));d.style.left=C[a].g.left+"px";d.style.top=C[a].g.top+"px";Re(a)};window.tg_Init=function(a){Ya||(Ya=new (window.AudioContext||window.webkitAudioContext),console.log("audio context initialized. should only happen once!"));var b=C[a].Window;b.o=640;b.s=240;b.G=320;b.F=240;b.I="atg";b.S=1;b.ca=1;C[a].g={ma:[],Xa:[],A:[],oc:1};C[a].D=[{Text:"Help",v:[{Text:"About",j:function(){U("ToneGenerator-Tone Generator_100")}}]}];document.getElementById(a);b=document.getElementById(a+"Box");b.innerHTML="";b.style.backgroundColor="#fff";b.style.padding="4px";b.style.textAlign=
"center";Se(a,0);Se(a,1);b.style.height=b.offsetHeight+"px";b.style.width=b.offsetWidth+10+"px";Yb(b);Zb(b);C[a].Window.o=document.getElementById(a+"Cont").offsetWidth;C[a].Window.s=document.getElementById(a+"Cont").offsetHeight;C[a].Window.G=Math.floor(C[a].Window.o/3);C[a].Window.F=C[a].Window.s;document.getElementById(a+"Box").style.width=.8*Q+"px";Rb(a);document.getElementById(a+"CloseButton").addEventListener("mouseup",function(){Te(a)},!1);document.getElementById(a+"CloseButton").addEventListener("touchend",
function(){Te(a)},!1)};
function Se(a,b){C[a].g.ma[b]=Ya.createOscillator();C[a].g.Xa[b]=Ya.createGain();C[a].g.ma[b].connect(C[a].g.Xa[b]);C[a].g.ma[b].type="sine";C[a].g.ma[b].frequency.value=Ue(60+12*b,12,69);C[a].g.Xa[b].gain.value=.5;C[a].g.ma[b].start();0!=b&&(document.getElementById(a+"Box").innerHTML+='<div style="clear:both;float:left;width:100%;margin:18px 0px 18px 0px;text-align:center;"><div style="display:inline;border-radius:32px;padding:6px 18px;background:linear-gradient(#eee, #999);border:1px solid #000;">Sweep between these tones, taking <input type="text" id="tg_'+a+
"_"+b+'_sweep" class="editEnable" style="text-align:center;background:linear-gradient(#fff, #ddd);border:1px solid #000;padding:0;" size="3" value="10"> seconds <button id="tg_'+a+"_"+b+'_sweepGO" type="button" class="uButtons uButtonGreen" style="display:inline;padding:0px 6px;">&nbsp;&nbsp;GO!&nbsp;&nbsp;</button><span>&nbsp;<input type="checkbox" id="tg_'+a+"_"+b+'_sweepLoop" class="editEnable" style="position:relative;top:2px;display:inline;">Loop</span></div>');document.getElementById(a+"Box").innerHTML+=
'<div id="tg_'+a+"_"+b+'_cont1" style="clear:both;float:left;margin-bottom:4px;text-align:left;width:100%;"><button id="tg_'+a+"_"+b+'_pp" type="button" class="uButtons uButtonRed" style="float:left;margin-right:10px;">Start</button><div style="float:left;margin-right:6px;font-size:100%;transform:scaleX(2);">&#9698;</div><div id="tg_'+a+"_"+b+'_vol" style="float:left;padding:1px 0px;text-align:center;">100%</div><div id="tg-'+a+"-"+b+'-slider-Cv" class="winSliderCont" style="float:left;width:150px;height:10px;"><div id="tg-'+
a+"-"+b+'-slider-Iv" class="winSliderInner" style="position:relative;top:-6px;left:43%;height:20px;width:20px;"></div></div><button id="tg_'+a+"_"+b+'_sw" type="button" class="uButtons uButtonGrey" style="float:right;margin-left:4px;">Sawtooth</button><button id="tg_'+a+"_"+b+'_sq" type="button" class="uButtons uButtonGrey" style="float:right;margin-left:4px;">Square</button><button id="tg_'+a+"_"+b+'_tr" type="button" class="uButtons uButtonGrey" style="float:right;margin-left:4px;">Triangle</button><button id="tg_'+
a+"_"+b+'_si" type="button" class="uButtons uButtonGreen" style="float:right;margin-left:4px;">Sine</button></div><div style="clear:both;float:left;text-align:center;width:100%;"><input type="text" id="tg_'+a+"_"+b+'_min" class="editEnable" style="clear:both;float:left;text-align:center;background:linear-gradient(#fff, #ddd);border:1px solid #000;" size="9" value="'+Ue(12,12,69)+'"><input type="text" id="tg_'+a+"_"+b+'_now" style="text-align:center;font-weight:900;background:linear-gradient(#fff, #ddd);border:1px solid #000;" class="editEnable" size="9" value="'+
Ue(60+12*b,12,69)+'"><input type="text" id="tg_'+a+"_"+b+'_max" class="editEnable" style="float:right;text-align:center;background:linear-gradient(#fff, #ddd);border:1px solid #000;" size="9" value="'+Ue(141,12,69)+'"></div><div id="tg-'+a+"-"+b+'-slider-C" class="winSliderCont" style="word-break:break-all;clear:both;float:left;width:100%;height:20px;text-align:left;"><span id="tg_'+a+"_"+b+'_chk" style="margin-left:8px;left:8px;float:left;"><input type="checkbox" id="tg_'+a+"_"+b+'_stn" class="editEnable" style="position:relative;top:2px;display:inline;">Snap to <input type="text" id="tg_'+
a+"_"+b+'_pn" class="editEnable" style="text-align:center;background:linear-gradient(#fff, #ddd);border:1px solid #000;padding:0;" size="2" value="12"> Notes per Octave &nbsp; &nbsp;</span><div id="tg-'+a+"-"+b+'-slider-I" class="winSliderInner" style="position:relative;top:-7px;left:37%;height:32px;width:32px;"></div></div>';Hc(a,b,Ue(60+12*b,12,69));document.getElementById("tg_"+a+"_"+b+"_si").style.width=document.getElementById("tg_"+a+"_"+b+"_tr").style.width=document.getElementById("tg_"+a+"_"+
b+"_sq").style.width=document.getElementById("tg_"+a+"_"+b+"_sw").offsetWidth-14+"px";document.getElementById("tg_"+a+"_"+b+"_vol").style.width=document.getElementById("tg_"+a+"_"+b+"_vol").offsetWidth+"px";document.getElementById("tg_"+a+"_"+b+"_vol").innerHTML="50%"}
function Hc(a,b,d){var e=document.getElementById("tg_"+a+"_"+b+"_max").value,f=document.getElementById("tg_"+a+"_"+b+"_min").value;d=Math.round((Math.log(d)/Math.log(2)-Math.log(f)/Math.log(2))/(Math.log(e/f)/Math.log(2))*100);a=document.getElementById("tg-"+a+"-"+b+"-slider-I");b=a.parentNode.offsetWidth;0>d?d=0:100<d&&(d=100);d*=(b-a.offsetWidth)/b;a.style.left=d+"%"}
function Vc(a){var b=x.O,d=b.id.split("-"),e=d[1],f=d[2],g=b.parentNode.offsetWidth,l=b.parentNode.offsetLeft;a=a.clientX-document.getElementById(e).offsetLeft-l-8;a-=b.offsetWidth/2;a=a/(g-b.offsetWidth)*100;0>a?a=0:100<a&&(a=100);if("I"===d[4]||"C"===d[4]){l=a;var m=document.getElementById("tg_"+e+"_"+f+"_max").value,p=document.getElementById("tg_"+e+"_"+f+"_min").value;d=document.getElementById("tg_"+e+"_"+f+"_pn").value;l=Math.pow(2,Math.log(m/p)/Math.log(2)*(l/100)+Math.log(p)/Math.log(2)).toFixed(3);
document.getElementById("tg_"+e+"_"+f+"_stn").checked&&(m=d/12*69,l=Ue(Math.round(Math.log(l/440)/Math.log(2)*d)+Math.round(m),d,m));C[e].g.ma[f].frequency.value=document.getElementById("tg_"+e+"_"+f+"_now").value=l}else if("Iv"===d[4]||"Cv"===d[4])C[e].g.Xa[f].gain.value=a/100,document.getElementById("tg_"+e+"_"+f+"_vol").innerHTML=Math.round(a)+"%";a*=(g-b.offsetWidth)/g;b.style.left=a+"%"}
function ud(a){var b=a.id.split("_");if("pp"===b[3])"Start"===a.innerHTML?(a.innerHTML="Stop",a.classList.remove("uButtonRed"),a.classList.add("uButtonGreen"),C[b[1]].g.Xa[b[2]].connect(Ya.destination)):(a.innerHTML="Start",a.classList.remove("uButtonGreen"),a.classList.add("uButtonRed"),C[b[1]].g.Xa[b[2]].disconnect(Ya.destination));else if("sweepGO"===b[3])a=b[1],b=b[2],"Stop!"!=document.getElementById("tg_"+a+"_"+b+"_sweepGO").innerHTML?(document.getElementById("tg_"+a+"_"+b+"_sweepGO").classList.remove("uButtonGreen"),
document.getElementById("tg_"+a+"_"+b+"_sweepGO").classList.add("uButtonRed"),document.getElementById("tg_"+a+"_"+b+"_sweepGO").innerHTML="Stop!",C[a].g.A[b]={xa:Ya.createOscillator(),gain:Ya.createGain(),zb:1E3*parseFloat(document.getElementById("tg_"+a+"_"+b+"_sweep").value),Ab:(new Date).getTime(),Rb:0,Va:0,rb:document.getElementById("tg_"+a+"_"+(b-1)+"_now").value,Yb:document.getElementById("tg_"+a+"_"+b+"_now").value,Wa:parseInt(document.getElementById("tg_"+a+"_"+(b-1)+"_vol").innerHTML,10),
Tb:parseInt(document.getElementById("tg_"+a+"_"+b+"_vol").innerHTML,10)},C[a].g.A[b].Rb=C[a].g.A[b].Ab+C[a].g.A[b].zb,C[a].g.A[b].xa.connect(C[a].g.A[b].gain),C[a].g.A[b].gain.connect(Ya.destination),C[a].g.A[b].xa.type="sine",C[a].g.A[b].xa.frequency.value=C[a].g.A[b].rb,C[a].g.A[b].gain.gain.value=C[a].g.A[b].Wa/100,C[a].g.A[b].xa.start(),Ve(a,b)):(document.getElementById("tg_"+a+"_"+b+"_sweepGO").classList.remove("uButtonRed"),document.getElementById("tg_"+a+"_"+b+"_sweepGO").classList.add("uButtonGreen"),
document.getElementById("tg_"+a+"_"+b+"_sweepGO").innerHTML="  GO!  ",C[a].g.A[b].xa.stop());else{var d=a.id.slice(0,a.id.lastIndexOf("_"));document.getElementById(d+"_si").classList.contains("uButtonGreen")&&(document.getElementById(d+"_si").classList.remove("uButtonGreen"),document.getElementById(d+"_si").classList.add("uButtonGrey"));document.getElementById(d+"_tr").classList.contains("uButtonGreen")&&(document.getElementById(d+"_tr").classList.remove("uButtonGreen"),document.getElementById(d+
"_tr").classList.add("uButtonGrey"));document.getElementById(d+"_sq").classList.contains("uButtonGreen")&&(document.getElementById(d+"_sq").classList.remove("uButtonGreen"),document.getElementById(d+"_sq").classList.add("uButtonGrey"));document.getElementById(d+"_sw").classList.contains("uButtonGreen")&&(document.getElementById(d+"_sw").classList.remove("uButtonGreen"),document.getElementById(d+"_sw").classList.add("uButtonGrey"));a.classList.add("uButtonGreen");"si"===b[3]?C[b[1]].g.ma[b[2]].type=
"sine":"tr"===b[3]?C[b[1]].g.ma[b[2]].type="triangle":"sq"===b[3]?C[b[1]].g.ma[b[2]].type="square":"sw"===b[3]&&(C[b[1]].g.ma[b[2]].type="sawtooth")}}function Ue(a,b,d){return(440*Math.pow(2,(a-d)/b)).toFixed(3)}
function Ve(a,b){if(C[a]){var d=(new Date).getTime();if(d>C[a].g.A[b].Rb)if(document.getElementById("tg_"+a+"_"+b+"_sweepLoop").checked)C[a].g.A[b].zb=1E3*parseFloat(document.getElementById("tg_"+a+"_"+b+"_sweep").value),C[a].g.A[b].Ab=(new Date).getTime(),C[a].g.A[b].Rb=C[a].g.A[b].Ab+C[a].g.A[b].zb,C[a].g.A[b].xa.frequency.value=C[a].g.A[b].rb=document.getElementById("tg_"+a+"_"+(b-1)+"_now").value,C[a].g.A[b].Yb=document.getElementById("tg_"+a+"_"+b+"_now").value,C[a].g.A[b].Wa=parseInt(document.getElementById("tg_"+
a+"_"+(b-1)+"_vol").innerHTML,10),C[a].g.A[b].gain.gain.value=C[a].g.A[b].Wa/100,C[a].g.A[b].Tb=parseInt(document.getElementById("tg_"+a+"_"+b+"_vol").innerHTML,10);else{document.getElementById("tg_"+a+"_"+b+"_sweepGO").classList.remove("uButtonRed");document.getElementById("tg_"+a+"_"+b+"_sweepGO").classList.add("uButtonGreen");document.getElementById("tg_"+a+"_"+b+"_sweepGO").innerHTML="  GO!  ";C[a].g.A[b].xa.stop();return}C[a].g.A[b].Va=window.requestAnimationFrame(function(){Ve(a,b)});d-=C[a].g.A[b].Ab;
d/=C[a].g.A[b].zb;C[a].g.A[b].xa.frequency.value=Math.pow(2,Math.log(C[a].g.A[b].Yb/C[a].g.A[b].rb)/Math.log(2)*d+Math.log(C[a].g.A[b].rb)/Math.log(2)).toFixed(3);C[a].g.A[b].Wa!=C[a].g.A[b].Tb&&(C[a].g.A[b].gain.gain.value=(C[a].g.A[b].Wa+(C[a].g.A[b].Tb-C[a].g.A[b].Wa)*d)/100)}}function Te(a){for(var b in C[a].g.ma)C[a].g.ma[b].stop(),C[a].g.A[b]&&C[a].g.A[b].xa.stop()};window.tAT_Init=function(a){var b=C[a].Window;b.o=640;b.s=360;b.G=160;b.F=160;b.I="tATimer";b.S=1;b.ca=1;C[a].g={R:["",0],J:new Date,P:0,ra:0,paused:!0,hb:0,na:[],Pa:[],oa:[],ec:!1,eb:document.createElement("audio"),fb:document.createElement("audio"),fa:[!1,!1,!0,!0],Cb:"",ba:-1};We(a);C[a].g.eb.src="media/dw1.mp3";C[a].g.eb.src="media/dw1.ogg";C[a].g.fb.src="media/dw2.mp3";C[a].g.fb.src="media/dw2.ogg";C[a].D=[{Text:"Timers",v:[]},{Text:"Dates",v:[]},{Text:"Help",v:[{Text:"About Tillago Timer",j:function(){U("tillago-Tillago Timer_100")}}]}];
Xe(a);Ye(a);var d="",e="Years Months Weeks Days Hours Mins Secs".split(" ");for(b=0;7>b;b++)d+='<div id="'+a+"-"+b+'" style="float:left;overflow:hidden;text-align:center;">',d=4>b?d+('<button id="'+a+"_tATM_"+b+'" type="button" class="uButtons uButtonGrey" style="padding:0px 2px">'+e[b]+"</button>"):d+('<p style="margin:0;">'+e[b]+"</p>"),d+='<p id="'+a+"~"+b+'" class="tATnums">0</p></div>';b='<button id="'+a+'_tATB_addDate" type="button" class="uButtons uButtonGrey" style="padding:0px 6px;margin:4px;">Save&nbsp;Date</button><button id="'+
a+'_tATB_pp" type="button" class="uButtons uButtonGrey" style="transition:opacity 0.9s linear;opacity:0.3;padding:0px 6px;margin:4px;" >Pause</button><button id="'+a+'_tATB_reset" type="button" class="uButtons uButtonGrey" style="padding:0px 6px;margin:4px;" >Reset</button><button id="'+a+'_tATB_addTimer" type="button" class="uButtons uButtonGrey" style="padding:0px 6px;margin:4px;" >Save&nbsp;Timer</button><div id="'+a+'tillAgo" style="transition:opacity 0.9s linear;opacity:0.3;font-size:1.5em;">Time <span id="'+
a+'tus">since </span><span id="'+a+'~4a" class="tATnums" style="font-size:1em;">10</span>:<span id="'+a+'~5a" class="tATnums" style="font-size:1em;">10</span>:<span id="'+a+'~6a" class="tATnums" style="font-size:1em;">10</span> on <span id="'+a+'~3a" class="tATnums" style="font-size:1em;">Wed 20th </span><span id="'+a+'~1a" class="tATnums" style="font-size:1em;">May </span><span id="'+a+'~0a" class="tATnums" style="font-size:1em;">201 5</span></div><hr style="margin:4px 0px;">'+d;e=document.getElementById(a+
"Cont");d=document.getElementById(a+"Box");d.style.width=Q+"px";d.style.backgroundColor="#fff";d.style.textAlign="center";document.getElementById(a).style.left=Xa-F+"px";d.innerHTML=b+'<div style="height:4px;"></div>';document.getElementById(a+"-0").style.position="";document.getElementById(a+"-1").style.width=document.getElementById(a+"-1").offsetWidth+"px";C[a].g.Cb=document.getElementById(a+"-1").offsetWidth+2;for(b=0;7>b;b++)document.getElementById(a+"-"+b).style.width=C[a].g.Cb+"px";d.style.width=
"";d.style.height="";d.style.width=e.offsetWidth+F+"px";d.style.height=e.offsetHeight+"px";C[a].Window.o=e.offsetWidth;C[a].Window.s=e.offsetHeight;C[a].Window.G=Math.floor(C[a].Window.o/4);C[a].Window.F=Math.floor(C[a].Window.s/4);Ze(a);Yb(d);Zb(d);for(b=0;4>b;b++)document.getElementById(a+"_tATM_"+b).style.width=C[a].g.Cb-2+"px",1!=C[a].g.fa[b]&&(document.getElementById(a+"-"+b).style.opacity="0.33");b=(d.offsetWidth-7*C[a].g.Cb)/2;document.getElementById(a+"-0").style.left=b+"px";for(b=1;7>b;b++)document.getElementById(a+
"-"+b).style.top=document.getElementById(a+"-0").offsetTop+"px",document.getElementById(a+"-"+b).style.left=document.getElementById(a+"-"+(b-1)).offsetLeft+document.getElementById(a+"-"+(b-1)).offsetWidth+"px";d.style.width=.8*Q+"px";Nb(a);document.getElementById(a+"_tATB_pp").innerHTML="Start";C[a].g.hb=window.setInterval(function(){$e(a)},1E3)};
function af(a,b){var d=new Date;Ba&&(a=Ba);var e=a.split("~");a=parseFloat(e[0]);e=parseInt(e[1],10);var f=C[a].g.J.getTime();C[a].g.paused&&(f=0);var g=new Date(C[a].g.J.getTime());0==e?0<b?g.setFullYear(g.getFullYear()+1):g.setFullYear(g.getFullYear()-1):1==e?0<b?g.setMonth(g.getMonth()+1):g.setMonth(g.getMonth()-1):2==e?0<b?g.setDate(g.getDate()+7):g.setDate(g.getDate()-7):3==e?0<b?g.setDate(g.getDate()+1):g.setDate(g.getDate()-1):4==e?0<b?g.setHours(g.getHours()+1):g.setHours(g.getHours()-1):
5==e?0<b?g.setMinutes(g.getMinutes()+1):g.setMinutes(g.getMinutes()-1):6==e&&(0<b?g.setSeconds(g.getSeconds()+1):g.setSeconds(g.getSeconds()-1));f-=C[a].g.J.getTime()-g.getTime();C[a].g.paused?(C[a].g.P-=f,C[a].g.J.setTime(d.getTime()-C[a].g.P)):C[a].g.J.setTime(f);$e(a)}
function We(a){var b=cb("TillAgo Timer");if(b){for(var d=b.split(P)[0].split(O),e=0;4>e;e++)C[a].g.fa[e]=!!d[e];d=b.split(P)[1].split(O);for(e in d){var f=d[e].split("\u2349");C[a].g.na[e]=new Date(Date.parse(f[0]));f[1]&&(C[a].g.Pa[e]=f[1])}C[a].g.na.pop();if(b.split(P)[2]){b=b.split(P)[2].split(O);for(e in b)C[a].g.oa[e]=parseInt(b[e],10);C[a].g.oa.pop()}else C[a].g.oa[0]=-18E4,C[a].g.oa[1]=-24E4}else C[a].g.na.push(new Date((new Date).getFullYear(),11,25)),C[a].g.oa[0]=-18E4,C[a].g.oa[1]=-24E4}
function bf(a){for(var b="",d=0;4>d;d++)C[a].g.fa[d]&&(b+=C[a].g.fa[d]),3>d&&(b+=O);b+=P;for(d in C[a].g.na)b+=C[a].g.na[d].toString(),C[a].g.Pa[d]&&(b+="\u2349"+C[a].g.Pa[d]),b+=O;b+=P;for(d in C[a].g.oa)b+=C[a].g.oa[d].toString()+O;(b+=P+P+P+P+P)&&Cc("TillAgo Timer",b)}
function cf(a){C[a].g.na.push(new Date(C[a].g.J.getTime()));var b=document.createElement("div");b.id=a+"cover";b.style.cssText="width:100%;height:100%;opacity:0;position:absolute;background:#FFF;transition:0.5s;";b.innerHTML='<p style="width:100%;text-align:center;">Add a title to this date?</p><input type="text" id="'+a+'_tATtitle" class="editEnable" style="width:66%;" autofocus="true"><button id="'+a+'_tATOK" class="uButtons uButtonGrey" type="button" style="margin-left:3%;margin-botton:4px;width:20%;">No</button>';
document.getElementById(a+"Box").appendChild(b);document.getElementById(a+"_tATtitle").addEventListener("keyup",function(){document.getElementById(a+"_tATtitle").value?(document.getElementById(a+"_tATOK").innerHTML="Save",C[a].g.Pa[C[a].g.na.length-1]=document.getElementById(a+"_tATtitle").value):(document.getElementById(a+"_tATOK").innerHTML="No",C[a].g.Pa[C[a].g.na.length-1]="")},!1);window.setTimeout(function(){document.getElementById(a+"cover").style.opacity=.9},50)}
function Ed(a){document.getElementById(a+"cover").style.opacity=0;window.setTimeout(function(){document.getElementById(a+"Box").removeChild(document.getElementById(a+"cover"))},500);Xe(a);bf(a)}
function Xe(a){var b=[],d;for(d in C[a].g.na)b[parseFloat(d)]={Text:'<span id="'+a+"_dt_"+d+'" style="position:relative;left:-5px;border-right:1px solid rgba(255,255,255,0.5);color:red;font-weight:bold;">&nbsp;&nbsp;&#150&nbsp;&nbsp;</span>&nbsp;'+(C[a].g.Pa[d]?C[a].g.Pa[d]:C[a].g.na[d].toDateString()),j:function(){},Event:[a+"_dt_"+d,"mouseup",function(){var e=this.id.split("_"),f=e[0];delete C[f].g.na[e[2]];window.clearTimeout(x.ta);vb();ac();Xe(f);bf(f);C[f].g.J=new Date}],Gb:[a+"_"+d+"_gMenu_1",
"mouseup",function(){var e=this.id.split("_")[1];C[a].g.na[e]&&(C[a].g.J=new Date(C[a].g.na[e]),C[a].g.paused&&(C[a].g.P=new Date-C[a].g.J,document.getElementById(a+"_tATB_pp").innerHTML="Pause"),C[a].g.paused=!1,document.getElementById(a+"tillAgo").style.opacity="1",document.getElementById(a+"_tATB_pp").style.opacity="1",$e(a))}]};0<b.length&&(C[a].D[1].v=b)}
function df(a,b,d,e){isNaN(e)&&(e=0);b<d?(C[a].g.fa[0]&&(b=new Date(d.getTime()-e)),a=new Date(d.getTime()),d=new Date(b.getTime())):(C[a].g.fa[0]&&(b=new Date(d.getTime()+e)),a=new Date(b.getTime()),d=new Date(d.getTime()));b=a.getMonth()-d.getMonth()+12*(a.getFullYear()-d.getFullYear());a.setMonth(a.getMonth()-b);e=new Date(a.getFullYear(),d.getMonth(),a.getDate(),a.getHours(),a.getMinutes(),a.getSeconds(),a.getMilliseconds());e<d?(b--,e.setMonth(e.getMonth()+1),a=e.getTime()-d.getTime()):a=a.getTime()-
d.getTime();0>a&&(a=-a);return[b,a]}function ef(a,b){if(a<b){var d=new Date(b.getTime());b=new Date(a.getTime())}else d=new Date(a.getTime()),b=new Date(b.getTime());a=d.getFullYear()-b.getFullYear();d.setFullYear(d.getFullYear()-a);var e=new Date(b.getFullYear(),d.getMonth(),d.getDate(),d.getHours(),d.getMinutes(),d.getSeconds(),d.getMilliseconds());e<b?(a--,e.setFullYear(e.getFullYear()+1),d=e.getTime()-b.getTime()):d=d.getTime()-b.getTime();0>d&&(d=-d);return[a,d]}
function ed(a){var b=y.m;Ba&&0<b.length&&0<C[b].g.R[0].length?(document.getElementById(Ba),a=a.clientY,a-5>C[b].g.R[1]?(af(C[b].g.R[0],-1),C[b].g.R[1]=a):a+5<C[b].g.R[1]&&(af(C[b].g.R[0],1),C[b].g.R[1]=a),C[b].g.ba=-2,Xc(b),window.setTimeout(function(){Ba||(C[b].g.ba=-1)},1E3)):Ba=!1}function od(a){""!=a&&(window.setTimeout(function(){C[parseFloat(a)].g.ba=-1},1E3),C[a].g.R[0]="",C[a].g.R[1]=0,Ba=!1,jd())}
function Dd(a){var b=a.split("_");"tATB"===b[1]?"addDate"===b[2]?cf(b[0]):"pp"===b[2]?ff(b[0]):"reset"===b[2]?Ze(b[0]):"addTimer"===b[2]&&(a=b[0],C[a].g.oa.push(C[a].g.P),Ye(a),bf(a)):"tATM"===b[1]&&(a=a.split("_"),0==C[a[0]].g.fa[a[2]]?document.getElementById(a[0]+"-"+a[2]).style.opacity="1":(document.getElementById(a[0]+"-"+a[2]).style.opacity="0.33",document.getElementById(a[0]+"~"+a[2]).innerHTML="0"),C[a[0]].g.fa[a[2]]=!C[a[0]].g.fa[a[2]],$e(a[0]),bf(a[0]))}
function Id(a,b){C[parseFloat(a)].g.ba=-2;Xc(parseFloat(a));window.setTimeout(function(){C[parseFloat(a)].g.ba=-1},1E3);af(a,b)}function Ze(a){C[a].g.J=new Date;C[a].g.P=0;C[a].g.paused||(C[a].g.paused=!0,document.getElementById(a+"_tATB_pp").innerHTML="Start");$e(a);gf(a,C[a].g.J)}
function ff(a){C[a].g.paused=!C[a].g.paused;C[a].g.paused?(C[a].g.P=new Date-C[a].g.J,document.getElementById(a+"_tATB_pp").innerHTML="Start",document.getElementById(a+"tillAgo").style.opacity="0.6",document.getElementById(a+"_tATB_pp").style.opacity="1"):(document.getElementById(a+"_tATB_pp").innerHTML="Pause",document.getElementById(a+"tillAgo").style.opacity="1",document.getElementById(a+"_tATB_pp").style.opacity="1",window.setTimeout(function(){Ba||(C[a].g.ba=-1)},1E3));$e(a)}
function hf(a){var b=new Date,d=new Date(b.getTime()+C[a].g.ra),e="",f=ef(d,b);0<f[0]&&(e+=f[0]+" Yrs, ");C[a].g.ra=f[1];f=df(a,d,b,C[a].g.ra);0<f[0]&&(e+=f[0]+" Mths, ");C[a].g.ra=f[1];6048E5<C[a].g.ra&&(e+=jf(a,6048E5)+" Wks, ");864E5<C[a].g.ra&&(e+=jf(a,864E5)+" Dys, ");36E5<C[a].g.ra&&(e+=jf(a,36E5)+" Hrs, ");6E4<C[a].g.ra&&(e+=jf(a,6E4)+" Mins, ");return e+=jf(a,1E3)+" Secs"}
function Ye(a){var b=[],d;for(d in C[a].g.oa)C[a].g.ra=-C[a].g.oa[d],b[parseFloat(d)]={Text:'<span id="'+a+"_tm_"+d+'" style="position:relative;left:-5px;border-right:1px solid rgba(255,255,255,0.5);color:red;font-weight:bold;">&nbsp;&nbsp;&#150&nbsp;&nbsp;</span>&nbsp;'+hf(a),j:function(){},Event:[a+"_tm_"+d,"mouseup",function(){var e=this.id.split("_"),f=e[0];delete C[f].g.oa[e[2]];window.clearTimeout(x.ta);vb();ac();Ye(f);bf(f)}],Gb:[a+"_"+d+"_gMenu_0","mouseup",function(){C[a].g.P=C[a].g.oa[this.id.split("_")[1]];
C[a].g.paused=!0;document.getElementById(a+"_tATB_pp").innerHTML="Start";document.getElementById(a+"tillAgo").style.opacity="0.3";document.getElementById(a+"_tATB_pp").style.opacity="0.5";C[a].g.J.setTime((new Date).getTime()-C[a].g.P);$e(a)}]};0<b.length&&(C[a].D[0].v=b)}function kf(a,b){var d=Math.floor(C[a].g.P/b);C[a].g.P-=b*d;return d}function jf(a,b){var d=Math.floor(C[a].g.ra/b);C[a].g.ra-=b*d;return d}
function $e(a){if(C[a]){var b=new Date(1E3*Math.round((new Date).getTime()/1E3));C[a].g.paused?(C[a].g.J.setTime(b.getTime()-C[a].g.P),.3==document.getElementById(a+"tillAgo").style.opacity?(document.getElementById(a+"tillAgo").style.opacity=.6,document.getElementById(a+"_tATB_pp").style.opacity=.8):(document.getElementById(a+"tillAgo").style.opacity=.3,document.getElementById(a+"_tATB_pp").style.opacity=.5)):C[a].g.P=b>=C[a].g.J?b-C[a].g.J:C[a].g.J-b;b>=C[a].g.J?document.getElementById(a+"tus").innerHTML=
"since ":document.getElementById(a+"tus").innerHTML="until ";document.getElementById(a+"~0a").innerHTML=C[a].g.J.getFullYear();document.getElementById(a+"~1a").innerHTML="Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" ")[C[a].g.J.getMonth()]+" ";document.getElementById(a+"~3a").innerHTML=Kb("Sun Mon Tue Wed Thu Fri Sat".split(" ")[C[a].g.J.getDay()])+" "+C[a].g.J.getDate()+" ";document.getElementById(a+"~4a").innerHTML=Kb(C[a].g.J.getHours());document.getElementById(a+"~5a").innerHTML=Kb(C[a].g.J.getMinutes());
document.getElementById(a+"~6a").innerHTML=Kb(C[a].g.J.getSeconds());b.getTime()+1E3>C[a].g.J.getTime()?document.getElementById(a+"_tATB_addTimer").className="uButtonDisabled":document.getElementById(a+"_tATB_addTimer").className="uButtons uButtonGrey";if(C[a].g.paused){var d=C[a].g.P;0>C[a].g.P&&(C[a].g.P=-C[a].g.P);gf(a,b);C[a].g.P=d}else document.getElementById(a+"_tATB_addTimer").className="uButtonDisabled",gf(a,b)}}
function gf(a,b){if(C[a].g.fa[0]){var d=ef(C[a].g.J,b);document.getElementById(a+"~0").innerHTML=d[0];C[a].g.P=d[1]}C[a].g.fa[1]&&(d=df(a,C[a].g.J,b,C[a].g.P),document.getElementById(a+"~1").innerHTML=d[0],C[a].g.P=d[1]);0==C[a].g.fa[1]&&0==C[a].g.fa[0]&&C[a].g.ec&&(C[a].g.P+=6E4*C[a].g.J.getTimezoneOffset());C[a].g.fa[2]&&(document.getElementById(a+"~2").innerHTML=kf(a,6048E5));C[a].g.fa[3]&&(document.getElementById(a+"~3").innerHTML=kf(a,864E5));document.getElementById(a+"~4").innerHTML=Kb(kf(a,
36E5));document.getElementById(a+"~5").innerHTML=Kb(kf(a,6E4));document.getElementById(a+"~6").innerHTML=Kb(kf(a,1E3));"0"!=document.getElementById(a+"~0").innerHTML||"0"!=document.getElementById(a+"~1").innerHTML||"0"!=document.getElementById(a+"~2").innerHTML||"0"!=document.getElementById(a+"~3").innerHTML||"00"!=document.getElementById(a+"~4").innerHTML||"00"!=document.getElementById(a+"~5").innerHTML||"00"!=document.getElementById(a+"~6").innerHTML||-1!==C[a].g.ba||C[a].g.paused||(C[a].g.ba=0,
lf(a))}function lf(a){!C[a]||0>C[a].g.ba||(window.setTimeout(function(){lf(a)},1E3),Xc(a),3>C[a].g.ba?C[a].g.eb.play():3==C[a].g.ba?C[a].g.fb.play():C[a].g.ba=4,C[a].g.ba++,4===C[a].g.ba&&(C[a].g.ba=0))}function Xc(a){C[a].g.eb.pause();C[a].g.eb.currentTime=0;C[a].g.fb.pause();C[a].g.fb.currentTime=0};window.tt_Init=function(a){var b=C[a].Window;b.I="TeaTimer";b.S=1;b.ca=1;C[a].g={sb:0,ub:0,Nb:0,W:0,gb:!1,ended:!1,ib:document.createElement("audio"),R:["",0],hb:0,startTime:0,Mb:!1};C[a].g.ib.setAttribute("src","media/SingleBlip.ogg");document.getElementById(a);var d=document.getElementById(a+"Cont");b=document.getElementById(a+"Box");b.style.padding="4px";b.style.backgroundColor="#fff";b.innerHTML='<div id="'+a+'_lHs" class="TTDescribed" style="text-align:right;">Hours<div id="'+a+'_Hs" class="TTnums" style="text-align:right;">0</div></div><div id="'+
a+'_lMs" class="TTDescribed" style="text-align:center;">Minutes<div id="'+a+'_Ms" class="TTnums" style="text-align:center;">:00:</div></div><div id="'+a+'_lSs" class="TTDescribed" style="text-align:left;">Seconds<div id="'+a+'_Ss" class="TTnums" style="text-align:left;">00</div></div><div id="'+a+'_SrtStp" class="TTbutton" style="background-color:#4AF;font-size:2.5em;">&#9654;</div>';Qc(a);Yb(b);C[a].Window.o=d.offsetWidth;C[a].Window.s=d.offsetHeight;C[a].Window.G=160;C[a].Window.F=0;Zb(b);d=C[a].Window.o/
C[a].Window.s;b.style.width=Math.round(.8*Q)+"px";b.style.height=Math.round(Math.round(.8*Q)/d)+"px";Nb(a);C[a].g.hb=window.setInterval(function(){C[a]&&(C[a].g.gb&&(C[a].g.W--,0>C[a].g.W?(document.getElementById(a+"_SrtStp").style.backgroundColor="#4AF",document.getElementById(a+"_SrtStp").innerHTML="&#9654",C[a].g.gb=C[a].g.Mb=!1,C[a].g.W=0,document.getElementById(a+"_Hs").innerHTML="&#160;D",document.getElementById(a+"_Ms").innerHTML="&#160;on",document.getElementById(a+"_Ss").innerHTML="e!",document.getElementById(a+
"_lHs").innerHTML="&#160;&#160;&#160;&#160;Click",document.getElementById(a+"_lMs").innerHTML="&#160;&#160;&#160;&#160;&#160;&#160;&#160;To",document.getElementById(a+"_lSs").innerHTML="Reset&#160;&#160;",C[a].g.ended=!0,mf(a)):Qc(a)),1==C[a].g.ended&&mf(a))},1E3)};
function Qc(a){var b=C[a].g.W;3599<b?(C[a].g.sb=Math.floor(b/3600),b-=Math.floor(3600*C[a].g.sb)):C[a].g.sb=0;59<b?(C[a].g.ub=Kb(Math.floor(b/60)),b-=Math.floor(60*C[a].g.ub)):C[a].g.ub="00";0<b?C[a].g.Nb=Kb(b):C[a].g.Nb="00";document.getElementById(a+"_Hs").innerHTML=C[a].g.sb+"";document.getElementById(a+"_Ms").innerHTML=":"+C[a].g.ub+":";document.getElementById(a+"_Ss").innerHTML=C[a].g.Nb}
function Nd(a,b){za&&(a=za);var d=a.split("_");a=d[0];d=d[1];"Hs"==d?0<b?C[a].g.W+=3600:0>b&&(C[a].g.W-=3600):"Ms"==d?0<b?C[a].g.W+=60:0>b&&(C[a].g.W-=60):"Ss"==d&&(0<b?C[a].g.W++:0>b&&C[a].g.W--);35999<C[a].g.W?C[a].g.W=35999:0>C[a].g.W&&(C[a].g.W=0);Qc(a)}function fd(a,b){0<C[b].g.R[0].length&&(za?document.getElementById(za):Gc(a),a=a.clientY,a-5>C[b].g.R[1]?(Nd(C[b].g.R[0],-1),C[b].g.R[1]=a):a+5<C[b].g.R[1]&&(Nd(C[b].g.R[0],1),C[b].g.R[1]=a),Qc(b))}
function nd(a){""!=a&&(C[a].g.R[0]="",C[a].g.R[1]=0,za=!1,jd())}function mf(a){C[a].g.ib.pause();C[a].g.ib.currentTime=0;C[a].g.ib.play()};window.wc_Init=function(a){if(a==parseInt(a,10))nf(a);else{var b=document.getElementById(a+"Cont"),d=document.getElementById(a+"Box");d.style.backgroundColor="#fff";var e=C[a].Window;e.I="WCalc";e.S=1;e.ca=1;d.innerHTML='<table id="'+a+'fig1" style="text-align:center;"><tr><td>Personal Allowance:</td><td>\u00a3<input id="'+a+'PA" type="text" size="8" class="editEnable"/></td></tr><tr><td>PA Income Limit:</td><td>\u00a3<input id="'+a+'IL" type="text" size="8" class="editEnable"/></td></tr><tr><td>Basic Limit:</td><td>\u00a3<input id="'+
a+'BL" type="text" size="8" class="editEnable"/></td><td>Basic Rate:</td><td><input id="'+a+'BR" type="text" size="3" class="editEnable"/>%</td></tr><tr><td>Higher Limit:</td><td>\u00a3<input id="'+a+'HL" type="text" size="8" class="editEnable"/></td><td>Higher Rate:</td><td><input id="'+a+'HR" type="text" size="3" class="editEnable"/>%</td></tr><tr><td>Aditional Limit:</td><td>\u00a3<input id="'+a+'AL" type="text" size="8" class="editEnable"/></td><td>Additional Rate:</td><td><input id="'+a+'AR" type="text" size="3" class="editEnable"/>%</td></tr><tr><td>NI Pri Threshold:</td><td>\u00a3<input id="'+
a+'PT" type="text" size="8" class="editEnable"/></td><td>Primary Rate:</td><td><input id="'+a+'PR" type="text" size="3" class="editEnable"/>%</td></tr><tr><td>NI Upper Limit:</td><td>\u00a3<input id="'+a+'UL" type="text" size="8" class="editEnable"/></td><td>Upper Rate:</td><td><input id="'+a+'UR" type="text" size="3" class="editEnable"/>%</td></tr></table><br><div id="'+a+'fig2" style="text-align:center;"><a href="https://www.gov.uk/income-tax-rates" target="_blank">gov.uk: Income Tax Rates</a> | <a href="https://www.gov.uk/national-insurance-contributions-for-employers/national-insurance-contribution-rates" target="_blank">gov.uk: National Insurance Rates</a><br><br><button id="'+
a+'_wc_UPFigures" type="button" class="uButtons uButtonGrey">Apply&nbsp;new&nbsp;Rates</button><br><br></div>';d.style.height=d.offsetHeight+"px";Yb(d);Zb(d);C[a].Window.o=b.offsetWidth;C[a].Window.s=b.offsetHeight;C[a].Window.G=Math.floor(C[a].Window.o/3);C[a].Window.F=Math.floor(C[a].Window.s/3);document.getElementById(a+"Title").innerHTML="Figures for 2015/16";e=parseInt(a,10);document.getElementById(a+"PA").value=C[e].g.cb;document.getElementById(a+"IL").value=C[e].g.ab;document.getElementById(a+
"BR").value=C[e].g.Za;document.getElementById(a+"BL").value=C[e].g.za;document.getElementById(a+"HR").value=C[e].g.lb;document.getElementById(a+"HL").value=C[e].g.Ia;document.getElementById(a+"AL").value=">"+C[e].g.Ia;document.getElementById(a+"AR").value=C[e].g.Db;document.getElementById(a+"PT").value=C[e].g.Jb;document.getElementById(a+"PR").value=C[e].g.vb;document.getElementById(a+"UL").value=C[e].g.Kb;document.getElementById(a+"UR").value=C[e].g.Fb;a=b.offsetWidth/b.offsetHeight;d.style.width=
Math.round(.8*Q)+"px";d.style.height=Math.round(b.offsetWidth/a)+"px"}};
function nf(a){var b=C[a].Window;b.I="WCalc";b.S=1;b.ca=1;C[a].ea=[{Text:"Reset Calculator",j:function(){of(a)}}];C[a].D=[{Text:"Reset",v:[{Text:"Reset Calculator",j:function(){of(a)}}]}];b=document.getElementById(a+"Cont");var d=document.getElementById(a+"Box");pf(a);of(a);C[a].Window.o=b.offsetWidth;C[a].Window.s=b.offsetHeight;C[a].Window.G=Math.floor(C[a].Window.o/2);C[a].Window.F=Math.floor(C[a].Window.s/2);var e=b.offsetWidth/b.offsetHeight;d.style.width=Math.round(.8*Q)+"px";d.style.height=
Math.round(b.offsetWidth/e)+"px"}function Jd(a,b){C[b].g.Ib=a;C[b].g.$a=parseFloat(document.getElementById(b+"Gross").value);qf(b)}function Kd(a,b){C[b].g.bb=a;qf(b)}function rf(a){document.getElementById(a+"Combo1").selectedIndex=0;C[a].g.Ib=0;C[a].g.Hb=parseFloat(document.getElementById(a+"Hours").value);C[a].g.Lb=parseFloat(document.getElementById(a+"Wage").value);C[a].g.$a=parseFloat(C[a].g.Hb*C[a].g.Lb);document.getElementById(a+"Gross").value=C[a].g.$a.toFixed(2);qf(a)}
function qf(a){C[a].g.ga=0;var b=C[a].g.$a*Qa[C[a].g.Ib];b>C[a].g.ab?2*C[a].g.cb<=b-C[a].g.ab?C[a].g.Ga=0:C[a].g.Ga=(2*C[a].g.cb-(b-C[a].g.ab)/2).toFixed(2):C[a].g.Ga=C[a].g.cb;b-=C[a].g.Ga;b+C[a].g.Ga<C[a].g.Ga?C[a].g.ga=0:b<=C[a].g.za?C[a].g.ga=C[a].g.Za/100*b:b>C[a].g.za&&b<=C[a].g.Ia?(C[a].g.ga=C[a].g.lb/100*(b-C[a].g.za),C[a].g.ga+=C[a].g.Za/100*C[a].g.za):b>C[a].g.Ia&&(C[a].g.ga=C[a].g.Db/100*(b-(C[a].g.Ia+C[a].g.za)),C[a].g.ga+=C[a].g.lb/100*C[a].g.Ia,C[a].g.ga+=C[a].g.Za/100*C[a].g.za);b+=
C[a].g.Ga;var d=52*C[a].g.Jb,e=52*C[a].g.Kb;b<=d?C[a].g.Aa=0:b>d&&b<=e?C[a].g.Aa=C[a].g.vb/100*(b-d):b>e&&(C[a].g.Aa=C[a].g.Fb/100*(b-e),C[a].g.Aa+=C[a].g.vb/100*(e-d));C[a].g.Ub=b-(C[a].g.Aa+C[a].g.ga);document.getElementById(a+"tax").value=(C[a].g.ga/Qa[C[a].g.bb]).toFixed(2);document.getElementById(a+"ni").value=(C[a].g.Aa/Qa[C[a].g.bb]).toFixed(2);document.getElementById(a+"deds").value=((C[a].g.ga+C[a].g.Aa)/Qa[C[a].g.bb]).toFixed(2);document.getElementById(a+"net").value=(C[a].g.Ub/Qa[C[a].g.bb]).toFixed(2)}
function pf(a){var b=document.getElementById(a+"Box");C[a].g.Eb=!0;b.style.padding="4px";b.style.backgroundColor="#fff";b.innerHTML='<div id="'+a+'Input" style="text-align:center;"><input id="'+a+'Hours" type="text" class="editEnable" style="width:3em;"/><span id="'+a+'t1" class="labScale" style="top:0px;">&nbsp;Hours&nbsp;per&nbsp;Week&nbsp;at&nbsp;</span><span>\u00a3</span><input id="'+a+'Wage" type="text" class="editEnable" style="width:3em;"/><span id="'+a+'t2" class="labScale" style="">&nbsp;per&nbsp;Hour</span><br><span id="'+
a+'t3" class="labScale">---------------------------&nbsp;OR&nbsp;---------------------------</span><br><span id="'+a+'t4" class="labScale">Gross&nbsp;Wage&nbsp;</span><span>\u00a3</span><input id="'+a+'Gross" type="text" class="editEnable" style="width:5em;"/><span id="'+a+'t5" class="labScale">&nbsp;per&nbsp;</span><select id="'+a+'Combo1" class="editEnable" style=""><option class="wageC" >Week</option><option class="wageC" >Fortnight</option><option class="wageC" >4 Weeks</option><option class="wageC" >Month</option><option class="wageC" >Quarter</option><option class="wageC" >6 Months&#160;</option><option class="wageC" >Year</option></select></div><div id="'+
a+'NET" class="editEnable" style ="box-sizing:border-box;border:0;float:left;margin-top:4px;margin-right:4px;padding:2px 6px;"><p id="'+a+'t6" class="labScale" style="clear:both;float:left;margin:0;padding:0;text-align:center;">Result&nbsp;per</p><span style="color:#fff;">\u00a3</span><select id="'+a+'Combo2" class="editEnable" style=""><option class="wageC" >Week</option><option class="wageC" >Fortnight </option><option class="wageC" >4 Weeks</option><option class="wageC" >Month</option><option class="wageC" >Quarter</option><option class="wageC" >6 Months&#160;</option><option class="wageC" >Year</option></select><br><p id="'+
a+'t7" class="labScale" style="clear:both;float:left;margin:0;padding:0;text-align:center;">Tax&nbsp;paid</p><span>\u00a3</span><input id="'+a+'tax" type="text" class="editEnable" value="0"/><br><p id="'+a+'t8" class="labScale" style="clear:both;float:left;margin:0;padding:0;text-align:center;">NI&nbsp;paid</p><span>\u00a3</span><input id="'+a+'ni" type="text" class="editEnable" value="0"/><br><p id="'+a+'t9" class="labScale" style="clear:both;float:left;margin:0;padding:0;text-align:center;">Total</p><span>\u00a3</span><input id="'+
a+'deds" type="text" class="editEnable" value="0"/></div><div id="'+a+'eNET" class="editEnable" style ="box-sizing:border-box;border:0;float:left;margin-top:4px;padding:2px 6px;"><button id="'+a+'_wc_Figs" type="button" class="uButtons uButtonGrey" style="width:92%;margin:8% 4%;">View/Edit figures</button><br><span id="'+a+'la" class="labScale" style="font-weight:bold;margin:1%;">&nbsp;Net&nbsp;Wage&nbsp;\u00a3</span><input id="'+a+'net" type="text" class="editEnable" style="font-weight:bold;width:6em;" value="0"/></div>';
document.getElementById(a+"Title").innerHTML="Wage Calculator (2014/15)";document.getElementById(a+"Combo1").addEventListener("change",function(){Jd(this.selectedIndex,a)},!1);document.getElementById(a+"Combo2").addEventListener("change",function(){Kd(this.selectedIndex,a)},!1);document.getElementById(a+"Hours").addEventListener("keyup",function(){rf(a)},!1);document.getElementById(a+"Wage").addEventListener("keyup",function(){rf(a)},!1);document.getElementById(a+"Gross").addEventListener("keyup",
function(){C[a].g.$a=parseFloat(document.getElementById(a+"Gross").value);qf(a)},!1);document.getElementById(a+"tax").style.width=document.getElementById(a+"ni").style.width=document.getElementById(a+"deds").style.width=document.getElementById(a+"Combo2").clientWidth-5+"px";document.getElementById(a+"t7").style.width=document.getElementById(a+"t8").style.width=document.getElementById(a+"t9").style.width=document.getElementById(a+"t6").clientWidth+"px";document.getElementById(a+"eNET").style.height=
document.getElementById(a+"NET").offsetHeight+"px";b.style.height=b.offsetHeight+"px";b.style.width=b.offsetWidth+"px";Yb(b);Zb(b);document.getElementById(a+"eNET").style.padding=document.getElementById(a+"NET").style.padding="2px 0px"}
function xd(a){var b=parseInt(a,10);C[b].g.cb=document.getElementById(a+"PA").value;C[b].g.ab=document.getElementById(a+"IL").value;C[b].g.Za=document.getElementById(a+"BR").value;C[b].g.za=document.getElementById(a+"BL").value;C[b].g.lb=document.getElementById(a+"HR").value;C[b].g.Ia=document.getElementById(a+"HL").value;C[b].g.Db=document.getElementById(a+"AR").value;C[b].g.Jb=document.getElementById(a+"PT").value;C[b].g.vb=document.getElementById(a+"PR").value;C[b].g.Kb=document.getElementById(a+
"UL").value;C[b].g.Fb=document.getElementById(a+"UR").value;pf(b);pc(a)}function of(a){C[a].g={Ib:0,bb:0,Hb:37.5,Lb:6.5,Ga:"",$a:0,Ub:"",ga:"",Aa:"",cb:10600,ab:1E5,Za:20,za:31785,lb:40,Ia:15E4,Db:45,Jb:155,vb:12,Kb:815,Fb:2,Eb:!0};document.getElementById(a+"Hours").value=C[a].g.Hb;document.getElementById(a+"Wage").value=C[a].g.Lb;rf(a)};
