/*
 Copyright © 2023 Stewart J. Robinson (AKA StewVed, Ved)
 To show your appreciation of my work, feel free to talk about, and link to my website(s)
 If you wish to copy/use code from [any part of] my website(s), please contact me. Thankyou.
 Adapted from my projects on GitHub, which in turn were adapted from the original loader for the webtop!
*/
var aa=window.fVer,ba=[],ca=0,c=[],da=0;aa?(ea(),fa()):(ca=2,ha(1));
function ea(){"serviceWorker"in navigator&&navigator.serviceWorker.register("sw.js").then(function(a){a.active&&(da="a");a.addEventListener("updatefound",function(){a.installing.addEventListener("statechange",function(b){"installed"===b.target.state?"a"===da&&h("updating webtop..."):"activated"===b.target.state&&(da="a"===da?"u":"i",h("i"))})});"a"===da&&a.update()}).catch(function(a){da="e";console.log("ServiceWorker registration failed: ",a)})}
function fa(){var a=[];ba=[];var b=aa?"231125.css":"all.css";a.push(b);b=aa?aa+"_1.js":"apps/aWebtop.js";a.push(b);a.push("images/imgSprites_160429.png");for(var d of a)ba.push(d.replace(/\./,"").replace(/\//,""));ia(a[0],"style",ba[0]);ja(a[1],"script","Core Webtop");ja(a[2],"img","Images")}
function ja(a,b,d){var e=a.replace(/\./,"").replace(/\//,"");ka(e,d);c[e]=[];c[e].text=d;c[e].time=performance.now();c[e].bc=performance.now();c[e].size=0;c[e].speed=2;c[e].total=0;c[e].cc=1;d=new XMLHttpRequest;d.open("GET",a,!0);"img"===b&&(d.responseType="blob");d.addEventListener("loadend",function(){if(c[e].cc){var f=document.createElement(b);f.id=e;"img"===b?(window.URL.revokeObjectURL(f.src),f.src=window.URL.createObjectURL(new Blob([this.response],{type:"image/png"}))):f.innerHTML=this.responseText;
document.head.appendChild(f)}},!1);d.addEventListener("error",function(){c[e].cc=0;ia(a,b,e)},!1);d.addEventListener("progress",function(f){la(f,e)},!1);d.send();c[e].frame=window.requestAnimationFrame(function(){ma(e)})}
function ia(a,b,d){var e=document.getElementsByTagName("script")[0],f=document.createElement(b);"link"===b||"style"===b?(f=document.createElement("link"),f.type="text/css",f.rel="stylesheet",f.href=a,na(f)):f.src=a;f.id=d+"l";f.addEventListener("load",function(){"l"===this.id.slice(-1)&&(this.id=this.id.slice(0,-1));oa()});e.parentNode.insertBefore(f,e)}function na(a){a.sheet?("l"===a.id.slice(-1)&&(a.id=a.id.slice(0,-1)),oa()):window.requestAnimationFrame(function(){na(a)})}
function ka(a,b){document.getElementById("Load")&&(a='<div id="'+a+'C" class="loadC"><div id="'+a+'Pi" class="loadPi"></div><div id="'+a+'Pc" class="loadPc">'+b+" (...)</div></div>",document.getElementById("Load").innerHTML+=a,pa())}
function la(a,b){if(document.getElementById(b+"Pi"))if(a.lengthComputable){c[b].Ob&&(c[b].Ob=0,window.clearInterval(c[b].Xb),c[b].Xb=null);document.getElementById(b+"Pi").classList.remove("loadVV");var d=performance.now();c[b].speed=(a.loaded-c[b].size)/(d-c[b].time);c[b].time=d;c[b].size=a.loaded;c[b].total||(c[b].total=a.total);a=a.loaded/a.total*100;document.getElementById(b+"Pi").style.width=a+"%";document.getElementById(b+"Pc").innerHTML=c[b].text+" ("+a.toFixed(1)+"%)"}else c[b].Ob||(c[b].Ob=
1,c[b].Xb=window.setInterval(function(){oa()},500)),document.getElementById(b+"Pi").classList.add("loadVV")}
function ma(a){if(document.getElementById(a+"Pi")){var b=parseFloat(document.getElementById(a+"Pi").style.width||0);if(100>b){if(c[a].total){var d=performance.now();b+=parseFloat(parseFloat(c[a].speed*(d-c[a].bc))/c[a].total*100);document.getElementById(a+"Pi").style.width=b+"%";document.getElementById(a+"Pc").innerHTML=c[a].text+" ("+b.toFixed(1)+"%)"}else document.getElementById(a+"Pc").innerHTML=c[a].text+" (...)",document.getElementById(a+"Pi").classList.add("loadVV");c[a].bc=d;c[a].frame=window.requestAnimationFrame(function(){ma(a)})}else document.getElementById(a+
"C").style.transition="1s",document.getElementById(a+"C").style.opacity=0,window.setTimeout(function(){document.getElementById(a+"C")&&(document.getElementById(a+"C").parentNode.removeChild(document.getElementById(a+"C")),pa());oa()},1E3)}}
function oa(){if(document.getElementById("Load")){for(var a of ba)if(!document.getElementById(a))return;2==ca?(ca=0,fa()):ca||(ca=1,document.getElementById("Load").parentNode.removeChild(document.getElementById("Load")),document.getElementById(ba[2]).id="spriteMain",qa())}}function pa(){document.getElementById("Load").style.top=(window.innerHeight-document.getElementById("Load").offsetHeight)/2+"px"}
function ha(a){1===a?(ba="aWinStorage aWinIndex aWinLaunchers aWinWallpaper aWinDEChooser aWinEvents aWinzErrorHandler aWinThemeChooser aWinToolTip".split(" "),ba.push()):2===a&&(ba="bb bp calsPerGrams dialogue dm feedBack saveVsLoan screen iFramedApp soundGenerator tAT tt wc".split(" "));for(var b of ba)ia("apps/"+b+".js","script",b)}
function h(a){if(!document.getElementById("Wallpaper"))window.setTimeout(function(){h(a)},1E3);else if(a){var b=document.createElement("div");b.id="NotyCont"+k.length;b.className="notifier "+q[r].wa;var d='<img id="notifyClose'+k.length+'" class="Button ButtonClo" style="background-image:url('+t.src+');position:absolute;left:0px;top:0px;margin:0;" '+u+">";a=a.replace(/ id="_/gi,' id="'+k.length+"_");b.innerHTML=d+a;document.getElementById("Wallpaper").appendChild(b);d=document.getElementById("NotyCont"+
k.length);if("RizzsXmasTimer"===a.slice(144,158)){d.style.border="4px solid rgb(255,0,0)";d.style.width=d.offsetWidth+32+"px";var e=new Date((new Date).getFullYear(),11,25);new Date>e&&e.setFullYear(e.getFullYear()+1);document.getElementById("RizzsXmasTimer").innerHTML=ra(e)}e=document.getElementById("Wallpaper").offsetWidth-d.offsetWidth-4;0>e&&(e=0,d.style.width=document.getElementById("Wallpaper").offsetWidth+"px");d.style.left=e+"px";k.push(k.length);sa();b.style.opacity=.9}};