/*
 WEBTOP Copyright © 2023 Stewart J. Robinson (AKA StewVed, Ved)
 To show your appreciation of my work, feel free to talk about, and link to my website(s)
 If you wish to copy/use code from [any part of] my website(s), please contact me. Thankyou.
*/
var ta,v,ua=0,va=0,k=[],x,wa,xa,y=[],ya=!1,za=!1,Ba=!1,Ca=[],Da=[],z=[],A={window:0,x:[0,0],y:[0,0]},B,Ea=!1,C=[],D=0,E=[],F=10,G={active:"none",Bb:"",Ya:""},Fa=0,Ga=0,H,I,J,K,Ha,La,Ma="",Na=!1,Oa="",Pa=0,L=-1,Qa=[365/7,365/14,365/28,12,4,2,1],Ra,Sa,N,Ta,Ua,Va,Wa,t,O="@#~",P="~#@",Q,Xa,Ya=!1,Za=document.exitFullscreen||document.mozCancelFullScreen||document.webkitExitFullscreen||document.msExitFullscreen,$a=document.documentElement.requestFullscreen||document.documentElement.mozRequestFullScreen||
document.documentElement.webkitRequestFullscreen||document.documentElement.msRequestFullscreen;
function qa(){t=document.getElementById("spriteMain");B='style="background:url('+t.src+")";ab[1].Text='<img class="imgSocs" '+B+' -146px -26px;"'+u+">Feedback / Contact Webapp";document.body.style.cursor="default";document.getElementById("Load")&&document.getElementById("Load").parentNode.removeChild(document.getElementById("Load"));bb();(r=cb("webtopTheme"))||(r=0);(v=cb("webtopStyle"))||(v="Ub");ta=cb("showErrors");db();eb();fb();gb(0);H=document.getElementById("pup");I=document.getElementById("pupc");
J=document.getElementById("pupD");K=document.getElementById("pupDc");Ha=document.getElementById("pupB");hb();window.setInterval(function(){hb()},1E3);ib();window.addEventListener("resize",ib);document.addEventListener("contextmenu",jb);window.addEventListener("wheel",kb);document.addEventListener("touchstart",lb);document.addEventListener("touchmove",mb);document.addEventListener("touchcancel",nb);document.addEventListener("touchend",nb);document.addEventListener("touchleave",nb);document.addEventListener("mousedown",
ob);document.addEventListener("mousemove",pb);document.addEventListener("mouseup",qb);document.addEventListener("dblclick",jb);document.addEventListener("keydown",rb);document.addEventListener("keyup",sb);window.addEventListener("gamepadconnected",tb);window.addEventListener("gamepaddisconnected",ub);vb();document.getElementById("UnityPanel").classList.add(q[r].ka);wb();aa?ja(aa+"_2.js","script","apps & games"):ha(2);ja(aa+"_3.js","script","Text (Changelogs, etc.)");document.getElementById("cpContact").outerHTML=
"Stewart Robinson"}function wb(){for(var a in R);document.getElementById("Wallpaper").style.opacity=1;window.setTimeout(function(){yb()},2200)}
function zb(a,b){var d='<img id="'+a+'appImg" class="winTitleIcon" ';" -"==R[C[a].Window.Y].u.slice(0,2)?(a=R[C[a].Window.Y].u.split(" "),d+='style="position:absolute;z-index:0;transition:opacity 1s;opacity:'+b+";left:4px;background-image: url("+t.src+");background-position:"+parseFloat(a[1])/2.75+"px "+parseFloat(a[2])/2.75+'px;"'):d+='style="background:center/contain no-repeat url('+R[C[a].Window.Y].u+');"';return d+u+">"}
function eb(){var a='<img id="Tl" class="lTriangle" '+B+' -119px -44px;left:58px;top:54px;"'+u+">",b;for(b in S)a+='<div id="C_'+T[S[parseFloat(b)]].l+'" class="LauncherContainer">',a+='<img id="T_'+T[S[parseFloat(b)]].l+'" class="lTriangle" '+B+' -131px -44px;"'+u+">",a+='<div id="D_'+T[S[parseFloat(b)]].l+'" class="LauncherIconBack" style="background-color:'+T[S[parseFloat(b)]].C+';"></div>',a+='<img id="L_'+T[S[parseFloat(b)]].l+'" class="LauncherIcon" ',a=" -"==T[S[parseFloat(b)]].u.slice(0,2)?
a+(B+T[S[parseFloat(b)]].u+';"'+u+">"):a+("style=\"background:center/contain no-repeat url('"+T[S[parseFloat(b)]].u+"');\""+u+">"),a+='<img id="Lc_'+T[S[parseFloat(b)]].l+'" class="LauncherIconCover ttElem" '+B+' -198px -26px;"'+u+">",a+="</div>";document.body.innerHTML+='<canvas id="backGround"></canvas><div id="Wallpaper" class="Wallpaper"><div id="winCover"></div><div id="pupB" class="ttElem"></div><div id="pup" class="ttElem"></div><div id="pupc" class="ttElem"></div><div id="pupD" class="ttElem"></div><div id="pupDc" class="ttElem"></div><div id="UnityPanel"><div id="UPTitle" class="winTitle" style="color: rgb(223,219,210);margin-left:8px;height:24px;transition:opacity 1s;"></div><div id="gMxTitle" style="position:absolute;overflow:hidden;cursor:default;"></div><div id="kTaskBar"><div id="b_0" style="height:32px;width:33px;background-color:transparant;position:relative;float:left;margin:0;padding:0;"> <img id="i_0" class="kTaskImg" style="background-size:180px;background-image:url('+
t.src+");background-position:"+.5*parseFloat(T[0].u.split(" ")[1])+"px "+.5*parseFloat(T[0].u.split(" ")[2])+'px;left:0px;width:36px;height:36px;margin:4px;"'+u+'></div></div><div id="indicatorPanel"><img id="System" class="PanelIcons" '+B+' -120px -21px;"'+u+'><div id="Time" class="PanelIcons" style="width:auto;"></div><img id="Volume" class="PanelIcons" '+B+'  -188px -0px;"'+u+'><img id="Messages" class="PanelIcons" '+B+'  -143px -22px;"'+u+'></div></div><div id="uLauncher">'+a+'</div><div id="cpy"><span class="cp">Copyright&nbsp;&copy;&nbsp;2023 </span><span id="0_cpContact" class="toolTipclass">Stewart J. Robinson</span><span class="cp"><br>Stewved&apos;s Webtop is modeled after </span></span><a class="ubLink" href="http://www.ubuntu.com/" target="_blank">Ubuntu OS</a></div></div>';
Ab(1);document.getElementById("C_0").style.marginTop="5px";C[0]=[];C[0].Window={I:"Desktop",H:"",nc:!1};C[0].ea=Bb;C[0].Sb={cpContact:'<p class="B pZW">Contact StewVed:<br></p><img class="imgSocs" '+B+' -146px -26px;"'+u+"><a id='contactFB' class='ubLink'>Feedback / Contact Webapp</a><br><img class=\"imgSocs\" "+Cb+"Facebook.png');\""+u+"><a class='ubLink' href='https://www.facebook.com/StewvedsWebtop' target='_blank'>Stewved's Webtop on FaceBook</a><br><img class=\"imgSocs\" "+Cb+"Facebook.png');\""+
u+"><a class='ubLink' href='https://www.facebook.com/Stewved' target='_blank'>Stewved on FaceBook</a><br><img class=\"imgSocs\" "+Cb+"Twitter.png');\""+u+"><a class='ubLink' href='https://twitter.com/StewVed' target='_blank'>Stewved on Twitter</a><br>"}}function Db(a){if(a){a=a.split(",");for(var b in a)window.open(a[b],"_blank")}}
function ra(a){var b=new Date;b>=a?(Ga=Math.floor((b-a)/1E3),b="since "):(Ga=Math.floor((a-b)/1E3),b="until ");var d="",e="("+(Ga/86400/365*100).toFixed(2)+"% of a year.)";31536E3<=Ga&&(d+=Eb(31536E3,"year")+", ");2628E3<=Ga&&(d+=Eb(2628E3,"month")+", ");604800<=Ga&&(d+=Eb(604800,"week")+", ");86400<=Ga&&(d+=Eb(86400,"day")+", ");3600<=Ga&&(d+=Eb(3600,"hour")+", ");60<=Ga&&(d+=Eb(60,"minute")+", ");d+=Eb(1,"second")+"<br>";100>=parseFloat(e.slice(1))&&(d+=e);return"Time "+b+a.toDateString()+"<br>"+
d}function Fb(a){document.getElementById("NotyCont"+a).style.opacity=0;window.setTimeout(function(){delete k[a];document.getElementById("NotyCont"+a).parentNode.removeChild(document.getElementById("NotyCont"+a));sa()},500)}
function sa(){if(0<k.length){var a=0,b=[];if("Ub"===v)for(var d in k){b.push(d);if(0<a){var e=document.getElementById("NotyCont"+b[a-1]),f=document.getElementById("NotyCont"+b[a]);e&&f&&(f.style.top=Number(e.style.top.slice(0,-2))+e.offsetHeight+4+"px")}else document.getElementById("NotyCont"+k[parseFloat(d)]).style.top=Number(document.getElementById("UnityPanel").style.height.slice(0,-2))+4+"px";document.getElementById("NotyCont"+k[parseFloat(d)]).style.left=document.getElementById("Wallpaper").offsetWidth-
document.getElementById("NotyCont"+k[parseFloat(d)]).offsetWidth-4+"px";a++}else for(d in k)b.push(d),0<a?(e=document.getElementById("NotyCont"+b[a-1]),f=document.getElementById("NotyCont"+b[a]),e&&f&&(f.style.top=Number(e.style.top.slice(0,-2))-f.offsetHeight-4+"px")):document.getElementById("NotyCont"+k[parseFloat(d)]).style.top=Number(document.getElementById("UnityPanel").style.top.slice(0,-2))-document.getElementById("NotyCont"+k[parseFloat(d)]).offsetHeight-4+"px",a++}}
function Gb(){if(!document.getElementById("RizzsXmasTimer")){var a=new Date((new Date).getFullYear(),11,25);new Date>a&&a.setFullYear(a.getFullYear()+1);h('For <a class="ubLink" href="https://www.facebook.com/chris.booker.5" target="_blank">Chrs Booker</a>, Until Xmas:<br><div id="RizzsXmasTimer">000 days, 00 hours, 00 minutes, 00 seconds<br>(100% of a year.)</div>')}}function Eb(a,b){var d=Math.floor(Ga/a);Ga-=a*d;return 1==d?"1 "+b:d+" "+b+"s"}
function Hb(a,b){var d=Ya.createOscillator(),e=Ya.createGain();d.connect(e);e.connect(Ya.destination);d.type="sine";d.frequency.value=a;e.gain.value=1;d.start();setTimeout(function(){d.stop()},b)}function Ib(a){H.innerHTML='<p style="margin:0;padding:0;text-align:center;">'+a.replace(/~#/g,"&").replace(/#Q/g,"&quot").replace(/-Q-/g,'\\"')+"</p>";Jb()}function Kb(a){10>a&&(a="0"+a);return a}
function hb(){var a=new Date;a=Kb(a.getHours())+":"+Kb(a.getMinutes());a!=document.getElementById("Time").innerHTML&&(document.getElementById("Time").innerHTML=a);document.getElementById("RizzsXmasTimer")&&(a=new Date((new Date).getFullYear(),11,25),new Date>a&&a.setFullYear(a.getFullYear()+1),document.getElementById("RizzsXmasTimer").innerHTML=ra(a),a=document.getElementById("RizzsXmasTimer").parentNode,a.style.borderColor="rgb(255, 255, 255"==a.style.borderColor.slice(0,17)?"rgb(225,0,0)":"rgb(225, 0"==
a.style.borderColor.slice(0,10)?"rgb(0,255,0":"rgb(255,255,255)")}
function ib(){Q=document.getElementById("Wallpaper").offsetWidth-(document.getElementById("uLauncher").offsetWidth+1+document.getElementById("uLauncher").offsetLeft);Xa=document.getElementById("uLauncher").offsetWidth+1+document.getElementById("uLauncher").offsetLeft;document.body.style.height=window.innerHeight+"px";if(Lb())if(-1==L||0==L)L=0,C[0].Window.H="full";else{if(0<L){var a=L,b=document.getElementById(a),d=document.getElementById(a+"Cont");b.style.left="-8px";b.style.top="-8px";d.style.width=
document.getElementById("Wallpaper").offsetWidth+"px";d.style.height=document.getElementById("Wallpaper").offsetHeight+"px";d.style.top=-document.getElementById(a+"TopBar").offsetHeight+"px";C[a].Window.$b=C[a].Window.H;C[a].Window.H="full";b.style.zIndex=999;d.style.height=document.getElementById("Wallpaper").offsetHeight+"px";d.style.top=document.getElementById(a+"TopBar").offsetHeight+"px";Mb(a);document.getElementById(a+"TopBar").style.opacity=0;document.getElementById("UnityPanel").style.opacity=
0;Nb(L)}}else-1<L&&(Ob(),C[0].Window.H="");document.getElementById("lExpo")&&Pb();document.getElementById("cpy").style.left=Xa+"px";document.getElementById("cpy").style.left=document.getElementById("Wallpaper").offsetWidth-document.getElementById("cpy").offsetWidth-4+"px";Qb("resize");"Ku"==v?(document.getElementById("UnityPanel").style.top=document.getElementById("Wallpaper").offsetHeight-document.getElementById("UnityPanel").offsetHeight+"px",document.getElementById("cpy").style.top=document.getElementById("Wallpaper").offsetHeight-
document.getElementById("cpy").offsetHeight-document.getElementById("UnityPanel").offsetHeight-2+"px",document.getElementById("kTaskBar").style.width=document.getElementById("indicatorPanel").offsetLeft+"px"):(document.getElementById("cpy").style.top=document.getElementById("Wallpaper").offsetHeight-document.getElementById("cpy").offsetHeight-2+"px",document.getElementById("gMxTitle").style.width=document.getElementById("indicatorPanel").offsetLeft+"px");sa();for(var e in C){if("max"==C[parseFloat(e)].Window.H||
"full"==C[parseFloat(e)].Window.H)var f=document.getElementById(e),g=document.getElementById(e+"Cont");f&&(f.style.top=-F+"px","max"==C[parseFloat(e)].Window.H?"Ku"==v?(f.style.left=-F+"px",g.style.width=document.getElementById("Wallpaper").offsetWidth+"px",g.style.height=document.getElementById("Wallpaper").offsetHeight-document.getElementById("UnityPanel").offsetHeight+"px"):"Ub"==v&&(f.style.left=Xa-F+"px",g.style.width=Q+"px",g.style.height=document.getElementById("Wallpaper").offsetHeight-document.getElementById("UnityPanel").offsetHeight+
"px"):(g.style.width=document.getElementById("Wallpaper").offsetWidth+"px",g.style.height=document.getElementById("Wallpaper").offsetHeight+"px",g.style.top=-document.getElementById(e+"TopBar").offsetHeight+"px"),Nb(e))}document.getElementById("NotyCont")&&(document.getElementById("NotyCont").style.left=document.getElementById("Wallpaper").offsetWidth-document.getElementById("NotyCont").offsetWidth-4+"px")}
function Nb(a){C[a].Window.ca?Rb(a):(document.getElementById(a+"Box").style.width=document.getElementById(a+"Cont").offsetWidth+"px",document.getElementById(a+"Box").style.height=document.getElementById(a+"Cont").offsetHeight+"px");"Bencher"==C[a].Window.I?document.getElementById(a+"_bb_gameArea")&&(C[a].g.Z=document.getElementById(a+"Cont").offsetWidth,C[a].g.aa=document.getElementById(a+"Cont").offsetHeight,1<C[a].g.la?(C[a].g.ja.width=C[a].g.Z,C[a].g.ja.height=C[a].g.aa):(C[a].g.ja.style.width=
C[a].g.Z+"px",C[a].g.ja.style.height=C[a].g.aa+"px")):"Screens"==C[a].Window.I?Sb(a,0):"wall"==C[a].Window.I?Tb(a):12==a?Ub(a):13==a?Vb():"GProto"==C[a].Window.I&&Wb(a)}
function Mb(a){var b=document.getElementById(a);document.getElementById(a+"Cont");var d=document.getElementById(a+"Box"),e=document.getElementById("Wallpaper"),f=b.offsetWidth-2*F;f>e.offsetWidth-Xa&&(d.style.width=f-Xa+"px");b=b.offsetHeight-2*F;var g;"max"==C[a].Window.H?b>e.offsetHeight&&(g=e.offsetHeight-document.getElementById("UnityPanel").offsetHeight):b>e.offsetHeight-document.getElementById("UnityPanel").offsetHeight&&(g=e.offsetHeight-document.getElementById("UnityPanel").offsetHeight-document.getElementById(a+
"TopBar").offsetHeight);g&&(d.style.height=g+"px",C[a].Window.ca&&(y.X="n-resize",Rb(a),y.X=""));Nb(a)}
function Rb(a){document.getElementById(a+"Cont");var b=document.getElementById(a+"Box");if("max"==C[a].Window.H||"n-resize"==y.X||"s-resize"==y.X){var d=b.offsetHeight/C[a].Window.s;b.style.width=C[a].Window.o*d+"px"}else d=b.offsetWidth/C[a].Window.o,b.style.height=C[a].Window.s*d+"px";if("max"==C[a].Window.H||"full"==C[a].Window.H){var e=document.getElementById(a+"Cont");b=document.getElementById(a+"Box");var f=e.offsetHeight;f/=C[a].Window.s;d=Math.floor(C[a].Window.o*f);d>e.offsetWidth&&(f=e.offsetWidth/
C[a].Window.o,d=Math.floor(C[a].Window.o*f));f=Math.floor(C[a].Window.s*f);var g=Math.floor(e.offsetWidth-(d+(e.offsetWidth-d)/2));e=Math.floor(e.offsetHeight-(f+(e.offsetHeight-f)/2));1==e&&(e=0);1==g&&(g=0);b.style.left=g+"px";b.style.width=d+"px";b.style.top=e+"px";b.style.height=f+"px"}C[a].Window.S&&(document.getElementById(a),document.getElementById(a+"Cont"),b=document.getElementById(a+"Box"),d=b.offsetWidth/C[a].Window.o,b.style.fontSize=100*d+"%",Xb(a,b,d),C[a].Window.S=d)}
function Xb(a,b,d){if(b.hasChildNodes()){b=b.children;for(var e=0;e<b.length;e++){try{var f=b[e].nodeName.toLowerCase();if("br"!=f&&"option"!=f&&""!=f&&"table"!=f&&"tbody"!=f&&"tr"!=f&&"td"!=f&&(f=b[e].parentNode.nodeName.toLowerCase(),"br"!=f&&"option"!=f&&""!=f&&"table"!=f&&"tbody"!=f&&"tr"!=f&&"td"!=f)){var g=b[e].style.left.slice(0,-2),l=b[e].style.top.slice(0,-2),m=b[e].style.width.slice(0,-2),p=b[e].style.height.slice(0,-2);0==p.length&&(p=b[e].clientHeight);0==m.length&&(m=b[e].clientWidth);
"%"!=b[e].style.left.slice(-1)&&(b[e].style.left=g/C[a].Window.S*d+"px");"%"!=b[e].style.top.slice(-1)&&(b[e].style.top=l/C[a].Window.S*d+"px");"%"!=b[e].style.width.slice(-1)&&(b[e].style.width=m/C[a].Window.S*d+"px");"%"!=b[e].style.height.slice(-1)&&(b[e].style.height=p/C[a].Window.S*d+"px");b[e].style.borderLeftWidth&&(b[e].style.borderLeftWidth=parseFloat(b[e].style.borderLeftWidth)/C[a].Window.S*d+"px");b[e].style.borderRightWidth&&(b[e].style.borderRightWidth=parseFloat(b[e].style.borderRightWidth)/
C[a].Window.S*d+"px");b[e].style.borderTopWidth&&(b[e].style.borderTopWidth=parseFloat(b[e].style.borderTopWidth)/C[a].Window.S*d+"px");b[e].style.borderBottomWidth&&(b[e].style.borderBottomWidth=parseFloat(b[e].style.borderBottomWidth)/C[a].Window.S*d+"px")}}catch(w){}0<b[e].childElementCount&&Xb(a,b[e],d)}}}
function Yb(a){if(a.hasChildNodes()){a=a.children;for(var b=a.length-1;0<=b;b--){var d=a[b].nodeName.toLowerCase();"br"!=d&&"option"!=d&&""!=d&&"table"!=d&&"tbody"!=d&&"tr"!=d&&"td"!=d&&(d=a[b].parentNode.nodeName.toLowerCase(),"br"!=d&&"option"!=d&&""!=d&&"table"!=d&&"tbody"!=d&&"tr"!=d&&"td"!=d&&("relative"!=a[b].style.position&&(a[b].style.left=a[b].offsetLeft+"px",a[b].style.top=a[b].offsetTop+"px"),a[b].style.boxSizing="border-box",a[b].style.width=a[b].offsetWidth+"px",parseFloat(a[b].style.width)!=
a[b].offsetWidth&&(a[b].style.width=parseFloat(a[b].style.width)+(parseFloat(a[b].style.width)-a[b].offsetWidth)+"px"),a[b].style.height=a[b].offsetHeight+"px",parseFloat(a[b].style.height)!=a[b].offsetHeight&&(a[b].style.height=parseFloat(a[b].style.height)+(parseFloat(a[b].style.height)-a[b].offsetHeight)+"px"),d=a[b].parentNode.offsetWidth,a[b].style.marginLeft&&"%"!=a[b].style.marginLeft.slice(-1)&&(a[b].style.marginLeft=100*parseFloat(a[b].style.marginLeft)/d+"%"),a[b].style.marginRight&&"%"!=
a[b].style.marginRight.slice(-1)&&(a[b].style.marginRight=100*parseFloat(a[b].style.marginRight)/d+"%"),a[b].style.marginTop&&"%"!=a[b].style.marginTop.slice(-1)&&(a[b].style.marginTop=100*parseFloat(a[b].style.marginTop)/d+"%"),a[b].style.marginBottom&&"%"!=a[b].style.marginBottom.slice(-1)&&(a[b].style.marginBottom=100*parseFloat(a[b].style.marginBottom)/d+"%"),a[b].style.paddingLeft&&"%"!=a[b].style.paddingLeft.slice(-1)&&(a[b].style.paddingLeft=100*parseFloat(a[b].style.paddingLeft)/d+"%"),a[b].style.paddingRight&&
"%"!=a[b].style.paddingRight.slice(-1)&&(a[b].style.paddingRight=100*parseFloat(a[b].style.paddingRight)/d+"%"),a[b].style.paddingTop&&"%"!=a[b].style.paddingTop.slice(-1)&&(a[b].style.paddingTop=100*parseFloat(a[b].style.paddingTop)/d+"%"),a[b].style.paddingBottom&&"%"!=a[b].style.paddingBottom.slice(-1)&&(a[b].style.paddingBottom=100*parseFloat(a[b].style.paddingBottom)/d+"%"),0<a[b].childElementCount&&Yb(a[b])))}}}
function Zb(a){if(a.hasChildNodes()){a=a.children;for(var b=a.length-1;0<=b;b--){var d=a[b].nodeName.toLowerCase();"br"!=d&&"option"!=d&&""!=d&&"table"!=d&&"tbody"!=d&&"tr"!=d&&"td"!=d&&(d=a[b].parentNode.nodeName.toLowerCase(),"br"!=d&&"option"!=d&&""!=d&&"table"!=d&&"tbody"!=d&&"tr"!=d&&"td"!=d&&("relative"!=a[b].style.position&&(a[b].style.position="absolute"),d=parseFloat(a[b].style.left),d!=a[b].offsetLeft&&(a[b].style.left=d+(d-a[b].offsetLeft)+"px"),d=parseFloat(a[b].style.width),d!=a[b].offsetWidth&&
(a[b].style.width=d+(d-a[b].offsetWidth)+"px"),d=parseFloat(a[b].style.top),d!=a[b].offsetTop&&(a[b].style.top=d+(d-a[b].offsetTop)+"px"),d=parseFloat(a[b].style.height),d!=a[b].offsetHeight&&(a[b].style.height=d+(d-a[b].offsetHeight)+"px"),0<a[b].childElementCount&&Yb(a[b])))}}}
function gb(a){a=parseFloat(a);if(isNaN(a)||!C[a])a=0;if(!(0<a&&"max"==C[a].Window.H)){for(var b in C[a].D);0<a?document.getElementById("UPTitle").innerHTML="":document.getElementById("UPTitle").innerHTML="StewVed&apos;s Webtop"}}
function $b(a){document.getElementById("RCMcontainer")&&ac();var b=a.id.split("_"),d=parseFloat(b[0]);if(!isNaN(d)){-1==d&&(d=0);G.Bb=a.id;if(G.Ya=d)document.getElementById(G.Ya+"gMenu").classList.add("gMenuOpen"),a.classList.add("gMenuItemsHover");var e="",f;for(f in C[d].D[b[2]].v)e=C[d].D[b[2]].v[f].j?e+('<div id="'+d+"_"+f+"_gMenu_"+b[2]+'" class="RCMenu '+q[r].va+'">'+C[d].D[b[2]].v[f].Text+"</div>"):e+('<div class="RCMgrey">'+C[d].D[b[2]].v[f].Text+"</div>");bc(e);for(f in C[d].D[b[2]].v)C[d].D[b[2]].v[f].Event&&
(e=C[d].D[b[2]].v[f].Event,"mouseup"===e[1]?(document.getElementById(e[0]).addEventListener("mouseup",e[2]),document.getElementById(e[0]).addEventListener("touchend",e[2])):document.getElementById(e[0]).addEventListener(e[1],e[2])),C[d].D[b[2]].v[f].Gb&&(e=C[d].D[b[2]].v[f].Gb,"mouseup"===e[1]?(document.getElementById(e[0]).addEventListener("mouseup",e[2]),document.getElementById(e[0]).addEventListener("touchend",e[2])):document.getElementById(e[0]).addEventListener(e[1],e[2]));"none"==G.active&&
(G.active="gMenuSub");b=document.getElementById("RCMcontainer");d=0;for(f=a.offsetHeight;"Wallpaper"!=a.id;)d+=a.offsetLeft,f+=a.offsetTop,a=a.parentNode;b.style.left=d+"px";b.style.top=f-2+"px";b.style.borderRadius="0px 0px 6px 6px";b.style.borderTop="0px";7==D&&(C[7].Ja=!0)}}
function cc(a,b){if(a&&"gm"!==a.id.slice(0,2)){var d=parseFloat(a.id).toString();isNaN(d)&&(d=dc(a));if(isFinite(d)){if("top"===b){if(E[E.indexOf(d)]&&E.splice(E.indexOf(d),1),E.unshift(d),"full"==C[d].Window.H)return}else"add"===b?E.unshift(d):"del"===b&&E.splice(E.indexOf(d),1);E[0]&&0!=E[0]?(ec(document.getElementById(E[0])),gb(E[0])):(ec(document.getElementById("Wallpaper")),gb(0),document.getElementById("Tl").style.opacity=0,document.getElementById("Tl").style.top="0")}else ec(a),gb(0),document.getElementById("Tl").style.opacity=
0,document.getElementById("Tl").style.top="0"}}function fc(a){for(var b=1;C[parseFloat(a+"."+b)];)b++;return parseFloat(a+"."+b)}function dc(a){var b=NaN;if(a){for(;"Wallpaper"!=a.id&&isNaN(parseFloat(a.id));)a=a.parentNode;b=a}return parseFloat(b.id).toString()}
function U(a){var b=a.split("_");a=parseFloat(b[1]);if(0===a){a=document.createElement("div");a.id="lExpo";document.getElementById("Wallpaper").appendChild(a);var d=document.getElementById("Wallpaper").offsetHeight-32;a.innerHTML='<div id="lExTop" style="height:32px;"><div style="float:left;width:8px;height:1px;"></div><img id="lExpoClose" class="Button ButtonClo" style="margin-right:56px;background-image: url('+t.src+')" '+u+'><div id="expoTall" class="expoTabSeld">All</div><div id="expoTapp" class="expoTabs">Apps</div><div id="expoTgame" class="expoTabs">Games</div><div id="expoTsett" class="expoTabs">Settings</div><div id="expoThelp" class="expoTabs">Help</div></div><div id="lExlCov" style="top:32px;height:'+
d+"px;width:"+Xa+'px;"></div><div id="lExList" class="letScroll" style="top:32px;left:'+Xa+"px;height:"+d+"px;width:"+Q+'px;"></div>';R.sort(gc);hc("all");a.style.opacity=1}else{d=parseInt(a,10);var e=parseInt(b[1].split(".")[1],10);if(e){var f=C[d].Window.Y;d=C[d].Window.l}else{99!==a&&100!==a&&a!==d&&parseInt(b[2],10)&&(d=parseInt(b[2],10));for(var g in R)if(R[parseFloat(g)].l==d){f=g;break}}var l=[],m;for(g in C)C[parseFloat(g)].Window.l==d&&(l.push(parseFloat(g)),m||(e?C[a]&&(m=1):m=1));if(m&&
"newInstance"!=b[0]&&isNaN(parseInt(x.O.id,10)))if("b"==b[2]||"f"==b[2]||"i"==b[2]||"t"==b[2])ic(b[3]);else{if("Lc"==b[2])for(g in l)ic(l[parseFloat(g)])}else{if(!e)for(a=1;C[a];)a++;C[a]=[];C[a].Window={Y:f,l:d,I:"blank",Fa:!1,T:-1,kb:-1,V:-1,ob:-1,H:"nor",o:-1,s:-1,G:-1,F:-1,S:0,ca:0};C[a].g=[];l.push(a);e&&b[2]&&(C[a].Window.Qb=b[2]);100==C[a].Window.l&&(C[a].Window.Qb=b[0]);g=document.getElementById("Wallpaper");f=document.createElement("div");f.id=a;f.className="winWindow";g.appendChild(f);if("Ku"==
v){var p=zb(a,1);p+='<div id="'+a+'bSpacer" style="float:right;width:8px;height:27px;"></div><img id="'+a+'CloseButton" class="Button" style="background-image: url('+t.src+');float:right;" '+u+'><img id="'+a+'MaxButton" class="Button" style="background-image: url('+t.src+');float:right;" '+u+'><img id="'+a+'MinButton" class="Button" style="background-image: url('+t.src+');float:right;" '+u+">"}else"Ub"==v&&(p=zb(a,0)+'<div id="'+a+'bSpacer" style="float:left;width:8px;height:27px;"></div><img id="'+
a+'CloseButton" class="Button" style="background-image: url('+t.src+')" '+u+'><img id="'+a+'MinButton" class="Button" style="background-image: url('+t.src+')" '+u+'><img id="'+a+'MaxButton" class="Button" style="background-image: url('+t.src+')" '+u+">");f.innerHTML='<div id="'+a+'TopBar" class="windowTopBar">'+p+'<div id="'+a+'Title" class="winTitle"></div><div id="'+a+'gMenu" class="gMenu '+q[r].ka+'"></div></div><div id="'+a+'Cont" class="winContainer"><div id="'+a+'Box" class="winBox"></div></div>';
"Ub"===v&&(document.getElementById(a+"appImg").style.width=0);document.getElementById(a+"TopBar").classList.add(q[r].ka);"Ku"==v&&(document.getElementById(a+"TopBar").style.height=document.getElementById(a+"Title").offsetHeight+25+"px");""==document.getElementById(a+"Title").innerHTML&&(document.getElementById(a+"Title").innerHTML=R[C[a].Window.Y].appName);f.style.left="128px";f.style.top="19px";jc(a);-1<S.indexOf(C[a].Window.l)?(ua||kc(a,"ku"),document.getElementById("T_"+d).style.opacity=1,document.getElementById("D_"+
d).style.opacity=.5):kc(a,"all");1==l.length?document.getElementById("T_"+d).style.backgroundPosition="-131px -44px":2==l.length?document.getElementById("T_"+d).style.backgroundPosition="-145px -44px":2<l.length&&(document.getElementById("T_"+d).style.backgroundPosition="-157px -44px");cc(document.getElementById(a.toString()),"add")}}}
function jc(a){window[R[C[a].Window.Y].K]?(window[R[C[a].Window.Y].K](a),lc(a)):(document.getElementById("Loader"+a)||mc(a),window.setTimeout(function(){jc(a)},500))}
function mc(a){document.getElementById(a+"Box").innerHTML='<div id="Loader'+a+'" style="position:relative;color:#dfdbd2;z-index:5;text-align:center;width:100%;margin:auto;"><span id="Ling'+a+'" class="loadin">Loading...</span><div id="LP"></div>';document.getElementById("Loader"+a).style.top=document.getElementById(a+"Box").offsetHeight/2-document.getElementById("Loader"+a).offsetHeight/2+"px";nc(a)}
function lc(a){document.getElementById(a+"Cont").style.backgroundColor=document.getElementById(a+"Box").style.backgroundColor;document.getElementById(a+"Box").style.left="0";document.getElementById(a+"Box").style.top="0";nc(a);oc(a);var b=document.getElementById(a+"MinButton");100==a&&(b.style.width="0");"Ku"==v?(b=document.getElementById(a+"appImg").offsetLeft+document.getElementById(a+"appImg").offsetWidth,document.getElementById(a+"Title").style.left=(document.getElementById(a+"MinButton").offsetLeft-
b)/2-document.getElementById(a+"Title").offsetWidth/2+b+"px",document.getElementById(a+"gMenu").className="kMenu",document.getElementById(a+"gMenu").style.width="100%",document.getElementById(a+"gMenu").style.top=document.getElementById(a+"Title").offsetHeight+"px"):"Ub"==v&&(document.getElementById(a+"Title").style.left=document.getElementById(a+"MaxButton").offsetLeft+document.getElementById(a+"MaxButton").offsetWidth+"px",document.getElementById(a+"gMenu").style.left=document.getElementById(a+
"Title").style.left,document.getElementById(a+"gMenu").style.width=document.getElementById(a).offsetWidth-document.getElementById(a+"gMenu").offsetLeft+"px",document.getElementById(a+"gMenu").style.height=document.getElementById(a+"TopBar").offsetHeight+"px");C[a].D||(C[a].D=[{Text:"File",v:[{Text:"Exit",j:function(){pc(a)}}]}]);qc(a);Mb(a)}
function ic(a){"Deleted"!=C[a].Window.I&&("min-max"==C[a].Window.H?C[a].Window.H="max":"min-nor"==C[a].Window.H&&(C[a].Window.H="nor"),document.getElementById(a).hidden=!1,cc(document.getElementById(a),"top"),document.getElementById("b_"+a).style.opacity="1")}function qc(a){var b="",d;for(d in C[a].D)b+='<div id="'+a+"_gm_"+d,"Ku"==v?b+='" class="kMenuItems">':"Ub"==v&&(b+='" class="gMenuItems">'),b+=C[a].D[d].Text+"</div>";document.getElementById(a+"gMenu").innerHTML=b}
function Lb(){var a=document.fullscreenElement||document.webkitFullscreenElement||document.msFullscreenElement;a=a?1:0;var b=0,d=window.innerWidth,e=screen.width;screen.height===window.innerHeight&&d===e&&(b=1);if(a!=b){debugger;h("isFS is "+a+" but checkFS is "+b)}return a}
function Ob(){var a=L;if(isFinite(a)&&0<a){var b=document.getElementById(a),d=document.getElementById(a+"Cont"),e=document.getElementById(a+"Box");"max"==C[a].Window.$b?(b.style.top="-8px","Ku"==v?(b.style.left="-8px",d.style.width=document.getElementById("Wallpaper").offsetWidth+"px",d.style.height=document.getElementById("Wallpaper").offsetHeight-document.getElementById("UnityPanel").offsetHeight+"px"):"Ub"==v&&(b.style.left=Xa-F+"px",d.style.width=Q+"px",d.style.height=document.getElementById("Wallpaper").offsetHeight-
document.getElementById("UnityPanel").offsetHeight+"px"),cc(b,"top")):(b.style.left=C[a].Window.V+"px",b.style.top=C[a].Window.T+"px",d.style.width=d.style.height="",e.style.top=e.style.left="",e.style.width=C[a].Window.ob+"px",e.style.height=C[a].Window.kb+"px");"Ub"==v&&(document.getElementById(a+"gMenu").style.width=document.getElementById(a).offsetWidth-document.getElementById(a+"gMenu").offsetLeft+"px");C[a].Window.H=C[a].Window.$b;b.style.zIndex=E[a];d.style.top="";document.getElementById(a+
"TopBar").style.opacity=1;document.getElementById("UnityPanel").style.opacity=1}isFinite(a)&&0<a&&(Mb(L),Nb(L));L="full"==C[0].Window.H&&0<a?0:-1}
function V(a){var b=Lb();L=a;b?"full"==C[0].Window.H&&0<L?"full"==C[a].Window.H?Ob():ib():(Za.call(document,function(){}),document.getElementById(a+"FS")&&(document.getElementById(a+"FS").classList.remove("fsdButton"),document.getElementById(a+"FS").classList.add("fsButton"))):($a.call(document.documentElement,function(){}),document.getElementById(a+"FS")&&(document.getElementById(a+"FS").classList.remove("fsButton"),document.getElementById(a+"FS").classList.add("fsdButton")))}
function nc(a){var b=document.getElementById("Wallpaper"),d=document.getElementById(a);d.style.left=Xa-1+(b.offsetWidth-Xa)/2-(d.offsetWidth-0)/2+"px";var e=document.getElementById("UnityPanel").offsetHeight,f=d.offsetHeight-2*F;if("Ub"==v)var g=e+(b.offsetHeight-e)/2-f/2;else"Ku"==v&&(g=b.offsetHeight/2-(f+e)/2,e=0);if(g<=e||99==a)g=e;g-=F;d.style.top=g+"px"}
function pc(a){var b=parseFloat(a),d=document.getElementById(b.toString());if(isFinite(b)&&d){var e=parseInt(a,10);if(b===e)for(var f in C)parseInt(f,10)===e&&f!=b&&pc(f);"closing"!=C[a].Window.I&&("none"!=G.active&&ac(),d.style.transition="opacity 0.4s",d.style.opacity=0,C[a].Window.I="closing",window.setTimeout(function(){var g=parseInt(C[a].Window.l,10),l=0,m;for(m in C)C[parseFloat(m)].Window.l==g&&l++;1==l?(document.getElementById("T_"+g).style.opacity=0,document.getElementById("T_"+g).style.backgroundPosition=
"-131px -44px",document.getElementById("D_"+g).style.opacity=0,T[g].locked||rc(g)):1<l&&(2==l?document.getElementById("T_"+g).style.backgroundPosition="-131px -44px":3==l?document.getElementById("T_"+g).style.backgroundPosition="-145px -44px":3<l&&(document.getElementById("T_"+g).style.backgroundPosition="-157px -44px"));document.getElementById("b_"+a)&&(document.getElementById("kTaskBar").removeChild(document.getElementById("b_"+a)),Qb("close"));d.parentNode.removeChild(d);C[a].g.hb&&window.clearInterval(C[a].g.hb);
delete C[a];cc(d,"del")},420))}}
function sc(a){var b=document.getElementById(a),d=document.getElementById(a+"Cont"),e=document.getElementById(a+"Box");b&&!isNaN(parseInt(a,10))&&("max"==C[a].Window.H?(b.style.left=C[a].Window.V+"px",b.style.top=C[a].Window.T+"px",d.style.width=d.style.height="",e.style.top=e.style.left="",e.style.width=C[a].Window.ob+"px",e.style.height=C[a].Window.kb+"px",C[a].Window.H="nor"):(b.style.top="-8px",C[a].Window.H="max",tc(a),e.style.width=d.style.width,e.style.height=d.style.height),Mb(a),"max"==C[a].Window.H&&
tc(a),"Ub"==v&&(document.getElementById(a+"gMenu"),document.getElementById(a+"gMenu").style.width=document.getElementById(a).offsetWidth-document.getElementById(a+"gMenu").offsetLeft+"px"),cc(b,"top"))}
function tc(a){var b=document.getElementById(a),d=document.getElementById(a+"Cont");document.getElementById(a+"Box");"Ku"==v?(b.style.left=-F+"px",d.style.width=document.getElementById("Wallpaper").offsetWidth+"px",d.style.height=document.getElementById("Wallpaper").offsetHeight-document.getElementById("UnityPanel").offsetHeight+"px"):"Ub"==v&&(b.style.left=Xa-F+"px",d.style.width=Q+"px",d.style.height=document.getElementById("Wallpaper").offsetHeight-document.getElementById("UnityPanel").offsetHeight+
"px")}function bc(a){var b=document.createElement("div");b.id="RCMcontainer";b.innerHTML=a;document.getElementById("Wallpaper").appendChild(b);b.classList.add(q[r].wa)}
function ac(){G.active="none";J.style.opacity=K.style.opacity=0;G.Ya&&document.getElementById(G.Ya+"gMenu").classList.remove("gMenuOpen");G.Bb&&document.getElementById(G.Bb).classList.remove("gMenuItemsHover");document.getElementById("RCMcontainer")&&document.getElementById("RCMcontainer").parentNode.removeChild(document.getElementById("RCMcontainer"));"full"!=C[parseFloat(D)].Window.H&&ec(document.getElementById(D.toString()));G={active:"none",Bb:"",Ya:"",Zb:""}}
function uc(a){if("System"==a)return Bb;if("Time"==a)return vc;if("Volume"==a)return wc;if("Messages"==a)return ab}
function xc(a){document.getElementById("RCMcontainer")&&ac();G.active="indicator";var b="",d=uc(a.id),e;for(e in d)b=d[e].j?b+('<div id="'+a.id+"_"+e+'_iMenu" class="RCMenu '+q[r].va+'">'+d[e].Text+"</div>"):b+('<div class="RCMgrey">'+d[e].Text+"</div>");if(0!=b.length){bc(b);b=document.getElementById("RCMcontainer");for(e=d=0;"Wallpaper"!=a.id;)d+=a.offsetLeft,e+=a.offsetTop,a=a.parentNode;b.offsetWidth+d>document.getElementById("Wallpaper").offsetWidth&&(d=document.getElementById("Wallpaper").offsetWidth-
b.offsetWidth);"Ub"==v?(e+=document.getElementById("UnityPanel").offsetHeight,b.offsetHeight+e>document.getElementById("Wallpaper").offsetHeight&&(e=document.getElementById("Wallpaper").offsetHeight-b.offsetHeight)):"Ku"==v&&b.offsetHeight+e>document.getElementById("Wallpaper").offsetHeight-document.getElementById("UnityPanel").offsetHeight&&(e=document.getElementById("Wallpaper").offsetHeight-document.getElementById("UnityPanel").offsetHeight-b.offsetHeight);b.style.top=e+"px";b.style.left=d+"px"}}
function yc(a,b){a=parseFloat(a.id).toString();if(!isNaN(a)){var d=C[parseFloat(a)].Window.Fa?"&#10004;&nbsp;":"&nbsp;&nbsp;";d+="Always On Top";G.active="title";var e="";0<document.getElementById(a+"MinButton").offsetWidth&&(e+='<div id="'+a+'MinButtonE" class="RCMenu '+q[r].va+'">>&nbsp;&nbsp;Minimise</div>');0<document.getElementById(a+"MaxButton").offsetWidth&&(e+='<div id="'+a+'MaxButtonE" class="RCMenu '+q[r].va+'">>&nbsp;&nbsp;Maximise</div>');0<e.length&&(e+="<hr>");e+='<div id="'+a+'AOE" class="RCMenu '+
q[r].va+'">>'+d+"</div>";99!=parseInt(a,10)&&(e+='<hr><div id="'+a+'CloseButtonE" class="RCMenu '+q[r].va+'">>&nbsp;&nbsp;Close</div>');bc(e);d=document.getElementById("RCMcontainer");d.style.left=b.clientX+"px";d.style.top=b.clientY+"px";G.Zb=a;7==D&&(C[7].Ja=!0)}}
function zc(a,b){document.getElementById("RCMcontainer")&&ac();var d="",e=a.id;"Wallpaper"==e&&(e=0);for(var f in C[e].ea)d=C[e].ea[f].j?d+('<div id="'+e+"_"+f+'_rMenu" class="RCMenu '+q[r].va+'">'+C[e].ea[f].Text+"</div>"):d+('<div id="'+e+"_"+f+'_rMenu" class="RCMgrey">'+C[e].ea[f].Text+"</div>");0!=d.length&&(bc(d),G.active="right",d=document.getElementById("RCMcontainer"),d.style.borderRadius="6px",d.style.borderTop="",e=b.clientX,f=b.clientY,e+d.offsetWidth>window.innerWidth&&(e=b.clientX-d.offsetWidth),
f+d.offsetHeight>window.innerHeight&&(f=b.clientY-d.offsetHeight),d.style.left=e+"px",d.style.top=f+"px",G.Zb=a,7==D&&(C[7].Ja=!0))}
function ec(a){var b=NaN;a&&(b=parseFloat(a.id).toString());for(var d in C)"Deleted"!=C[parseFloat(d)].Window.I&&"Desktop"!=C[parseFloat(d)].Window.I&&d!=b&&(C[parseFloat(d)].Window.Fa?document.getElementById(d).style.zIndex=E.length+3:document.getElementById(d).style.zIndex=E.length+1-E.indexOf(d),document.getElementById(d+"CloseButton").className="Button ButtonCloU",document.getElementById(d+"MinButton").className="Button ButtonMinU",document.getElementById(d+"MaxButton").className="Button ButtonMaxU",
document.getElementById("f_"+d).classList.add("kTaskU"),document.getElementById(d+"gMenu").classList.remove("gMenuF"),document.getElementById(d+"Title").classList.remove("winTitleF"));isFinite(b)&&0<b?("full"!=C[parseFloat(b)].Window.H&&(document.getElementById(b.toString()).style.zIndex=E.length+1),a=parseInt(C[parseFloat(b)].Window.l,10),document.getElementById("Tl").style.top=document.getElementById("C_"+a).offsetTop+10+"px",document.getElementById("Tl").style.opacity=1,document.getElementById(b+
"CloseButton").className="Button ButtonClo",document.getElementById(b+"MinButton").className="Button ButtonMin",document.getElementById(b+"MaxButton").className="Button ButtonMax",document.getElementById("f_"+b).classList.remove("kTaskU"),document.getElementById("f_"+b).classList.remove("kTaskH"),document.getElementById("f_"+b).classList.add("kTaskF"),document.getElementById(b+"gMenu").classList.add("gMenuF"),document.getElementById(b+"Title").classList.add("winTitleF"),D=b):(y.m="",D=0,document.getElementById("Tl").style.opacity=
0,document.getElementById("Tl").style.top="0");if("Ub"==v){for(d=E.length-1;-1<d;d--)if("max"==C[E[d]].Window.H){document.getElementById("gMxTitle").innerHTML=document.getElementById(E[d]+"TopBar").innerHTML;break}-1==d&&(document.getElementById("gMxTitle").innerHTML="")}}
function Ac(a){document.getElementById(a+"Cont");document.getElementById(a+"Box");document.getElementById(a+"Box").style.width=Math.round(.8*Q)+"px";C[a].Window.o=document.getElementById(a+"Cont").offsetWidth;document.getElementById(a+"Box").style.height=Math.round(.5625*document.getElementById(a+"Cont").offsetWidth)+"px";C[a].Window.s=document.getElementById(a+"Cont").offsetHeight;C[a].Window.G=Math.floor(document.getElementById(a+"Cont").offsetWidth/3);C[a].Window.F=Math.floor(document.getElementById(a+
"Cont").offsetHeight/3)}function oc(a){C[a].Window.V=document.getElementById(a).offsetLeft;C[a].Window.T=document.getElementById(a).offsetTop;C[a].Window.ob=document.getElementById(a+"Cont").offsetWidth;C[a].Window.kb=document.getElementById(a+"Cont").offsetHeight};window.dChoose=function(a){a=parseFloat(a);var b=document.body;isFinite(a)?(b=document.getElementById(a+"Box"),b.style.width=.8*Q+"px"):a=0;var d=a+"deChooser";b.style.background="radial-gradient(rgb(64, 71, 96), rgb(32, 39, 64))";b.innerHTML+='<div id="'+d+'" style="position:relative;margin:0% 2%;color:#dfdbd2;overflow:hidden;"><p style="padding:0;text-align:center;margin:0;font-size:3em;">Choose&nbsp;your&nbsp;Webtop:</p><p id="b" style="padding:0;text-align:center;margin:0px 0px 8px 0px;"><img id="'+
a+'Ku" class="DEchooseButton" style="float:left;width:47%;" src="images/kub.png"><img id="'+a+'Ub" class="DEchooseButton" style="float:right;width:47%;" src="images/ubu.png"><br style="clear:both;"><br></div>';document.getElementById(a+"Ku").style.height=document.getElementById(a+"Ub").style.height=.5625*document.getElementById(a+"Ku").offsetWidth+"px";a?(document.getElementById(a+v).style.backgroundColor="#eee",b.style.height=b.offsetHeight+"px",b.style.background="#234",d=C[a].Window,d.o=b.offsetWidth,
d.s=b.offsetHeight,d.G=Math.floor(b.offsetWidth/3),d.F=Math.floor(b.offsetHeight/3),d.I="dChooser",d.S=1,d.ca=1,Yb(document.getElementById(a+"Box")),Zb(document.getElementById(a+"Box"))):document.getElementById(d).style.top=b.offsetHeight/2-document.getElementById(d).offsetHeight/2+"px";document.getElementById(a+"Ku").addEventListener("mouseup",function(){Bc(a,"Ku")},!1);document.getElementById(a+"Ku").addEventListener("touchend",function(){Bc(a,"Ku")},!1);document.getElementById(a+"Ub").addEventListener("mouseup",
function(){Bc(a,"Ub")},!1);document.getElementById(a+"Ub").addEventListener("touchend",function(){Bc(a,"Ub")},!1)};function Bc(a,b){v!==b&&(v=b.slice(-2),Cc("webtopStyle",v),Ab(a))}
function Ab(a){if(a){if(document.getElementById(a+"deChooser")){for(var b=document.getElementById(a+"deChooser").getElementsByTagName("img"),d=0;d<b.length;d++)b[d].style.backgroundColor="";document.getElementById(a+v).style.backgroundColor="#eee"}document.getElementById("uLauncher").style.transition="top 1s, left 1s";document.getElementById("UnityPanel").style.transition="top 1s, height 1s";document.getElementById("cpy").style.transition="top 1s";"Ku"==v?(document.getElementById("uLauncher").style.left=
"-64px",document.getElementById("uLauncher").style.border=0,34!=document.getElementById("uLauncher").offsetTop&&(document.getElementById("uLauncher").style.top=document.getElementById("uLauncher").offsetTop+10+"px"),document.getElementById("UPTitle").style.opacity=0,document.getElementById("kTaskBar").style.opacity=1,document.getElementById("kTaskBar").style.zIndex=12,document.getElementById("indicatorPanel").style.marginTop="4px",document.getElementById("Time").style.lineHeight=document.getElementById("UnityPanel").style.height=
"34px",document.getElementById("gMxTitle").style.width=document.getElementById("gMxTitle").style.height=0,document.getElementById("kTaskBar").style.width=document.getElementById("indicatorPanel").offsetLeft+"px",document.getElementById("UnityPanel").style.top=document.getElementById("Wallpaper").offsetHeight-34+"px",document.getElementById("cpy").style.top=document.getElementById("Wallpaper").offsetHeight-document.getElementById("cpy").offsetHeight-34-2+"px",Dc(-24,"Ku")):"Ub"==v&&(document.getElementById("Time").style.lineHeight=
document.getElementById("UnityPanel").style.height=document.getElementById("gMxTitle").style.height="24px",document.getElementById("UnityPanel").style.top="0",document.getElementById("uLauncher").style.left="0",document.getElementById("uLauncher").style.border="border-right:1px solid rgba(255,255,255,0.5)",24!=document.getElementById("uLauncher").offsetTop&&(document.getElementById("uLauncher").style.top=document.getElementById("uLauncher").offsetTop+-10+"px"),document.getElementById("UPTitle").style.opacity=
1,document.getElementById("kTaskBar").style.opacity=0,document.getElementById("kTaskBar").style.width="0",document.getElementById("kTaskBar").style.zIndex=11,document.getElementById("indicatorPanel").style.marginTop="",document.getElementById("gMxTitle").style.width=document.getElementById("indicatorPanel").offsetLeft+"px",document.getElementById("cpy").style.top=document.getElementById("Wallpaper").offsetHeight-document.getElementById("cpy").offsetHeight-2+"px",Dc(24,"Ub"));sa();window.clearTimeout(va);
va=window.setTimeout(function(){document.getElementById("uLauncher").style.transition="";document.getElementById("UnityPanel").style.transition="";document.getElementById("cpy").style.transition="";for(var e=document.getElementsByClassName("winWindow"),f=0;f<e.length;f++){e[f].style.transition="";var g=e[f].id;document.getElementById(g+"CloseButton").style.position=document.getElementById(g+"CloseButton").style.transition="";document.getElementById(g+"MinButton").style.position=document.getElementById(g+
"MinButton").style.transition="";document.getElementById(g+"MaxButton").style.position=document.getElementById(g+"MaxButton").style.transition="";document.getElementById(g+"Title").style.transition="";"Ub"===v&&(document.getElementById(g+"appImg").style.width=0)}Q=document.getElementById("Wallpaper").offsetWidth-(document.getElementById("uLauncher").offsetWidth+1+document.getElementById("uLauncher").offsetLeft);Xa=document.getElementById("uLauncher").offsetWidth+1+document.getElementById("uLauncher").offsetLeft},
1E3)}}
function Dc(a,b){for(var d=document.getElementsByClassName("winWindow"),e=0;e<d.length;e++){d[e].style.transition="";d[e].style.transition="top 1s";d[e].style.top=d[e].offsetTop+a+"px";var f=d[e].id;C[parseFloat(f)].Window.T+=a;document.getElementById(f+"MaxButton").style.transition=document.getElementById(f+"MinButton").style.transition=document.getElementById(f+"CloseButton").style.transition="left 1s";document.getElementById(f+"Title").style.transition="1s";var g=f,l=b,m=document.getElementById(g+"CloseButton"),
p=document.getElementById(g+"MinButton"),w=document.getElementById(g+"MaxButton"),M=document.getElementById(g+"bSpacer");m.style.left=m.offsetLeft+"px";p.style.left=p.offsetLeft+"px";w.style.left=w.offsetLeft+"px";"Ub"===l?(M.style.cssFloat=m.style.cssFloat=p.style.cssFloat=w.style.cssFloat="left",w.parentNode.removeChild(p),w.parentNode.insertBefore(p,w)):(M.style.cssFloat=m.style.cssFloat=p.style.cssFloat=w.style.cssFloat="right",p.parentNode.removeChild(w),p.parentNode.insertBefore(w,p),document.getElementById(g+
"appImg").style.width="");var Aa=m.offsetLeft;M=p.offsetLeft;var xb=w.offsetLeft;m.style.position=p.style.position=w.style.position="absolute";m.style.left=Aa+"px";p.style.left=M+"px";w.style.left=xb+"px";m=document.getElementById(g+"Title");"Ub"===l?document.getElementById(g+"gMenu").style.left=m.style.left=xb+w.offsetWidth+"px":(g=document.getElementById(g+"appImg").offsetLeft+document.getElementById(g+"appImg").offsetWidth,m.style.left=(M-g)/2-m.offsetWidth/2+g+"px");g=document.getElementById(f+
"gMenu");g.style.transition="height 1s";"Ub"===b?(document.getElementById(f+"appImg").style.opacity=0,document.getElementById(f+"TopBar").style.height=document.getElementById(f+"Title").offsetHeight+"px",g.style.top="0",g.classList.remove("kMenu"),g.classList.add("gMenu"),g.style.width=d[e].offsetWidth-g.offsetLeft+"px"):(document.getElementById(f+"appImg").style.opacity=1,document.getElementById(f+"TopBar").style.height=document.getElementById(f+"Title").offsetHeight+25+"px",g.style.top=document.getElementById(f+
"Title").offsetHeight+"px",g.style.left="0",g.classList.remove("gMenu"),g.classList.add("kMenu"),g.style.width="")}};function jb(a){a.cancelable?(a.preventDefault(),a.stopPropagation()):(qb({bubbles:!0,button:0,cancelBubble:!1,cancelable:!0,clientX:0,clientY:0,currentTarget:"none",defaultPrevented:!1,returnValue:!0,target:document.getElementById("Wallpaper"),which:1,x:0,y:0}),z=[])}
function Ec(a,b,d){var e=a;0==a&&(e="lExList");if(!(isNaN(a)||!document.getElementById(e)||x.type&&D==a)){var f=(new Date).getTime();d=(f-d)/1E3;var g=b;e=-(b*d);0<d&&0!=b&&.25>e&&-.25<e?(x.type="",window.clearTimeout(x.ta)):(0<a?document.getElementById(a+"Box").scrollTop+=e:document.getElementById("lExList")&&(document.getElementById("lExList").scrollTop+=e),d&&(g+=0>g?2.5*e:3.2*e,0<b&&0>g||0>b&&0<g)&&(g=0),g?C[a].Window.Vb=window.requestAnimationFrame(function(){Ec(a,g,f)}):x.Ea=0)}}
function tb(){Fc()}function ub(){Fc()}function Fc(){for(var a=navigator.getGamepads(),b=0;b<a.length;b++)a[b]&&(Ca[b]=[],Ca[b].buttons=a[b].buttons.slice(0),Ca[b].axes=a[b].axes.slice(0))}function rb(a){var b=a.keyCode||window.event.keyCode;122==b&&(jb(a),V(D));0!=b&&18!=b&&17!=b&&16!=b&&91!=b&&Da.push(b)}
function sb(a){var b=a.keyCode||window.event.keyCode;for(122==b&&jb(a);-1!=Da.indexOf(b);)Da.splice(Da.indexOf(b),1);b=Gc(a).id.split("_");if("tg"===b[0]){if("min"===b[3]||"now"===b[3]||"max"===b[3]){a=b[1];b=b[2];document.getElementById("tg_"+a+"_"+b+"_max");document.getElementById("tg_"+a+"_"+b+"_min");var d=parseFloat(document.getElementById("tg_"+a+"_"+b+"_now").value);isNaN(d)||(C[a].g.ma[b].frequency.value=d,Hc(a,b,d))}}else"svl"===b[0]&&Ic(b[1])}
function Gc(a){a||(a=window.event);if(a.target)var b=a.target;else a.srcElement&&(b=a.srcElement);1!=b.nodeType&&(b=b.parentNode);b||=document.getElementById("Wallpaper");return b}function vb(){x={button:0,type:"",ta:0,Da:NaN,O:NaN,startTime:0,Ea:0,Ra:0,Sa:8,wb:0,Na:0};y={m:"",N:"",X:""};document.getElementById("Wallpaper").style.cursor="default"}function Jc(){Fa=0}
function ob(a){var b=Gc(a);"none"!=G.active&&"gMenuSub"!=G.active&&(G.active="deleteMenu");window.clearTimeout(x.ta);x.button=null==a.which?a.button:a.which;x.type="click";x.Da=b;x.O=b;x.startTime=new Date;x.wb=a.clientX;x.Na=a.clientY;x.Ra=a.clientX;x.Sa=a.clientY;var d=b;d.classList.contains("PanelIcons")&&xc(b);var e=dc(b);b=0<e?document.getElementById(e):document.getElementById("Wallpaper");isFinite(parseFloat(b.id))&&(y.m=b.id);if(d.classList.contains("editEnable")||d.classList.contains("uButtons")||
"TPFG"==d.className||"object"==d.nodeName.toLowerCase())cc(b,"top");else if(jb(a),d.classList.contains("LauncherIconCover"))Kc(a,d.id);else{if(1==x.button){if(Fa){if(d.classList.contains("gMenu")||d.classList.contains("winTitle")||d.classList.contains("windowTopBar")){if(e=parseFloat(b.id).toString(),0<document.getElementById(e+"MaxButton").offsetWidth){sc(D);Fa=0;return}}else if("screen_img"==d.className||"bb_gameArea"==d.className){V(D);Fa=0;return}Fa=0}else Fa=1,window.setTimeout(Jc,200);if(Ea){y.m=
Ea;y.N="Resizing";"none"!=G.active&&ac();y.X=document.getElementById("Wallpaper").style.cursor;Lc();cc(document.getElementById(Ea),"top");return}Mc(e,a,d);x.ta=window.setTimeout(function(){Nc(a,b,d)},500)}3==x.button&&"none"==G.active?d.classList.contains("winTitle")||d.classList.contains("gMenu")||d.classList.contains("windowTopBar")?yc(b,a):d.classList.contains("LauncherIconCover")?Kc(a,d.id):zc(b,a):!(""==d.id&&d.classList.contains("windowTopBar")||d.classList.contains("Button"))&&(cc(b,"top"),
d.classList.contains("windowTopBar")&&d.parentNode||(d.classList.contains("gMenu")&&"gMenu"!=d.id||d.classList.contains("winTitle"))&&d.parentNode.parentNode)&&(isNaN(y.m)&&h("origTarg is a window title, but Mdown.ID is NaN!<br>"),y.N="preMoving")}}
function Mc(a,b,d){var e=d.id.split("-");"toolTipclass"==d.id&&(Na=!0,Oc(a,d.id),Pc(d.id,1));if("uLauncher"==d.id)Kc(b,-1);else if("gMenuItems"==d.className||"kMenuItems"==d.className)$b(d);else if("screen_img"==d.className){var f=parseFloat(d.id);1==(null==b.which?b.button:b.which)&&(C[f].g.Ua=b.clientX-C[f].g.left,C[f].g.tb=b.clientY-C[f].g.top,C[f].g.lc=!0,y.m=f,y.N="sDrg")}else if("TTnums"==d.className||"TTbutton"==d.className){if(za?f=document.getElementById(za):f=Gc(b),a=f.id.split("_"),d=a[0],
1==C[d].g.ended&&(document.getElementById(d+"_lHs").innerHTML="Hours",document.getElementById(d+"_lMs").innerHTML="Minutes",document.getElementById(d+"_lSs").innerHTML="Seconds",C[d].g.W=C[d].g.startTime,Qc(d),C[d].g.ended=!1),"SrtStp"==a[1]&&(0==C[d].g.gb?(document.getElementById(f.id).style.backgroundColor="#0F0",document.getElementById(f.id).innerHTML="&#8572;&#8572;",C[d].g.gb=!0,C[d].g.Mb||(C[d].g.startTime=C[d].g.W,C[d].g.Mb=!0)):(document.getElementById(f.id).style.backgroundColor="#4AF",document.getElementById(f.id).innerHTML=
"&#9654;",C[d].g.gb=!1)),"Hs"==a[1]||"Ms"==a[1]||"Ss"==a[1])C[d].g.R[1]=b.clientY,za=C[d].g.R[0]=f.id,Lc()}else if("_BPgameArea"==d.id.slice(-11)){if(f=parseFloat(d.id),b=Gc(b),"winWindow"==b.className||"bb_gameArea"==b.className)if(""==document.getElementById(f).style.cursor||"default"==document.getElementById(f).style.cursor)0==C[f].g.h.speed&&(C[f].g.mb=1,C[f].g.h.qa=C[f].g.h.speed=Rc[C[f].g.Pb]+C[f].g.mb,C[f].g.h.top=C[f].g.L.top-C[f].g.h.height-1,C[f].g.Ja=!0),C[f].g.Ja=!C[f].g.Ja}else"wallSlider"===
d.id.slice(0,10)?(f=dc(d),d=d.id.slice(11),jb(b),Sc=d,x.O=document.getElementById("wallSliderb"+d),x.O.style.transition="",Ib(""),Tc(),J.style.background="linear-gradient(315deg, rgba(0,0,0,1) 36%, rgba(0,0,0,0) 40%)",Uc(f,b),document.getElementById(f+"Box").style.backgroundColor="transparent",document.getElementById(f+"Cont").style.backgroundColor="rgba(255,255,255,0.2)"):"tg"===e[0]&&"slider"===e[3]?(f=d.id.split("-"),"I"===f[4]||"Iv"===f[4]?(y.N="sgDrag",Lc()):"C"===f[4].slice(0,1)&&(x.O=document.getElementById("Cv"===
f[4]?f[0]+"-"+f[1]+"-"+f[2]+"-"+f[3]+"-Iv":f[0]+"-"+f[1]+"-"+f[2]+"-"+f[3]+"-I"),y.N="sgDrag",Vc(b),Lc())):"svl"===e[0]&&"slider"===e[2]?(f=d.id.split("-"),"I"===f[3]||"Iv"===f[3]?y.N="svlDrag":"C"===f[3].slice(0,1)&&(x.O=document.getElementById("Cv"===f[3]?f[0]+"-"+f[1]+"-"+f[2]+"-Iv":f[0]+"-"+f[1]+"-"+f[2]+"-I"),y.N="svlDrag",Wc(b))):isFinite(parseFloat(x.Da.id))&&"tATimer"==C[parseFloat(x.Da.id)].Window.I&&(f=parseFloat(d.id),C[f].g.ba=-2,Xc(f),d=Gc(b),a=d.id.split("~"),f=a[0],isFinite(parseInt(a[1],
10))&&(C[f].g.R[1]=b.clientY,Ba=C[f].g.R[0]=d.id,Lc()))}function Nc(a,b,d){"none"==G.active&&d&&(d.classList.contains("winTitle")||d.classList.contains("gMenu")||d.classList.contains("windowTopBar")?yc(b,a):d.classList.contains("LauncherIconCover")?Yc(b.split("_")[1]):x.O.classList.contains("toolTipclass")||x.O.parentNode.classList.contains("toolTipclass")?Zc(a):d.classList.contains("gMenuItems")||zc(b,a))}
function pb(a){if(!ya){ya=!0;window.requestAnimationFrame(function(){ya=!1});var b,d;if(d=b=Gc(a)){x.Da!=b&&("click"===x.type&&(x.type="",window.clearTimeout(x.ta)),$c(b),ad());bd(b);var e=x.Sa;x.Da=b;x.Ra=a.clientX;x.Sa=a.clientY;W&&cd(a);if(!b)h("targ is null (line 581");else if(!b.classList.contains("editEnable")&&!b.classList.contains("uButtons")&&"TPFG"!=b.className&&"object"!=b.nodeName.toLowerCase()){jb(a);if("click"===x.type){if(x.wb+10<a.clientX||x.wb-10>a.clientX||x.Na+10<a.clientY||x.Na-
10>a.clientY)x.type="",window.clearTimeout(x.ta),"preMoving"==y.N&&document.getElementById(D.toString())&&"RCMcontainer"!=b.parentNode.id&&"RCMcontainer"!=b.parentNode.parentNode.id&&"RCMcontainer"!=b.parentNode.parentNode.parentNode.id&&(document.getElementById("RCMcontainer")&&ac(),isNaN(y.m)&&h("trying to move a window without an  ID?!?!? 597"),wa=a.clientY-document.getElementById(D.toString()).offsetTop,xa=a.clientX-document.getElementById(D.toString()).offsetLeft,document.getElementById(D+"gMenu").style.width=
0,y.N="Moving",y.X="move",document.getElementById("Wallpaper").style.cursor="move",Lc())}else if(1==x.button)if("scrolling"==x.type){if(!document.getElementById("lExList")&&!b.classList.contains("letScroll")){x.type="";return}e-=a.clientY;document.getElementById(x.Ea).scrollTop+=e}else""==x.type&&(x.Na+10<a.clientY||x.Na-10>a.clientY)&&(document.getElementById("lExList")||b.classList.contains("letScroll"))&&(x.type="scrolling",x.startTime=new Date,document.getElementById("lExList")?x.Ea="lExList":
x.Ea=D+"Box");if(b.classList.contains("editEnable")||"TPFG"==b.className)Na&&!b.classList.contains("ttElem")&&(Na=!1,dd());else if(Ba)ed(a);else if(za)fd(a,y.m);else if(Sc)Uc(D,a);else if("sDrg"==y.N)gd(y.m,a);else if("sgDrag"==y.N)Vc(a);else if("svlDrag"==y.N)Wc(a);else if(hd(a,b),"Moving"==y.N)isNaN(y.m)&&h("moving a window without an  ID?!?!? 686"),b=document.getElementById(y.m),document.getElementById("RCMcontainer")&&(ac(),h("should never see!!!<br>menuDelete called from inside if Mdown.Action == moving)")),
d=a.clientX-xa,a=a.clientY-wa,"Ub"==v&&a<document.getElementById("UnityPanel").offsetHeight?a=document.getElementById("UnityPanel").offsetHeight-F:a<-F?a=-F:a+b.offsetHeight>document.getElementById("Wallpaper").offsetHeight&&a+b.offsetHeight<document.getElementById("Wallpaper").offsetHeight+16&&(a=document.getElementById("Wallpaper").offsetHeight-b.offsetHeight+F),0>d&&d>-(2*F)?d=-F:d+b.offsetWidth>document.getElementById("Wallpaper").offsetWidth&&d+b.offsetWidth<document.getElementById("Wallpaper").offsetWidth+
16&&(d=document.getElementById("Wallpaper").offsetWidth-b.offsetWidth+F),b.style.top=a+"px",b.style.left=d+"px";else if("launcerMD"==y.N)id(a);else if(""==y.m||"vid"==y.N.slice(0,3)?!b.className||"Wallpaper"==b.className||b.classList.contains("winTitle")||b.classList.contains("windowTopBar")||b.classList.contains("gMenu")||b.classList.contains("RCMenu")||(b=dc(b),b=0<b?document.getElementById(b):document.getElementById("Wallpaper")):d=b=document.getElementById(y.m),"Resizing"==y.N){if("auto"!=y.X&&
""!=y.m){b=document.getElementById(y.m+"Box");if("n-resize"==y.X|"ne-resize"==y.X|"nw-resize"==y.X)if(e=0,"Ub"==v&&(e=document.getElementById("UnityPanel").offsetHeight),a.clientY>e)if(e=parseInt(b.style.height.slice(0,-2),10)+(parseInt(d.style.top.slice(0,-2),10)-(a.clientY-F)),C[y.m].Window.F<e)b.style.height=e+"px",d.style.top=a.clientY-F+"px";else{e=parseInt(b.style.height.slice(0,-2),10);b.style.height=C[y.m].Window.F+"px";var f=parseInt(b.style.height.slice(0,-2),10);d.style.top=parseInt(d.style.top.slice(0,
-2),10)+(e-f)+"px"}else b.offsetTop>e&&(b.style.height=parseInt(b.style.height.slice(0,-2),10)+(parseInt(d.style.top.slice(0,-2),10)-(e-F))+"px",d.style.top=e-F+"px");if("s-resize"==y.X||"se-resize"==y.X||"sw-resize"==y.X)e=parseInt(d.style.top.slice(0,-2),10)+F,f=parseInt(document.getElementById(y.m+"TopBar").offsetHeight,10),e=a.clientY-f-e,b.style.height=C[y.m].Window.F<e?e+"px":C[y.m].Window.F+"px";if("w-resize"==y.X||"nw-resize"==y.X||"sw-resize"==y.X)e=parseInt(b.style.width.slice(0,-2),10)+
(parseInt(d.style.left.slice(0,-2),10)-(a.clientX-F)),C[y.m].Window.G<e?(b.style.width=e+"px",d.style.left=a.clientX-F+"px"):(e=parseInt(b.style.width.slice(0,-2),10),b.style.width=C[y.m].Window.G+"px",f=parseInt(b.style.width.slice(0,-2),10),d.style.left=parseInt(d.style.left.slice(0,-2),10)+(e-f)+"px");if("e-resize"==y.X||"ne-resize"==y.X||"se-resize"==y.X)e=a.clientX-(parseInt(d.style.left.slice(0,-2),10)+F),b.style.width=C[y.m].Window.G<e?e+"px":C[y.m].Window.G+"px";document.getElementById(y.m+
"gMenu").style.width=0;Nb(y.m);document.getElementById(y.m+"gMenu").style.width=b.offsetWidth-document.getElementById(y.m+"gMenu").offsetLeft+"px";"Ku"===v&&(document.getElementById(y.m+"Title"),e=document.getElementById(y.m+"appImg").offsetLeft+document.getElementById(y.m+"appImg").offsetWidth,document.getElementById(y.m+"Title").style.left=(document.getElementById(y.m+"MinButton").offsetLeft-e)/2-document.getElementById(y.m+"Title").offsetWidth/2+e+"px")}}else if(d.id==parseFloat(d.id)){e=b="";
f=C[d.id].Window.V+C[d.id].Window.ob+F;var g=C[d.id].Window.T+C[d.id].Window.kb+F+document.getElementById(d.id+"TopBar").offsetHeight;a.clientX>=C[d.id].Window.V&&a.clientX<=C[d.id].Window.V+F?b="w":a.clientX>=f&&a.clientX<=f+F&&(b="e");a.clientY>=C[d.id].Window.T&&a.clientY<=C[d.id].Window.T+F?e="n":a.clientY>=g&&a.clientY<=g+F&&(e="s");if(e||b)document.getElementById("Wallpaper").style.cursor=e+b+"-resize",Ea=d.id}else"default"!=document.getElementById("Wallpaper").style.cursor&&(document.getElementById("Wallpaper").style.cursor=
"default"),Ea&&=!1,jd()}}else h("targ is null (line 559")}}function $c(a){document.getElementById("RCMcontainer")&&"right"!=G.active&&"Quick"!=G.active&&("indicator"==G.active&&a.classList.contains("PanelIcons")?xc(a):("gMenuItems"==a.className||"kMenuItems"==a.className)&&dc(a)==G.Ya&&$b(a))}function bd(a){var b=a.id.split("_");"Lc"==b[0]&&(Na=!0,kd(a.id));"eL"!=b[0]&&"eN"!=b[0]&&"eC"!=b[0]||!document.getElementById("eC_"+b[1])||(document.getElementById("eC_"+b[1]).className="expoIconHover")}
function ad(){if(x.Da){var a=x.Da.id.split("_");"eL"!=a[0]&&"eN"!=a[0]&&"eC"!=a[0]||!document.getElementById("eC_"+a[1])||(document.getElementById("eC_"+a[1]).className="expoIcon")}}
function hd(a,b){b.classList.contains("toolTipclass")?(ld(a),Na=!0,Oc(parseFloat(b.id),b.id)):Na&&!b.classList.contains("ttElem")&&(Na=!1,dd());"screen_img"==b.className?gd(parseFloat(b.id),a):"TTnums"==b.className?fd(a,parseFloat(b.id)):"_BPgameArea"==b.id.slice(-11)&&(b=parseFloat(b.id),C[b].g.Ua=a.clientX-(document.getElementById(b).offsetLeft+8+document.getElementById(b+"Box").offsetLeft),C[b].g.tb=a.clientY-(document.getElementById(b).offsetTop+8+document.getElementById(b+"Box").offsetTop),C[b].g.L.left=
C[b].g.Ua-C[b].g.L.width/2,0==C[b].g.h.speed&&(C[b].g.h.left=C[b].g.L.left+(C[b].g.L.width/2-C[b].g.h.width/2)))}
function qb(a){window.clearTimeout(x.ta);var b=Gc(a);if("input"==b.nodeName.toLowerCase()||"form"==b.nodeName.toLowerCase())vb();else{var d=y.m;1>d.length&&(d=0);Sc?md(D,a):za?nd(y.m):Ba?od(y.m):Sa||Ra?pd(a,"",""):"click"===x.type&&"Moving"!=y.N&&"Resizing"!=y.N&&qd(a,b);rd(a,b);if(1==x.button&&"scrolling"==x.type){var e=(new Date).getTime(),f=(x.Sa-x.Na)/((e-x.startTime.getTime())/1E3),g=parseFloat(y.m);isNaN(g)&&(g=0);C[g].Vb=window.requestAnimationFrame(function(){Ec(g,f,e)})}""==y.m||"Moving"!=
y.N&&"Resizing"!=y.N||"full"==C[y.m].Window.H||"max"==C[y.m].Window.H||"min-max"==C[y.m].Window.H||("Moving"==y.N&&("Ub"==v?document.getElementById(d+"gMenu").style.width=document.getElementById(d).offsetWidth-document.getElementById(d+"gMenu").offsetLeft+"px":document.getElementById(d+"gMenu").style.width="100%"),oc(y.m));Pa&&"gMenuSub"!=G.active&&jd();0<D&&document.getElementById(D+"TopBar")&&(document.getElementById(D+"Title").style.cursor=document.getElementById(D+"TopBar").style.cursor="default");
"deleteMenu"==G.active||"deleteTitleMenu"==G.active||"deletegMenu"==G.active?(ac(),d=y.m,1>d.length&&(d=0)):"gMenuSub"==G.active&&(G.active="deletegMenu");if(Na&&0<H.style.opacity&&!x.O.classList.contains("toolTipclass"))sd();else if(x.O.classList&&x.O.classList.contains("toolTipclass")){Zc(a);return}a=x.Ea;vb();x.Ea=a}}
function qd(a,b){if(b.classList.contains("LauncherIconCover"))pd(a,T[parseInt(b.id.slice(3),10)].l,b.id);else if("kStartButton"==b.className||"kStartButton"==b.parentNode.className||"kTaskImg"==b.className)0==b.id.slice(2)?pd(a,b.id.slice(2),b.id):pd(a,C[b.id.slice(2)].Window.l,b.id);else if(0<b.id.indexOf("CloseButton"))pc(parseFloat(b.id));else if(0<b.id.indexOf("MinButton")){var d=parseFloat(b.id);(a=document.getElementById(d))&&!isNaN(parseInt(d,10))&&(a.hidden=!0,document.getElementById("b_"+
d).style.opacity="0.5","max"==C[d].Window.H?C[d].Window.H="min-max":"nor"==C[d].Window.H&&(C[d].Window.H="min-nor"),cc(a,"del"))}else if(0<b.id.indexOf("MaxButton"))sc(parseFloat(b.id));else if(0<b.id.indexOf("AOE"))C[parseFloat(b.id)].Window.Fa=!C[parseFloat(b.id)].Window.Fa;else if("lExpoClose"==b.id)Pb();else if("expoTabs"==b.className)b.parentNode.getElementsByClassName("expoTabSeld")[0].className="expoTabs",b.className="expoTabSeld",hc(b.id.slice(5));else if(0<=b.id.indexOf("notifyClose"))Fb(b.parentNode.id.slice(8));
else if("uLauncher"==b.id)pd(a,-1,"");else if("expoIconHover"==b.className||"expoIcon"==b.className||"LauncherIcon"==b.className||"expoName"==b.className)Pb(),U(b.id);else if(b.classList.contains("uButtons"))td(b);else if("contactFB"===b.id)U("_12");else if("sliderI-tg"===b.id.slice(0,10))ud(b);else if("FS"===b.id.slice(-2))V(parseFloat(b.id));else if("thm"===b.id.slice(0,3)&&(a=parseInt(b.id.split("_")[2],10),r!=a)){document.getElementById("UnityPanel").classList.remove(q[r].ka);document.getElementById("UnityPanel").classList.add(q[a].ka);
b=document.getElementsByClassName("windowTopBar");for(var e=0;e<b.length;e++)b[e].classList.remove(q[r].ka),b[e].classList.add(q[a].ka);b=document.getElementsByClassName("gMenu");for(e=0;e<b.length;e++)b[e].classList.remove(q[r].ka),b[e].classList.add(q[a].ka);b=document.getElementsByClassName("windowTopBar");for(e=0;e<b.length;e++)b[e].classList.remove(q[r].ka),b[e].classList.add(q[a].ka);document.getElementById("RCMcontainer")&&(document.getElementById("RCMcontainer").classList.remove(q[r].wa),
document.getElementById("RCMcontainer").classList.add(q[a].wa));H.classList.remove(q[r].wa);H.classList.add(q[a].wa);for(d in k)document.getElementById("NotyCont"+k[parseFloat(d)]).classList.remove(q[r].wa),document.getElementById("NotyCont"+k[parseFloat(d)]).classList.add(q[a].wa);r=a;Cc("webtopTheme",r)}}
function rd(a,b){if(b.classList.contains("LauncherIconCover"))Sa&&pd(a,"UP","");else if(b.classList.contains("RCMenu")){b=b.id.split("_");if("ql"==b[0]){a=b[1];b=b[2];if("create"==b)U("_"+T[a].l);else if("unlock"==b)T[a].locked=!1,1!=document.getElementById("T_"+a).style.opacity&&(rc(a),vd());else if("lock"==b)T[a].locked=!0,vd();else if("new"==b)U("newInstance_"+T[a].Window.l);else if("quit"==b)for(var d in C)C[parseFloat(d)].Window.l==a&&pc(d);Na=!1;dd()}else"gMenu"==b[2]?C[b[0]].D[b[3]].v[b[1]].j():
"rMenu"==b[2]?C[b[0]].ea[b[1]].j():"iMenu"==b[2]&&uc(b[0])[b[1]].j();G.active="deleteMenu"}else"tATnums"==b.className?od(parseFloat(b.id)):"TTnums"==b.className&&nd(parseFloat(b.id))}
function td(a){var b=a.id.split("_");if(1!=b.length)if("dm"==b[1])wd(b[0],b[2]);else if("wc"==b[1])"Figs"==b[2]?U("_"+fc(b[0])):"UPFigures"==b[2]&&xd(b[0]);else if("dmW"==b[1])"bOK"==b[2]&&yd(b[0],"OK"),"bNO"==b[2]&&yd(b[0],"NO");else if("stor"==b[1])zd(b[0],b[2]);else if("sImp"==b[1])Ad();else if("sExp"==b[1])Bd();else if("errNt"==b[1]){if(Cd(),a=document.getElementsByClassName("notifier"),0<a.length){b=a.length;for(var d=0;d<b;d++)Fb(a[d].id.slice(8))}}else"tATM"===b[1]||"tATB"===b[1]?Dd(a.id):
"tATOK"===b[1]?Ed(b[0]):"full"===b[1]?(L=b[0],$a.call(document.documentElement,function(){})):"storC"===b[1]?(Fd(b[2]),Fb(b[0])):"tg"===b[0]?ud(a):"wall"===b[0]&&Gd(b[1],b[2])}function kb(a){a.cancelable&&jb(a);var b=a.deltaY?-a.deltaY:a.wheelDelta;b=0<b?1:-1;Hd(Gc(a),b)}
function Hd(a,b){var d=dc(a);if(document.getElementById("lExList")||a.classList.contains("letScroll"))document.getElementById("lExList")?(x.Ea="lExList",d=0):(x.O=dc(a),isFinite(parseFloat(x.O))&&(x.Ea=parseFloat(x.O)+"Box")),C[d].Window.Vb=0>b?window.requestAnimationFrame(function(){Ec(d,-1E3,(new Date).getTime())}):window.requestAnimationFrame(function(){Ec(d,1E3,(new Date).getTime())});else if(a&&"select"==a.nodeName.toLowerCase()){var e=a.selectedIndex;0<=e+b&&e+b<=a.length-1&&(a.selectedIndex+=
b,"tATimer"==C[parseInt(a.id,10)].Window.I?Id(a.id,b):"WCalc"==C[d].Window.I?a.id==d+"Combo1"?Jd(a.selectedIndex,d):a.id==d+"Combo2"&&Kd(a.selectedIndex,d):"DM"==C[d].Window.I&&Ld(d))}else"uLauncher"==a.id||a.classList.contains("LauncherIconCover")?Md(b):"screen_img"==a.className?Sb(parseFloat(a.id),b):isFinite(d)&&"tATimer"==C[d].Window.I?Id(a.id,b):"TT"==a.className.slice(0,2)&&Nd(a.id,b)}
function Od(a){return{button:1,target:a.target,id:a.identifier,clientX:a.clientX,clientY:a.clientY,preventDefault:function(){},stopPropagation:function(){},cancelable:!0}}
function lb(a){for(var b=a.changedTouches,d=!1,e=0;e<b.length;e++){var f=b[e].identifier;z[f]=Od(b[e]);0<f&&window.clearTimeout(x.ta);z[f].target&&!z[f].target.classList.contains("editEnable")&&(0==f&&(pb(z[f]),ob(z[f])),d=!0)}Pd()&&(A.window=parseFloat(z[0].target.id),A.x[0]=z[0].clientX,A.y[0]=z[0].clientY,A.x[1]=z[1].clientX,A.y[1]=z[1].clientY);d&&jb(a)}
function mb(a){for(var b=a.changedTouches,d=!1,e=0;e<b.length;e++){var f=b[e].identifier;0<=f&&z.splice(f,1,Od(b[e]));if(z[f]&&(z[f].target=document.elementFromPoint(z[f].clientX,z[f].clientY),z[f].target&&!z[f].target.classList.contains("editEnable"))){if(Pd()){f=A.x[0]-A.x[1];var g=z[0].clientX-z[1].clientX;d=f-g;A.x[0]>A.x[1]&&(d=-d);f=A.y[0]-A.y[1];g=z[0].clientY-z[1].clientY;f-=g;A.y[0]>A.y[1]&&(f=-f);d=(d+f)/25;f=parseFloat(A.window);A.window&&("Screens"==C[f].Window.I?Sb(f,d):(f=d,d=document.getElementById(y.m),
g=parseFloat(d.offsetHeight)+f,d.style.height=C[y.m].Window.F<g?g+"px":C[y.m].Window.F+"px",f=parseFloat(d.offsetWidth)+f,d.style.width=C[y.m].Window.G<f?f+"px":C[y.m].Window.G+"px",document.getElementById(y.m+"gMenu").style.width=0,Nb(y.m),document.getElementById(y.m+"gMenu").style.width=d.offsetWidth-document.getElementById(y.m+"gMenu").offsetLeft+"px","Ku"===v&&(document.getElementById(y.m+"Title"),d=document.getElementById(y.m+"appImg").offsetLeft+document.getElementById(y.m+"appImg").offsetWidth,
document.getElementById(y.m+"Title").style.left=(document.getElementById(y.m+"MinButton").offsetLeft-d)/2-document.getElementById(y.m+"Title").offsetWidth/2+d+"px")));A.x[0]=z[0].clientX;A.x[1]=z[1].clientX;A.y[0]=z[0].clientY;A.y[1]=z[1].clientY}else pb(z[f]);d=!0}}d&&jb(a)}
function nb(a){for(var b=a.changedTouches,d=!1,e=0;e<b.length;e++){var f=b[e].identifier;0<=f&&z[f]&&(z[f].target?(ad(),z[f].target.classList.contains("editEnable")&&(d=!0)):(z[f].target=document.getElementById("Wallpaper"),d=!0),qb(z[f]),delete z[f])}A={window:0,x:[0,0],y:[0,0]};d||(0==a.cancelable&&(a.cancelable=!0,a.cancelBubble=!0,a.bubbles=!1),jb(a))}function Pd(){var a=0,b=[],d;for(d in z){var e=parseFloat(z[parseFloat(d)].target.id);e&&(b[a]=e,a++)}return 2==a&&b[0]==b[1]?!0:!1}
function Lc(){document.getElementById("winCover").style.height="100%";Pa=1}function jd(){Pa&&(document.getElementById("winCover").style.height="0",Pa=0)}
function Kc(a,b){jb(a);Sa||(1==x.button?(x.type="click",x.startTime=new Date,x.wb=a.clientX,x.Na=a.clientY,x.ta=window.setTimeout(function(){Nc(a,b,document.getElementById(b))},500),-1==b?(N="uLauncher",Ua=document.getElementById(N).offsetTop,Ta=document.getElementById(N).offsetLeft):(Ua=document.getElementById(b).parentNode.parentNode.offsetTop,Ta=document.getElementById(b).parentNode.parentNode.offsetLeft,N=parseInt(b.split("_")[1],10)),wa=a.clientY-Ua,xa=a.clientX-Ta,y.N="launcerMD"):3==x.button&&
Yc(b.split("_")[1]))}
function id(a){if(!Wa){Wa=!0;if("launcerMD"==y.N){var b=document.getElementById("uLauncher");if(Sa){b=!1;var d=a.clientX-xa;a=a.clientY-wa;document.getElementById("C_"+N).style.top=a-6+"px";document.getElementById("C_"+N).style.left=d-6+"px";d=S.indexOf(Number(N));try{for(var e in S){if(99!=S[Number(e)]){var f=document.getElementById("C_"+S[Number(e)]);if(e!=d&&f.offsetTop-24<a&&f.offsetTop+f.offsetHeight>a+24)if(e<d)for(var g=d-1;g>=e;g--){var l=document.getElementById("C_"+S[Number(g)]);document.getElementById("uLauncher").removeChild(l);
var m=S.splice(d,1);document.getElementById("uLauncher").insertBefore(l,document.getElementById("C_"+N).nextElementSibling);d--;S.splice(d,0,m[0]);b=!0}else for(g=d+1;g<=e;g++)l=document.getElementById("C_"+S[Number(g)]),document.getElementById("uLauncher").removeChild(l),m=S.splice(d,1),document.getElementById("uLauncher").insertBefore(l,document.getElementById("lSpacer")),d++,S.splice(d,0,m[0]),b=!0}if(b)break}}catch(p){}}else Ra?(e=a.clientY-wa,24<e?e=24:e+b.offsetHeight<document.getElementById("Wallpaper").offsetHeight&&
(e=document.getElementById("Wallpaper").offsetHeight-b.offsetHeight),b.style.top=e+"px"):wa+Ua-12>a.clientY||wa+Ua+12<a.clientY?(Ra=!0,Na=Sa=!1,dd()):isFinite(N)&&xa+Ta+20<a.clientX&&(e=N,"99"!=e&&"0"!=e&&(Sa=!0,Na=Ra=!1,dd(),wa=Ua+21,xa=Ta+21,document.getElementById("T_"+N).style.opacity=0,document.getElementById("Tl").style.opacity=0,e=document.getElementById("C_"+N),e.style.top=e.offsetTop+"px",e.style.left=e.offsetLeft+"px",e.style.position="absolute",f=document.createElement("div"),f.id="lSpacer",
f.className="LauncherContainer",document.getElementById("uLauncher").insertBefore(f,e)))}Wa=!1}}
function pd(a,b,d){jb(a);window.clearTimeout(Va);0<=b&&!Ra&&!Sa&&"Quick"!=G.active?2==x.button?U("newInstance_"+b+"_"+d):U("L_"+b+"_"+d):Sa&&(document.getElementById("uLauncher").removeChild(document.getElementById("lSpacer")),a=document.getElementById("C_"+N),a.style.position="",a.style.top="",a.style.left="",0<D&&(document.getElementById("Tl").style.top=document.getElementById("C_"+parseInt(C[parseFloat(D)].Window.l,10)).offsetTop+10+"px",document.getElementById("Tl").style.opacity=1),.5==document.getElementById("D_"+
N).style.opacity&&(document.getElementById("T_"+N).style.opacity=1),vd());Sa=Ra=!1}function Md(a){var b,d=document.getElementById("uLauncher");0<a?b=document.getElementById("uLauncher").offsetTop+30:b=document.getElementById("uLauncher").offsetTop-30;24<b?b=24:b+d.offsetHeight<document.getElementById("Wallpaper").offsetHeight&&(b=document.getElementById("Wallpaper").offsetHeight-d.offsetHeight);d.style.top=b+"px"};var Cb="style=\"background:center/contain no-repeat url('images/allTheSocials/",u=' src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAACAQMAAABIeJ9nAAAAA1BMVEUAAACnej3aAAAAAXRSTlMAQObYZgAAAApJREFUCNdjAAIAAAQAASDSLW8AAAAASUVORK5CYII="',R=[{l:1,C:"#00ff21",M:"app",u:" -104px -135px",appName:"TeaTimer",K:"tt_Init"},{l:2,C:"#00b6b6",M:"app",u:" -208px -83px",appName:"Wage Calculator",K:"wc_Init"},{l:3,C:"#00ff00",M:"app",u:" -0px -135px",appName:"DUMbasic",K:"screen_Init"},{l:4,C:"#996b28",M:"app",
u:" -0px -83px",appName:"Private Diary",K:"screen_Init"},{l:5,C:"#00ff00",M:"app",u:" -156px -83px",appName:"Dosh Manager",K:"dm_Init"},{l:6,C:"#00ff00",M:"game",u:" -52px -135px",appName:"JS Cavern",Ma:"jscavern/index.html",Ca:"StewVed",La:"",Ka:"",K:"if_Init"},{l:7,C:"#8c8b8c",M:"game",u:" -52px -83px",appName:"ArcNerd",K:"bp_Init"},{l:8,C:"#8c8b8c",M:"app",u:" -104px -83px",appName:"Browser Benchmarker",K:"bb_Init"},{l:9,C:"#fffedd",M:"game",u:" -156px -135px",appName:"WordSearch",Ma:"wordsearch/index.html",
Ca:"StewVed",La:"",Ka:"",K:"if_Init"},{l:11,C:"#5e5e4d",M:"app",u:" -260px -135px",appName:"Video Player",K:"vid_Init"},{l:12,C:"#fffedd",M:"help",u:" -156px -187px",appName:"Feedback / Contact",K:"zFbInit"},{l:13,C:"#00ff00",M:"sett",u:" -0px -187px",appName:"Change Background",K:"wall_Init"},{l:15,C:"#fffedd",M:"sett",u:" -208px -187px",appName:"Storage",K:"Win_storage"},{l:16,C:"#fffedd",M:"app",u:" -260px -187px",appName:"Tillago Timer",K:"tAT_Init"},{l:17,C:"#fffedd",M:"app",u:" -0px -239px",
appName:"App Timer",K:"screen_Init"},{l:18,C:"#fffedd",M:"app",u:" -52px -239px",appName:"Event Manager",K:"screen_Init"},{l:19,C:"#fffedd",M:"sett",u:" -104px -239px",appName:"Desktop Chooser",K:"dChoose"},{l:21,C:"#fffedd",M:"app",u:" -156px -239px",appName:"Tone Generator",K:"tg_Init"},{l:22,C:"#fffedd",M:"app",u:" -260px -239px",appName:"Calories per grams calculator",K:"cpw_Init"},{l:25,C:"#00ff00",M:"app",u:" -156px -83px",appName:"Savings Vs Loans",K:"svl_Init"},{l:26,C:"#00ff00",M:"sett",
u:" -0px -292px",appName:"Theme Chooser",K:"theme_Init"},{l:100,C:"#00dd00",M:"help",u:" -208px -135px",appName:"About StewVed&apos;s Webtop",K:"Win_createDialogueInit"},{l:101,appName:"Toddler Colors",C:"#3aaff0",M:"game",u:"https://stewved.github.io/toddlercolors/favicon.png",pb:"https://github.com/StewVed/toddlercolors",Ma:"https://stewved.github.io/toddlercolors/index.html",Ca:"StewVed",Qa:"https://stewved.github.io",La:"https://stewved.github.io",Ka:"https://stewved.github.io/toddlercolors/README.md",
K:"if_Init"},{l:102,appName:"MemGuess",C:"#3aaff0",M:"game",u:"https://stewved.github.io/memguess/favicon.png",pb:"https://github.com/StewVed/memguess",Ma:"https://stewved.github.io/memguess/index.html",Ca:"StewVed",Qa:"https://stewved.github.io",La:"https://stewved.github.io",Ka:"https://stewved.github.io/memguess/README.md",K:"if_Init"},{l:103,appName:"toddlearner",C:"#3aaff0",M:"game",u:"https://stewved.github.io/toddlearner/favicon.png",pb:"https://github.com/StewVed/toddlearner",Ma:"https://stewved.github.io/toddlearner/index.html",
Ca:"StewVed",Qa:"https://stewved.github.io",La:"https://stewved.github.io",Ka:"https://stewved.github.io/toddlearner/README.md",K:"if_Init"},{l:104,appName:"toddlearner",C:"#3aaff0",M:"game",u:"https://stewved.github.io/audiotester/favicon.png",pb:"https://github.com/StewVed/audiotester",Ma:"https://stewved.github.io/audiotester/index.html",Ca:"StewVed",Qa:"https://stewved.github.io",La:"https://stewved.github.io",Ka:"https://stewved.github.io/audiotester/README.md",K:"if_Init"},{l:105,appName:"Calorie Calculator",
C:"#fffedd",M:"app",u:"https://stewved.github.io/calorieCalculator/favicon.png",pb:"https://github.com/StewVed/calorieCalculator",Ma:"https://stewved.github.io/calorieCalculator/index.html",Ca:"StewVed",Qa:"https://stewved.github.io",La:"https://stewved.github.io",Ka:"https://stewved.github.io/calorieCalculator/README.md",K:"if_Init"}],Qd=[{l:0,appName:"All apps",u:" -283px -16px",C:"#fff",locked:!0},{l:8,appName:"Browser Benchmarker",u:" -104px -83px",C:"#8c8b8c",locked:!0},{l:9,appName:"WordSearch",
u:" -156px -135px",C:"#fffedd",locked:!0},{l:5,appName:"Dosh Manager",u:" -156px -83px",C:"#00ff00",locked:!0},{l:6,appName:"JS Cavern",u:" -52px -135px",C:"#00ff00",locked:!0}],T=[],S=[],Bb=[{Text:"Fullscreen toggle",j:function(){V("0")}},{Text:"Change Background...",j:function(){U("_13")}},{Text:"<hr>"},{Text:"About StewVed&apos;s Webtop",j:function(){U("stewvedsWebtop-StewVed&apos;s Webtop_100")}},{Text:"StewVed&apos;s Webtop Changelog",j:function(){U("SiteCL-StewVed&apos;s Webtop_100")}},{Text:"Webtop Statistics",
j:function(){U("_14")}},{Text:"",j:function(){Cd()}}],vc=[{Text:"For Rizz...",j:function(){Gb()}},{Text:"TillAgoTimer",j:function(){U("_16")}},{Text:"TeaTimer",j:function(){U("_1")}}],wc=[{Text:"Volume Control"}],ab=[{Text:'<p class="B pZW">Contact StewVed:</p>'},{Text:"Feedback / Contact Webapp",j:function(){U("_12")}},{Text:'<img class="imgSocs" '+Cb+"Facebook.png');\""+u+">Stewved's Webtop on FaceBook",j:function(){Db("https://www.facebook.com/StewvedsWebtop")}},{Text:'<img class="imgSocs" '+Cb+
"Facebook.png');\""+u+">Stewved on FaceBook",j:function(){Db("https://www.facebook.com/Stewved")}},{Text:'<img class="imgSocs" '+Cb+"Twitter.png');\""+u+">Stewved on Twitter",j:function(){Db("https://twitter.com/StewVed")}},{Text:"<hr>"}];function Pb(){document.getElementById("lExpo").style.opacity=0;window.setTimeout(function(){document.getElementById("lExpo")&&document.getElementById("lExpo").parentNode.removeChild(document.getElementById("lExpo"))},300)}
function kc(a,b){if(C[a].Window.Y){var d=C[a].Window.l;if("all"==b){T[C[a].Window.l]={l:R[C[a].Window.Y].l,appName:R[C[a].Window.Y].appName,u:R[C[a].Window.Y].u,C:R[C[a].Window.Y].C,locked:!1};S.push(d);var e=document.createElement("div");e.id="C_"+d;e.className="LauncherContainer";var f='<img id="T_'+d+'" class="lTriangle" '+B+' -131px -44px;opacity:1;"'+u+">";f+='<div id="D_'+d+'" class="LauncherIconBack" style="background-color:'+T[d].C+';opacity:0.5;"></div>';f+='<img id="L_'+d+'" class="LauncherIcon" ';
f=" -"==T[d].u.slice(0,2)?f+(B+T[d].u+';"'+u+">"):f+("style=\"background:center/contain no-repeat url('"+T[d].u+"');\""+u+">");f+='<img id="Lc_'+d+'" class="LauncherIconCover ttElem" '+B+' -198px -26px;"'+u+">";e.innerHTML=f;document.getElementById("uLauncher").appendChild(e)}if("all"==b||"ku"==b)b=document.createElement("div"),b.id="b_"+a,b.className="kStartButton",f='<div id="f_'+a+'" class="kTask"></div><img id="i_'+(a+'" class="kTaskImg"')," -"==T[C[a].Window.l].u.slice(0,2)?(d=T[C[a].Window.l].u.split(" "),
f+='style="background-image: url('+t.src+");background-position:"+.313725490196*parseFloat(d[1])+"px "+.313725490196*(parseFloat(d[2])-1)+'px;"'):f+="style=\"background:center/contain no-repeat url('"+T[C[a].Window.l].u+"');\"",f+=u+'><div id="t_'+a+'" class="kTaskTitle">'+T[C[a].Window.l].appName+"</div>",b.innerHTML=f+"</div>",document.getElementById("kTaskBar").appendChild(b),document.getElementById("b_"+a).addEventListener("mouseover",function(){document.getElementById("f_"+a).classList.add("kTaskH")},
!1),document.getElementById("b_"+a).addEventListener("mouseout",function(){document.getElementById("f_"+a).classList.remove("kTaskH")},!1)}Qb("change")}function db(){var a=cb("Launcher Icons");if(a)try{var b=a.split(P);for(a=0;a<b.length-1;a++){var d=b[a].split(O);if(100!=d[0])T[d[0]]={l:d[0],appName:d[1],u:d[2],C:d[3],locked:"true"===d[4]},S.push(parseFloat(d[0]));else var e=!0;e&&vd()}T[0]||Rd()}catch(f){Rd()}else Rd()}
function vd(){var a="",b;for(b in S)1==T[S[parseFloat(b)]].locked&&(a+=T[S[parseFloat(b)]].l+O+T[S[parseFloat(b)]].appName+O+T[S[parseFloat(b)]].u+O+T[S[parseFloat(b)]].C+O+T[S[parseFloat(b)]].locked+P);a&&Cc("Launcher Icons",a)}function Rd(){S=[];T=[];var a;for(a in Qd){var b=parseFloat(Qd[parseFloat(a)].l);T[b]=Qd[parseFloat(a)];S.push(b)}}
function hc(a){var b=Q/120,d=parseInt(120+(b-parseInt(b,10))/parseInt(b,10)*120,10);b='style="width:'+d+'px;"';d=Math.floor((d-51)/2);var e="",f=!1,g;for(g in R){if("Ub"==v)for(var l in T)if(R[parseFloat(g)].l==T[parseFloat(l)].l){f=!0;break}"all"!=a&&a!=R[parseFloat(g)].M&&(f=!0);if(f)f=!1;else{var m=R[parseFloat(g)].appName;m=m.replace(/'/g,"'");e+='<div id="eC_'+R[parseFloat(g)].l+'" class="expoIcon" '+b+' ">';e=" -"==R[parseFloat(g)].u.slice(0,2)?e+('<img id="eL_'+R[parseFloat(g)].l+'" class="LauncherIcon" '+
B+R[parseFloat(g)].u+";transform:scale(1.5);left:"+d+'px;top:18px;"'+u+" >"):e+('<img id="eL_'+R[parseFloat(g)].l+'" class="LauncherIcon"  style="background:center/contain no-repeat url(\''+R[parseFloat(g)].u+"');left:"+d+'px;top:18px;width:51px;height:51px;transform: scale(1.5);"'+u+" >");e+='<div id="eN_'+R[parseFloat(g)].l+'" class="expoName" style="top:84px;" >'+m+"</div></div>"}}document.getElementById("lExList").innerHTML=e}
function gc(a,b){return a.appName<b.appName?-1:a.appName>b.appName?1:0}
function Qb(a){var b=document.getElementById("Wallpaper").offsetHeight-document.getElementById("UnityPanel").offsetHeight,d=58*S.length+6,e=document.getElementById("uLauncher");e.style.height=d>b?d+"px":b+"px";b=e.offsetTop;"change"==a&&(b=document.getElementById("Wallpaper").offsetHeight-e.offsetHeight);b>document.getElementById("UnityPanel").offsetHeight?b=document.getElementById("UnityPanel").offsetHeight:b+e.offsetHeight<document.getElementById("Wallpaper").offsetHeight&&(b=document.getElementById("Wallpaper").offsetHeight-
e.offsetHeight);e.style.top=b+"px";document.getElementById("indicatorPanel");a=document.getElementById("kTaskBar").childNodes;if(e=a.length-1)for(b=a[1].offsetWidth*e,d=document.getElementById("kTaskBar").offsetWidth-document.getElementById("b_0").offsetWidth,b=b>d||256*e>d?Math.floor(d/e)-2:256,d=1;d<=e;d++)a[d].style.width=b+"px"}
function Yc(a){document.getElementById("RCMcontainer")&&ac();var b='class="RCMenu '+q[r].va+'" ';var d='<div id="ql_'+a+'_create" style="font-weight:bold;" '+b+">"+T[a].appName+"</div>";if(0!=a&&99!=a&&100!=parseInt(a,10)){d=T[a].locked?d+('<div id="ql_'+a+'_unlock" '+b+">Unlock from Launcher</div>"):d+('<div id="ql_'+a+'_lock" '+b+">Lock to Launcher</div>");var e=0,f=parseInt(a,10),g;for(g in C)parseInt(C[parseFloat(g)].Window.l,10)==f&&(e+=1);e&&(d=d+('<div id="ql_'+a+'_new" '+b+'>New Window (middle Click)</div><div id="ql_')+
(a+'_quit" '+b),d=1==e?d+">Quit</div>":d+">Close all windows</div>")}else d='<p style="margin:6px;padding:0;">'+d+'<p style="margin:6px;padding:0;">';0!=d.length&&(bc(d),G.active="Quick",kd(a),a=document.getElementById("C_"+a).offsetTop+document.getElementById("uLauncher").offsetTop+26,J.style.top=a-J.offsetHeight/2+"px",K.style.top=J.offsetTop-1+"px",a=document.getElementById("RCMcontainer"),a.style.left="70px",a.style.top=J.offsetTop-8+"px",J.style.left="63px",K.style.left="62px",H.style.opacity=
I.style.opacity=0,J.style.opacity=K.style.opacity=1,J.style.zIndex=9999,J.style.background="linear-gradient(45deg, rgba(38,38,38,1) 45%, rgba(0,0,0,0) 45%)")}function rc(a){delete T[a];var b=parseFloat(a);if(ua||"Ub"==v)b=parseInt(a,10);S.splice(S.indexOf(b),1);document.getElementById("uLauncher").removeChild(document.getElementById("C_"+a));Qb("close")}
function kd(a){if(!Ra&&!Sa&&"Quick"!=G.active){a=Number(a.split("_")[1]);var b=document.getElementById("C_"+a).offsetTop+document.getElementById("uLauncher").offsetTop+26;J.style.background="linear-gradient(45deg, rgba(38,38,38,1) 45%, rgba(0,0,0,0) 45%)";K.style.border="1px solid rgba(255,255,255,0.5)";K.style.borderTop="0px";K.style.borderRight="0px";H.style.left="70px";I.style.left="70px";J.style.left="63px";K.style.left="62px";H.innerHTML=T[a].appName;J.style.top=b-J.offsetHeight/2+"px";H.style.top=
b-H.offsetHeight/2+"px";I.style.top=H.offsetTop-1+"px";I.style.width=H.offsetWidth-1+"px";I.style.height=H.offsetHeight+"px";K.style.top=J.offsetTop-1+"px";H.style.opacity=I.style.opacity=J.style.opacity=K.style.opacity=.9}};var Sd="<^>",Ud="<*>",Vd=0,X;window.Win_storage=function(a){C[a].Window.I="storage";document.getElementById(a+"Box").style.padding="4px";document.getElementById(a+"Box").style.backgroundColor="#fff";Wd(a);C[a].Window.o=document.getElementById(a+"Cont").offsetWidth;C[a].Window.s=document.getElementById(a+"Cont").offsetHeight;C[a].Window.G=200;C[a].Window.F=Math.round(C[a].Window.s/4)};
function Wd(a){var b='This webtop uses <a class="ubLink" style="color:#000;" href="http://www.w3schools.com/html/html5_webstorage.asp" target="_blank">HTML5 Local Storage</a>, (better than cookies).<br>Listed below is all of the stuff currently stored:<br><br><button id="'+(a+'_sImp_" class="uButtons uButtonGrey" style="float:left;font-size:1.5em;width:40%;margin-left:2%;" type="button">Import Data</button><button id="'+a+'_sExp_" class="uButtons uButtonGrey" style="float:right;font-size:1.5em;width:40%;margin-right:2%;" type="button">Export Data</button><br><br>');
var d=0;"undefined"!==typeof Storage&&(d=X.length);if(0<d)for(var e=0;e<d;e++){var f=X.key(e);b+='<div id="'+a+f+'" style="margin-bottom:6px;margin:10px 0px 10px 2%;padding-left:4px;">'+f+'&nbsp;&nbsp;<button id="'+a+"_stor_"+f+'" class="uButtons uButtonGrey" style="position:absolute;" type="button">Delete</button></div>'}else b+="<p>Nothing is currently stored.<br>When you change something on the webtop,<br>you can choose for your browser to remember it.</p>";document.getElementById(a+"Box").innerHTML=
b;if(0<d){for(e=b=0;e<d;e++)f=X.key(e),document.getElementById(a+"_stor_"+f).offsetLeft>b&&(b=document.getElementById(a+"_stor_"+f).offsetLeft);for(e=0;e<d;e++)f=X.key(e),document.getElementById(a+"_stor_"+f).style.left=b+"px"}}function bb(){try{if(X=window.localStorage)if(X.length){var a=cb("AllowSave");Vd=1==a?1:0==a?-1:0}else Vd=0}catch(b){}-1===Vd&&h("localStorage appears to be unavailable in this browser. Unable to save anything.")}
function Fd(a){if("Y"==a){a=Vd[0];var b=Vd[1];Vd=1;Cc("AllowSave",Vd);Cc(a,b)}else Vd=-1}function zd(a,b){try{X.removeItem(b),document.getElementById(a+b).parentNode.removeChild(document.getElementById(a+b))}catch(d){}}function cb(a){var b="";if(-1!=Vd)try{b=X.getItem(a)}catch(d){}return b}
function Cc(a,b){if(1==Vd)for(X.setItem(a,b),a=0;a<E.length;a++)"storage"==C[E[a]].Window.I&&Wd(E[a]);else 0!=Vd||document.getElementById("_stor_Y")||(Vd=[a,b],h('Would you like your browser to remember your settings?<br>(Using <a class="ubLink" href="http://www.w3schools.com/html/html5_webstorage.asp" target="_blank">HTML5 Local Storage</a>, (better than cookies).)<br><br><button id="_storC_Y" class="uButtons uButtonGreen" type="button " style="font-size:1.5em;width:30%;margin:4px;float:left;">Yes</button><button id="_storC_N" class="uButtons uButtonRed" type="button" style="font-size:1.5em;width:30%;margin:4px;float:right;">No</button>'))}
function Bd(){var a="",b=0;"undefined"!==typeof Storage&&(b=X.length);if(0<b){for(var d=0;d<b;d++)a+=X.key(d)+Sd,a+=X.getItem(X.key(d))+Ud;b=document.createElement("a");b.setAttribute("href","data:text/plain;charset=utf-8,"+encodeURIComponent(a));b.download="stewVedsWebtopData";b.style.display="none";document.body.appendChild(b);b.click();document.body.removeChild(b)}}
function Ad(){var a=document.createElement("input");a.setAttribute("type","file");a.style.display="none";document.body.appendChild(a);a.addEventListener("change",function(){Xd(this.files)},!1);a.click();document.body.removeChild(a)}
function Xd(a){if(window.File&&window.FileReader){var b=new FileReader;b.onload=function(){var d=b.result;X.clear();d=d.split(Ud);try{for(var e=0;e<d.length-1;e++){var f=d[e].split(Sd);X.setItem(f[0],f[1])}v=cb("webtopStyle");location.reload()}catch(g){alert("I am sorry, but the import failed.")}};b.readAsText(a[0])}else alert("Your broswer appears to not support HTML5 File Reading.")};var q=[{name:"StewVed Dark",ka:"zThStewVedMain",wa:"zThStewVedMenu",va:"zThStewVedMenH"},{name:"Ubuntu Ambiance",ka:"zThAmbianceMain",wa:"zThAmbianceMenu",va:"zThAmbianceMenH"}],r=0;
window.theme_Init=function(a){var b=C[a].Window;b.o=640;b.s=240;b.G=320;b.F=240;b.I="thm";b.S=1;b.ca=1;document.getElementById(a);b=document.getElementById(a+"Box");b.style.backgroundColor="#fff";b.style.padding="4px";for(var d='<div style="position:relative;width:96%;height:32px;"></div>',e=0;e<q.length;e++)d+='<div id="thm_'+a+"_"+e+'" class="'+q[e].ka+'" style="position:relative;width:96%;left:2%;border:0;box-shadow:0px 0px 14px #000;border-radius:8px 8px 0px 0px;cursor:default;height:32px;font-size:28px;color:#fff;text-align:center;">'+
q[e].name+'</div><div style="position:relative;width:96%;height:32px;"></div>';b.innerHTML=d+('<div id="thm_'+a+'_cover" NaN');document.getElementById(a+"Box").style.width=Math.round(.8*Q)+"px";C[a].Window.o=document.getElementById(a+"Cont").offsetWidth;C[a].Window.s=document.getElementById(a+"Cont").offsetHeight;C[a].Window.G=Math.floor(C[a].Window.o/3);C[a].Window.F=C[a].Window.s};function dd(){"Quick"!=G.active&&window.setTimeout(function(){Na||(sd(),Ma="",H.innerHTML="")},10)}function sd(){window.clearTimeout(La);H.style.opacity=I.style.opacity=J.style.opacity=K.style.opacity=Ha.style.opacity=0;H.style.top="-"+H.offsetHeight+"px";I.style.top="-"+I.offsetHeight+"px";I.style.width="0px";J.style.top="-"+J.offsetHeight+"px";K.style.top="-"+K.offsetHeight+"px";Ha.style.top="-"+Ha.offsetHeight+"px"}
function Tc(){H.style.opacity=I.style.opacity=J.style.opacity=K.style.opacity=.9}function ld(a){var b=parseFloat(Gc(a).id);isNaN(b)||.9==H.style.opacity&&Pc(Gc(a).id,!0)}function Oc(a,b){Ma!=b&&isFinite(a)&&(a=C[a].Sb[b.split("_")[1]],Ma=b,Oa='<span id="pupCapt">'+a+"</span>",La=window.setTimeout(function(){Pc(b,!1)},400))}
function Jb(){J.style.left=x.Ra-J.offsetWidth/2+"px";J.style.top=x.Sa-J.offsetHeight-F+"px";Ha.style.top=J.offsetTop+F+"px";Ha.style.height=J.offsetHeight+"px";H.style.top=J.offsetTop-(H.offsetHeight-J.offsetHeight/1.5)+"px";var a=document.getElementById("Wallpaper").offsetWidth;a=x.Ra+2+H.offsetWidth/2>a?a-2-H.offsetWidth:x.Ra-H.offsetWidth/2;0>a&&(a=1);H.style.left=a+"px";I.style.left=Ha.style.left=H.offsetLeft-1+"px";I.style.top=H.offsetTop-1+"px";I.style.width=Ha.style.width=H.offsetWidth+"px";
I.style.height=H.offsetHeight+"px";K.style.left=J.offsetLeft+"px";K.style.top=J.offsetTop+"px";K.style.width=J.offsetWidth+"px";K.style.height=J.offsetHeight+1+"px";K.style.border="1px solid rgba(255,255,255,0.5)";K.style.borderTop="0px";K.style.borderLeft="0px"}function Zc(a){var b=parseFloat(x.Da.id),d=x.O.id;ld(a);Na=!0;Oc(b,d);Pc(d,!1);window.clearTimeout(La)}
function Pc(a,b){Ma==a?(H.innerHTML='<p style="margin:0;padding:0;text-align:center;">'+Oa.replace(/~#/g,"&").replace(/#Q/g,"&quot").replace(/-Q-/g,'\\"')+"</p>",Yd(H),J.style.background="linear-gradient(315deg, rgba(0,0,0,1) 36%, rgba(0,0,0,0) 40%)",Jb(),b||Tc()):b||sd()}function Yd(a){a=a.children;for(var b=0;b<a.length;b++)"br"!=a[b].nodeName.toLowerCase()&&a[b].classList.add("ttElem"),0<a[b].childElementCount&&Yd(a[b])};var Zd,$d,Y=[],Sc,ae,W,Z=[],be=1;window.Slids=Z;
window.wall_Init=function(a){var b=C[a].Window;b.o=640;b.s=240;b.G=320;b.F=240;b.I="wall";b.S=1;b.ca=1;C[a].D=[{Text:"Reset",v:[{Text:"Reset to defaults",j:function(){ce(a)}}]}];document.getElementById(a);b=document.getElementById(a+"Box");b.style.backgroundColor="#fff";b.style.padding="4px";b.innerHTML='<button id="wall_'+a+'_s" type="button" class="uButtonLeft uButtons uButtonGrey" style="width:28%;height:32px;margin-left:4px;" value="0">Solid</button><button id="wall_'+a+'_l" type="button" class="uButtons uButtonGrey uButtonMid" style="width:28%;height:32px;margin-left:-1px;margin-right:-1px;" value="0">Linear</button><button id="wall_'+
a+'_r" type="button" class="uButtons uButtonGreen uButtonRight" style="width:28%;height:32px;margin-right:4px;" value="1">Circle</button><button id="wall_'+a+'_f" type="button" class="uButtons uButtonGrey" style="width:14%;height:32px;" value="0">Follow</button><br><br><div class="uButtons" style="float:left;clear:both;opacity:0;padding:8px;width:20%;"></div><button id="wall_'+a+'_1" type="button" class="uButtons uButtonGreen uButtonLeft" style="width:28%;height:32px;left:25%;" value="1">Color 1<span id="wall_'+
a+'_c1" style="background: hsl(0, 0%, 100%);height:24px;margin:-5px 0px 0px 8px;width:24px;position:absolute;border-radius:16px;"></span></button><button id="wall_'+a+'_2" type="button" class="uButtons uButtonGrey uButtonRight" style="width:28%;height:32px;margin-right:4px;" value="0">Color 2<span id="wall_'+a+'_c2" style="background: hsl(0, 0%, 100%);height:24px;margin:-5px 0px 0px 8px;width:24px;position:absolute;border-radius:16px;"></span></button><p id="wallH" class="cBtext" style="clear:both;">Hue</p>'+
de(1)+'<p id="wallS" class="cBtext">Saturation</p>'+de(2)+'<p id="wallL" class="cBtext">Luminocity</p>'+de(3)+'<p id="wallP" class="cBtext">overall color % <input id="wall_'+a+'_Ch" type="checkbox" class="editEnable uButtons" style="font-size:1.5em;margin:0px 6px 0px 0px;padding:0;border:0;vertical-align:middle;width:26px;height:26px;"></p>'+de(4)+"<br><br>";document.getElementById(a+"Box").style.width=Math.round(.8*Q)+"px";C[a].Window.o=document.getElementById(a+"Cont").offsetWidth;C[a].Window.s=
document.getElementById(a+"Cont").offsetHeight;C[a].Window.G=Math.floor(C[a].Window.o/3);C[a].Window.F=C[a].Window.s;document.getElementById("wall_"+a+"_Ch").checked="%"==Y[0].split(-1);document.getElementById("wall_"+a+"_Ch").checked?document.getElementById("wallSlidera4").style.opacity=.25:document.getElementById("wallSlidera4").style.opacity=1;W&&document.getElementById("wall_"+a+"_f").classList.add("uButtonGreen");Tb(a);a&&(document.getElementById("wall_"+a+"_c1").style.background=Y[0],document.getElementById("wall_"+
a+"_c2").style.background=Y[1]);ee(a)};
function Tb(a){var b=Y[be-1].split(") "),d=b[0].slice(4).split(",");Z[0]=d[0]/3.6/100;Z[1]=parseFloat(d[1])/100;Z[2]=parseFloat(d[2])/100;b[1]&&"%"==b[1].slice(-1)?(Z[3]=parseFloat(b[1])/100,document.getElementById("wall_"+a+"_Ch").checked=!0,document.getElementById("wallSlidera4").style.opacity=1):(Z[3]=0,document.getElementById("wall_"+a+"_Ch").checked=!1,document.getElementById("wallSlidera4").style.opacity=.25);document.getElementById("wall_"+a+"_c1").style.background=Y[0];document.getElementById("wall_"+
a+"_c2").style.background=Y[1];Vb()}function de(a){return'<div id="wallSlidera'+a+'" class="winSliderCont" style="width:100%;height:16px;"><div id="wallSliderb'+a+'" class="winSliderInner" style="position:relative;top:-10px;left:43%;height:32px;width:32px;transition:0.2s;"></div></div>'}
function fb(){var a=cb("Wallpaper");if(a)try{var b=a.split(P);Zd=b[0];$d=b[1];var d=b[2];ae=b[3];W=parseInt(b[4],10);"so"!=Zd.slice(0,2)&&"li"!=Zd.slice(0,2)&&"ra"!=Zd.slice(0,2)&&ce(0);Y=d.split("|");fe()}catch(e){ce(0)}else ce(0)}function ge(){for(var a="",b=0;b<Y.length;b++)a+=Y[b]+"|";a=a.slice(0,-1);Cc("Wallpaper",Zd+P+$d+P+a+P+ae+P+W+P)}
function ce(a){Zd="radial-gradient(";$d="circle at 90% 24%, ";Y=["hsl(26,100%,50%)","hsl(281,100%,33%) 70%"];Sc=0;ae="non";W=0;try{X.removeItem("Wallpaper")}catch(b){}fe();document.getElementById(a)&&Tb(a)}function cd(a){var b=Math.round(a.clientX/document.getElementById("Wallpaper").offsetWidth*100);a=Math.round(a.clientY/document.getElementById("Wallpaper").offsetHeight*100);$d="circle at "+b+"% "+a+"%,";fe()}
function ee(a){var b=ae;if(b!==ae){for(var d in C[a].D[2].v)"&"==C[a].D[2].v[d].Text[0]&&(C[a].D[2].v[d].Text=C[a].D[2].v[d].Text.split(";")[1]);"non"==b?(C[a].D[2].v[0].Text="&#10004;\tNormal",W=0,ae="non",fe()):"fM"==b?(C[a].D[2].v[1].Text="&#10004;\tFollow Mouse",W=1,ae="fM"):"tD"==b&&(C[a].D[2].v[1].Text="&#10004;\tFollow Mouse",W=1,ae="tD");md(a,{clientX:0,clientY:0})}}
function Uc(a,b){var d=x.O.parentNode.offsetWidth,e=x.O.parentNode.offsetLeft;b=b.clientX-document.getElementById(a).offsetLeft-e-F;b-=x.O.offsetWidth/2;b=b/(d-x.O.offsetWidth)*100;0>b?b=0:100<b&&(b=100);d=(d-x.O.offsetWidth)/d;Ib(b.toFixed(2)+"%");x.O.style.left=b*d+"%";Z[Sc-1]=b/100;d="";document.getElementById("wall_"+a+"_Ch").checked&&(d=" "+Math.round(100*Z[3])+"%");Y[be-1]="hsl("+Math.round(360*Z[0])+","+Math.round(100*Z[1])+"%,"+Math.round(100*Z[2])+"%)"+d;fe();document.getElementById("wall_"+
a+"_c1").style.background=Y[0];document.getElementById("wall_"+a+"_c2").style.background=Y[1]}function md(a,b){ge();sd();x.O.style.transition="0.2s";document.getElementById(a+"Cont")&&(document.getElementById(a+"Cont").style.backgroundColor="#fff");"non"!=ae&&W?cd(b):fe();Sc=0}
function Gd(a,b){if(isFinite(b))document.getElementById("wall_"+a+"_"+be).classList.remove("uButtonGreen"),document.getElementById("wall_"+a+"_"+be).classList.add("uButtonGrey"),document.getElementById("wall_"+a+"_"+b).classList.remove("uButtonGrey"),document.getElementById("wall_"+a+"_"+b).classList.add("uButtonGreen"),be=b,Tb(a);else if("Ch"===b)document.getElementById("wall_"+a+"_"+b).checked?document.getElementById("wallSlidera4").style.opacity=.25:document.getElementById("wallSlidera4").style.opacity=
1;else if("f"!=b){var d=Zd.slice(0,1);document.getElementById("wall_"+a+"_"+d).classList.remove("uButtonGreen");document.getElementById("wall_"+a+"_"+d).classList.add("uButtonGrey");document.getElementById("wall_"+a+"_"+b).classList.remove("uButtonGrey");document.getElementById("wall_"+a+"_"+b).classList.add("uButtonGreen");"r"===b?document.getElementById("wall_"+a+"_f").classList.remove("uButtonDisabled"):document.getElementById("wall_"+a+"_f").classList.add("uButtonDisabled");"s"==b?(Zd="so",document.getElementById("wallSlidera4").style.opacity=
document.getElementById("wallP").style.opacity=.25,document.getElementById("wall_"+a+"_Ch").checked=!1,W=0):("l"==b?(Zd="linear-gradient(",$d="0deg, ",W=0):"r"==b&&(Zd="radial-gradient(",$d="circle at 90% 24%, "),document.getElementById("wallSlidera4").style.opacity=document.getElementById("wallP").style.opacity=1,document.getElementById("wall_"+a+"_f").classList.contains("uButtonGreen")&&(W=1));fe();ae="non";ee(a);md(a,{clientX:0,clientY:0})}else W?(document.getElementById("wall_"+a+"_f").classList.remove("uButtonGreen"),
document.getElementById("wall_"+a+"_f").classList.add("uButtonGrey"),W=0):(document.getElementById("wall_"+a+"_f").classList.remove("uButtonGrey"),document.getElementById("wall_"+a+"_f").classList.add("uButtonGreen"),W=1);ge()}
function Vb(){document.getElementById("wallSlidera1");document.getElementById("wallSliderb1");var a=document.getElementById("wallSliderb1"),b=a.parentNode.offsetWidth;a=(b-a.offsetWidth)/b;document.getElementById("wallSliderb1").style.left=100*Z[0]*a+"%";document.getElementById("wallSliderb2").style.left=100*Z[1]*a+"%";document.getElementById("wallSliderb3").style.left=100*Z[2]*a+"%";document.getElementById("wallSliderb4").style.left=100*Z[3]*a+"%"}
function fe(){if("so"==Zd.slice(0,2))document.getElementById("Wallpaper").style.background=Y[0];else{for(var a=Zd+$d,b=0;b<Y.length;b++)a+=Y[b]+", ";a=a.slice(0,-2);document.getElementById("Wallpaper").style.background=a+")"}document.getElementById("cpy").style.color="";document.getElementsByClassName("ubLink")[0].style.color=""};window.Win_errorHandler=function(a){ta&&h("Error detected:<br><br>"+a.message+"<br><br>in file "+a.filename+"<br>in Line: "+a.lineno+", Columb: "+a.colno+'<br><button type="button" id="_errNt" class="uButtons uButtonGrey" style="margin-top:6px">Don&apos;t show errors</button>')};function Cd(){ta=!ta;Cc("showErrors",ta);yb()}function yb(){var a="Notify on Errors";a=ta?'<span style="color:#0F0;">&#10004;</span>'+a:'<span style="color:#f00;">&#10008;</span>'+a;C[0].ea[6].Text=a};
